### PR TITLE
Fix regression in util.toDefaultValue not returning the data types. Closes #3324, #3002 and #3410

### LINKED ISSUE #3324: sequelize.Utils.toDefaultValue(Sequelize.UUIDV4) returns empty object
**Is**
``sequelize.Utils.toDefaultValue(Sequelize.UUIDV4)`` returns empty object ({})

**Expected**
``sequelize.Utils.toDefaultValue(Sequelize.UUIDV4)`` to return valid UUIDV4

Sequelize version: **2.0.4**
Was OK in Sequelize **2.0.0-RC3**

## Test ##

**Code:**
https://bitbucket.org/tiblu/experiments/src/3e382d9f599860278cc341f6888a0cd29c393ab3/sequelize/models/defaultValue.js?at=master
```
'use strict';

var Sequelize = require('sequelize');
var lodash = require('lodash');


var sequelize = new Sequelize('postgres://experiments:experiments@localhost:5433/experiments',
    {
        "logging": console.log,
        "sync": {
            "force": true,
            "logging": console.log
        },
        "define": {
            "underscored": false,
            "freezeTableName": false,
            "syncOnAssociation": false,
            "charset": "utf8",
            "collate": "utf8_general_ci",
            "timestamps": true,
            "paranoid": true
        },
        "omitNull": true
    }
);

sequelize.sync().then(function () {
    console.log('---------------- Sync success ----------------');
    var expectedToBeUUID = sequelize.Utils.toDefaultValue(Sequelize.UUIDV4);
    console.log('sequelize.Utils.toDefaultValue(Sequelize.UUIDV4) = ', expectedToBeUUID, typeof expectedToBeUUID);
    console.log('Sequelize.UUIDV4 lodash.isFunction = ', typeof sequelize.Utils.toDefaultValue(Sequelize.UUIDV4));
    console.log('sequelize.Utils.toDefaultValue is = ', sequelize.Utils.toDefaultValue); // Lets see what function body is...
    console.log('Sequelize.UUIDV4 is = ', Sequelize.UUIDV4); // Lets see what Sequelize.UUIDV4 is ...
    console.log('Sequelize.UUIDV4 lodash.isFunction = ', lodash.isFunction(Sequelize.UUIDV4));
});
```

**Output:**
```
---------------- Sync success ----------------
sequelize.Utils.toDefaultValue(Sequelize.UUIDV4) =  {} object
Sequelize.UUIDV4 lodash.isFunction =  object
sequelize.Utils.toDefaultValue is =  function (value) {
    if (lodash.isFunction(value)) {
      return value();
    } else if (value instanceof DataTypes.UUIDV1) {
      return uuid.v1();
    } else if (value instanceof DataTypes.UUIDV4) {
      return uuid.v4();
    } else if (value instanceof DataTypes.NOW) {
      return Utils.now();
    } else {
      return value;
    }
  }
Sequelize.UUIDV4 is =  function () {
  if (!(this instanceof UUIDV4)) return new UUIDV4();
  ABSTRACT.apply(this, arguments);
}
Sequelize.UUIDV4 lodash.isFunction =  true
```

### PR DESCRIPTION
**Pull request by BridgeAR**
I'm uncertain if UUIDV1 and UUIDV4 is actually right for mysql and mssql. I guess it should be just as the general UUID? Fixes #3324 <s>(can't reproduce the error - seems to be fixed already).</s>

### CODE REVIEW

**Comment by mickhansen** [comment]
Only postgres has native `UUID` types, for mysql and other dialects we generate one with `node-uuid`

File: lib/utils.js [hunk 1]
```diff
@@ -219,8 +218,12 @@ var Utils = module.exports = {
...
 
   toDefaultValue: function(value) {
-    if (lodash.isFunction(value)) {
-      return value();
+    if (typeof value === 'function') {
+      if (value.key) {
+        return value().key;
+      } else {
+        return value();
+      }
```
Comment (BridgeAR) [inline lib/utils.js]: Can you come up with something better?

File: lib/model.js [hunk 2]
```diff
@@ -1792,6 +1794,13 @@ module.exports = (function() {
     }
   };
 
+  Model.prototype.__getDefaultTimestamp = function(attr) {
+    if (!!this.rawAttributes[attr] && !!this.rawAttributes[attr].defaultValue) {
+      return Utils.toDefaultValue(this.rawAttributes[attr].defaultValue);
+    }
+    return undefined;
+  };
+
```
Comment (BridgeAR) [inline lib/model.js]: I'd actually remove the old __getTimestamp (It's only used twice right now) and only always __getDefaultTimestamp in combination with Utils.now(this.sequelize.options.dialect). What do you think?

**Comment by BridgeAR** [comment]
Ready for review

File: lib/model.js [hunk 3]
```diff
@@ -1792,6 +1794,13 @@ module.exports = (function() {
     }
   };
 
+  Model.prototype.__getDefaultTimestamp = function(attr) {
```
Comment (mickhansen) [inline lib/model.js]: We're chaing to `$` prefix for privates.

File: lib/model.js [hunk 4]
```diff
@@ -1252,11 +1252,13 @@ module.exports = (function() {
...
 
+      var now = Utils.now(this.sequelize.options.dialect);
+
       if (createdAtAttr && !values[createdAtAttr]) {
-        values[createdAtAttr] = this.__getTimestamp(createdAtAttr);
+        values[createdAtAttr] = this.__getDefaultTimestamp(createdAtAttr) || now;
       }
       if (updatedAtAttr && !values[updatedAtAttr]) {
-        values[updatedAtAttr] = this.__getTimestamp(updatedAtAttr);
+        values[updatedAtAttr] = this.__getDefaultTimestamp(updatedAtAttr) || now;
```
Comment (mickhansen) [inline lib/model.js]: Couldnt defaulTtimestamp just return now?

Comment (BridgeAR) [inline lib/model.js]: That's what getTimestamp does right now. The whole point in my change though is that now will not be in the return value of the function. If you set now twice in a row for updatedAt and createdAt it differs for some parts of a millisecond and produces race condition in our tests.

File: lib/utils.js [hunk 5]
```diff
@@ -219,8 +218,12 @@ var Utils = module.exports = {
   },
 
   toDefaultValue: function(value) {
-    if (lodash.isFunction(value)) {
-      return value();
+    if (typeof value === 'function') {
+      if (value.key) {
+        return value().key;
```
Comment (mickhansen) [inline lib/utils.js]: what is `value.key`?
If it's to detect a sequelize method use `_isSequelizeMethod` instead and then the proper handler (usually toString())

File: lib/model.js (hunk 4 above)
Comment (mickhansen) [inline lib/model.js]: I see.

**Comment by BridgeAR** [comment]
Ready for merge

**Comment by BridgeAR** [comment]
I added a test for #3002 and #3410 so they can be closed too. Still waiting for merge ;)

File: lib/instance.js [hunk 6]
```diff
@@ -1024,7 +1025,7 @@ module.exports = (function() {
         delete defaults[this.Model._timestampAttributes.deletedAt];
       }
 
-      if (Object.keys(defaults).length) {
+      if (Object.keys(defaults).length !== 0) {
```
Comment (mickhansen) [inline lib/instance.js]: Any reason for this?

File: lib/utils.js [hunk 7]
```diff
@@ -219,8 +218,13 @@ var Utils = module.exports = {
   },
 
   toDefaultValue: function(value) {
-    if (lodash.isFunction(value)) {
-      return value();
+    if (typeof value === 'function') {
+      var tmp = value();
+      if (tmp instanceof DataTypes.ABSTRACT) {
```
Comment (mickhansen) [inline lib/utils.js]: You might also want to check `instanceof` when value is not a function, since default values should be `new()`'ed when the model is define (although they might not be but would be a good future proof to have.

File: lib/instance.js (hunk 6 above)
Comment (BridgeAR) [inline lib/instance.js]: I prefer the explicit one check. I'm uncertain if V8 handles it faster but this would not be measurable if. So it's just the style^^

Comment (mickhansen) [inline lib/instance.js]: Then there's really no reason to change it. It's better to keep style changes out of functional PR's so they can be discucssed seperately. I prefer the other style :)

File: lib/utils.js (hunk 7 above)
Comment (BridgeAR) [inline lib/utils.js]: Hm, right now there's no call that could reach that point and I doubt that it's possible to know when to call new in toDefaultValue.

**Comment by BridgeAR** [comment]
It's back to the old style

**Comment by BridgeAR** [comment]
Rebased

File: lib/utils.js (hunk 7 above)
Comment (mickhansen) [inline lib/utils.js]: Defining a model should be calling `new` on it, so we have to handle both cases.

File: lib/utils.js [hunk 8]
```diff
@@ -139,7 +138,7 @@ var Utils = module.exports = {
             delete attributes[attribute];
           }
 
-          if (_.isPlainObject(attributes[attribute])) {
+          if (lodash.isPlainObject(attributes[attribute])) {
```
Comment (mickhansen) [inline lib/utils.js]: Why `lodash` insteadof `_`?
