### PR TITLE
fix: sequelize.where col not null (#11447)

### LINKED ISSUE #11447: Sequelize.where col not null
## Issue Description

Can't query col is not NULL with Sequelize.where function.

### What are you doing?
Write a select query with the following where state.

```
where: [{}, 
    sequelize.where(sequelize.col('id'), Op.ne, null),
    {'id': {
        [Op.ne]: null
    }}]
```

### What do you expect to happen?

The first one is for not getting `literal replacements` error but it's a different topic.
Second and the third object should generate the same `id IS NOT NULL`.

### What is actually happening?

The second (`sequelize.where(sequelize.col('id'), Op.ne, null)`) generate `id IS NULL`.

```
id IS NULL AND id IS NOT NULL
```

### Environment

- Sequelize version: 5.18.4 
- Node.js version: v12.0.0
- Operating System: OSX -> Docker node:12.0 container
- MySql version: 5.7.23

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): MySQL
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

### LINKED ISSUE #11452: Error: Support for literal replacements in the `where` object has been removed.
### What are you doing?
Just copy and past it to the `getWhereConditions` unit test in `test/unit/sql/where.test.js` file and run `test-unit-mysql`:

```js
    testsql([current.where(current.col('name'), null), current.where(current.fn('SUM', current.col('hours')), '>', 0)], {
      default: '([name] IS NULL AND SUM([hours]) > 0)'
    });
```

### What do you expect to happen?

Correct me if I'm wrong but it should pass.

### What is actually happening?

Get an error:
`Error: Support for literal replacements in the `where` object has been removed.`

```
Output here
```

### Additional context

If you put an empty object to the where array, then it will pass and generate the correct output.
```js
   testsql([{}, current.where(current.col('name'), null), current.where(current.fn('SUM', current.col('hours')), '>', 0)], {
      default: '([name] IS NULL AND SUM([hours]) > 0)'
    });
```

### Environment

 - Sequelize version: 5.18.4
 - Node.js version: v12.0.0
 - Operating System: OSX -> Docker node:12.0 container
 - MySql version: 5.7.23

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): MySQL
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time... but I'll try to fix when I'll have time
- [ ] No, I don't have the time and I wouldn't even know how to start.

### PR DESCRIPTION
**Pull request by dodderjs**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Closes #11447
Closes #11452

### CODE REVIEW

File: lib/dialects/abstract/query-generator.js [hunk 1]
```diff
@@ -2070,7 +2070,16 @@ class QueryGenerator {
       if (value && value instanceof Utils.SequelizeMethod) {
         value = this.getWhereConditions(value, tableName, factory, options, prepend);
 
-        return value === 'NULL' ? `${key} IS NULL` : [key, value].join(` ${smth.comparator} `);
+        if (value === 'NULL') {
```
Comment (sushantdhiman) [inline lib/dialects/abstract/query-generator.js]: Coverage is down for these lines, Can you add additional unit test for this case?

Comment (dodderjs) [reply lib/dialects/abstract/query-generator.js]: I just added some to test query-generator.test.js and some for utils.test.js.
