### PR TITLE
fix(sqlite): describeTable now returns unique constraint and references

### LINKED ISSUE #7078: Sqlite remove/change/rename column don't pass foreign key references along in the new table
## What you are doing?
I'm trying to rename a column on an Sqlite db. I use `renameColumn` on the `QueryInterface` that, in the Sqlite case, is going to call `renameColumn` on the `SQLiteQueryInterface`.

## What do you expect to happen?
I expect that:
1) a temporary table is created equal to the first one (except the renamed column) including foreign key references.
2) data is copied over to the temporary table
3) old table is deleted
4) a new table is created equal to the first one (except the renamed column) including foreign key references.
5) data is copied over to the new table

## What is actually happening?
1) a temporary table is created equal to the first one (except the renamed column) **NOT including foreign key references**.
2) data is copied over to the temporary table
3) old table is deleted
4) a new table is created equal to the first one (except the renamed column) **NOT including foreign key references**.
5) data is copied over to the new table

This is the original table:
```SQL
CREATE TABLE `matches` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `hash` VARCHAR(200) NOT NULL UNIQUE, `alertId` INTEGER REFERENCES `alerts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
```

This is the table after the renameColumn on 'hash' -> 'foo'
```SQL
CREATE TABLE `matches` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `foo` VARCHAR(200) NOT NULL, `alertId` INTEGER)
```

__Dialect:__ sqlite
__Database version:__ 3.9.x
__Sequelize version:__ 3.24.x

### PR DESCRIPTION
**Pull request by dyc3**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Fixes #7078 

For the sqlite dialect, I added an additional query for describeTable to get the constraints for the columns via showIndexes. I also added a new test for this behavior, and updated existing tests to reflect the new behavior. Currently, this only fixes unique constraints.

I'm intentionally making this a draft until we can fix the foreign key thing because I don't know how those work, and so we can put this fix in v5 as well.

I'm also not really sure if the changes I made to the tests are valid

### CODE REVIEW

File: lib/dialects/sqlite/query-interface.js [hunk 1]
```diff
@@ -39,7 +40,7 @@ class SQLiteQueryInterface extends QueryInterface {
     options = options || {};
 
     const fields = await this.describeTable(tableName, options);
-    fields[attributeName] = this.normalizeAttribute(dataTypeOrOptions);
+    _.assign(fields[attributeName], this.normalizeAttribute(dataTypeOrOptions));
```
Comment (sushantdhiman) [inline lib/dialects/sqlite/query-interface.js:43]: Why `assign` ?

Comment (dyc3) [reply lib/dialects/sqlite/query-interface.js:43]: To not overwrite existing properties on the `fields[attributeName]` object. Effectively like applying a delta. `Object.assign()` would also work.

**Comment by sushantdhiman** [comment]
Tests are failing

File: lib/dialects/sqlite/query-interface.js (hunk 1 above)
Comment (sushantdhiman) [reply lib/dialects/sqlite/query-interface.js:43]: Use `Object.assign`

**Comment by dyc3** [comment]
Other dialects appear to be failing on the new tests that I created. It appears other dialects don't return the `unique` constraint on columns when you run `describeTables()`. Should we add that to other dialects? Or just only run the new tests for the `sqlite` dialect?

**Comment by dyc3** [comment]
Also, should I rebase this branch to target `v5` instead? Or would it be easier to make an additional PR targeting `v5`?

**Comment by sushantdhiman** [comment]
`master` is fine for now, after this is merged you may open similar PR for `v5` branch

File: test/integration/model/sync.test.js [hunk 2]
```diff
@@ -215,12 +215,14 @@ describe(Support.getTestDialectTeaser('Model'), () => {
...
             // SQLite doesn't treat primary key as index
-            expect(results).to.have.length(4);
+            // However it does create an extra "autoindex", except primary == false
+            expect(results).to.have.length(4 + 1);
           } else {
             expect(results).to.have.length(4 + 1);
             expect(results.filter(r => r.primary)).to.have.length(1);
           }
 
+          expect(results.filter(r => r.name === 'sqlite_autoindex_testSyncs_1')).to.have.length(1);
```
Comment (sushantdhiman) [inline test/integration/model/sync.test.js:225]: You are talking about this unique index, right? It can be wrapped with `if (dialect === 'sqlite')` statement

**Comment by dyc3** [comment]
I'm unsure why the tests are failing now, I tried running the postgres dialect integration tests on the master branch and those aren't successful. I'm unable to run the integration tests for mssql, mysql, and mariadb for some reason.

**Comment by dyc3** [comment]
Oh, nevermind. It looks like just appveyor is failing now. Something to do with uploading code coverage?

**Comment by dyc3** [comment]
I'll start working on preserving foreign keys tomorrow, if I can figure out how that works.

File: lib/dialects/sqlite/query-generator.js [hunk 3]
```diff
@@ -418,7 +418,8 @@ class SQLiteQueryGenerator extends MySqlQueryGenerator {
     ).join(', ');
     const attributeNamesExport = Object.keys(attributes).map(attr => this.quoteIdentifier(attr)).join(', ');
 
-    return `${this.createTableQuery(backupTableName, attributes).replace('CREATE TABLE', 'CREATE TEMPORARY TABLE')
+    // Temporary tables don't support foreign keys, so creating a temporary table will not allow foreign keys to be preserved
+    return `${this.createTableQuery(backupTableName, attributes)
```
Comment (sushantdhiman) [inline lib/dialects/sqlite/query-generator.js:422]: :+1:

**Comment by sushantdhiman** [comment]
LGTM @dyc3 , ready for merge?

**Comment by dyc3** [comment]
@sushantdhiman Yup!
