### PR TITLE
fix(postgres): update upsert regex to match the last `RETURNING *`

### LINKED ISSUE #11523: Unable to upsert on postgres text containing "RETURNING *" substring
## Issue Description

When using upsert on postgres, the string `RETURNING *` anywhere inside a text or json column value is being replaced with `RETURNING \"id\" INTO primary_key`. Besides changing the data to be upserted, this also makes it throw an error when inserting or updating into a JSON column since its not valid JSON.

### What are you doing?

**Here is the link to the SSCCE for this issue:** https://github.com/papb/sequelize-sscce/pull/9

### What do you expect to happen?

It should be possible to upsert a text or JSON value that happens to contain the substring `RETURNING *`.

### What is actually happening?

The `RETURNING *` substring in the input is being replaced with `RETURNING \"id\" INTO primary_key`

### Environment

- Sequelize version: 5.19.4 and 4.44.3
- Node.js version: 10.16.3
- Operating System: Ubuntu 14.04.5 LTS

### How does this problem relate to dialects?

I think this problem happens only for the following dialect(s): postgres

### Would you be willing to resolve this issue by submitting a Pull Request?

No, I don't have the time and I wouldn't even know how to start.

### PR DESCRIPTION
**Pull request by Americas**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Fixes #11523

Postgres' upsert query generator replaces the first `RETURNING *` it finds on the insert and update query, so if the data being added has that string, it replaces it (so it replaces the wrong `RETURNING *`) changing the input data and messing with the the final query.

This PR updates the replace method to use a regex with a negative lookahead so it only chooses the last `RETURNING *` in the query.

### CODE REVIEW

**Comment by papb** [comment]
I have edited

> Fixes issue #11523.

to the following

> Fixes #11523

so that GitHub detects the fix automatically.

**Comment by papb** [comment]
By the way, I have a question, was [the SSCCE (papb/sequelize-sscce#9)](https://github.com/papb/sequelize-sscce/pull/9) useful to you? Or do you think you could have fixed the issue as easily without it?

**Comment by Americas** [comment]
> By the way, I have a question, was [the SSCCE (papb/sequelize-sscce#9)](https://github.com/papb/sequelize-sscce/pull/9) useful to you? Or do you think you could have fixed the issue as easily without it?

I used it yes, just changed the log to an error if the result was different from the expected. It helps to have the problem easily available, otherwise there is this great setup cost to start analyzing the issue :smile:

**Comment by papb** [comment]
@Americas Nice! I'm happy that my idea of an SSCCE repo was useful then :)

**Comment by papb** [comment]
I was thinking... Would you be willing to add an explicit test for the [JSONB case](https://github.com/papb/sequelize-sscce/blob/93794ffcbf245fa279b5f693730ff8ffde4eed10/src/sscce.js#L23) as well?

File: lib/dialects/postgres/query-generator.js [hunk 1]
```diff
@@ -347,8 +347,10 @@ class PostgresQueryGenerator extends AbstractQueryGenerator {
     const insert = this.insertQuery(tableName, insertValues, model.rawAttributes, upsertOptions);
     const update = this.updateQuery(tableName, updateValues, where, upsertOptions, model.rawAttributes);
 
-    insert.query = insert.query.replace('RETURNING *', `RETURNING ${primaryField} INTO primary_key`);
-    update.query = update.query.replace('RETURNING *', `RETURNING ${primaryField} INTO primary_key`);
+    if (options.returning) {
+      insert.query = insert.query.replace(/RETURNING \*(?![\s\S]*RETURNING \*)/, `RETURNING ${primaryField} INTO primary_key`);
```
Comment (SimonSchick) [inline lib/dialects/postgres/query-generator.js]: Nit: Regex should be moved to a constant.

Comment (Americas) [reply lib/dialects/postgres/query-generator.js]: Done.

**Comment by Americas** [comment]
> I was thinking... Would you be willing to add an explicit test for the [JSONB case](https://github.com/papb/sequelize-sscce/blob/93794ffcbf245fa279b5f693730ff8ffde4eed10/src/sscce.js#L23) as well?

Added JSON example from SSCCE and a normal example.
