### PR TITLE
fix(model): handle Symbol-only where clauses

### LINKED ISSUE #8406: Paranoid overrides [Op.or] query
## What are you doing?
For the login functionality, I am trying to find a user who has username or email equal to X. `User` model has paranoid mode turned on.

```typescript
const userPromise = User.findOne({
      where: {
        [Op.or]: [
          {
            username
          },
          {
            email: username
          },
        ],
      },
    })
```

## What do you expect to happen?
```sql
SELECT `userId`, `username`, `email`, `displayName`, `active`, `password`, `createdAt`, `updatedAt`, `deletedAt` FROM `User` AS `User` WHERE (`User`.`deletedAt` > CURRENT_TIMESTAMP OR `User`.`deletedAt` IS NULL) AND (`User`.`username` = 'vladmiller' OR `User`.`email` = 'vladmiller')  LIMIT 1;
```

## What is actually happening?
But generated SQL query ignored my [Op.or] statement. Seems like `paranoid` mode overrides any `or` statement included in the query.

```sql
SELECT `userId`, `username`, `email`, `displayName`, `active`, `password`, `createdAt`, `updatedAt`, `deletedAt` FROM `User` AS `User` WHERE (`User`.`deletedAt` > CURRENT_TIMESTAMP OR `User`.`deletedAt` IS NULL) LIMIT 1;
```

__Dialect:__ mysql
__Sequelize version:__ 4.13.2
__Tested with master branch:__ Yes

**Note :** _Your issue may be ignored by maintainers if its not tested against `master` branch OR does not follow issue template._

### PR DESCRIPTION
**Pull request by gabegorelick**
Closes #8406

### Pull Request check-list

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)? **N/A**
- [x] Did you follow the commit message conventions explained in CONTRIBUTING.md?

### Description of change

Fixes paranoid clauses where the `where` only has symbols. See https://github.com/sequelize/sequelize/issues/8406.

I'll also work on adding more tests so we can completely close https://github.com/sequelize/sequelize/issues/8423, but this is ready to merge if we want a quick fix for #8406, which is kind of a big issue for a lot of users.

### CODE REVIEW

File: lib/utils.js [hunk 1]
```diff
@@ -599,3 +599,9 @@ function getComplexSize(obj) {
   return Array.isArray(obj) ? obj.length : getComplexKeys(obj).length;
 }
 exports.getComplexSize = getComplexSize;
+
+// Returns true if a where clause is empty
+function whereIsEmpty(obj) {
```
Comment (eseliger) [inline lib/utils.js]: As this returns boolean, `isWhereEmpty`sounds more natural to me, what do you think? :)

**Comment by sushantdhiman** [comment]
Thanks for this fix 👍

**Comment by PaulThompson** [comment]
This (release 4.13.7) fixed an issue for me, hasMany association get with a where clause.
