### PR TITLE
8336 Adds support for postgres infinity timestamp

### LINKED ISSUE #8336: Support for Infinity and -Infinity Dates in PostgreSQL
## What are you doing?
Trying to insert infinity and -infinity into a PostgreSQL column where the attribute has a type of Date.

Definition:
```js
'deletedAt': {
    type: DataTypes.DATE,
    field: 'deleted_at',
    allowNull: false,
    defaultValue: Infinity
}
```

## What do you expect to happen?
For the record to be inserted correctly.

## What is actually happening?
```sh
{ SequelizeValidationError: null is not a valid date
    at DATE.validate (node_modules/sequelize/lib/data-types.js:312:11)
    at Object.escape (node_modules/sequelize/lib/dialects/abstract/query-generator.js:898:26)
    at Object.insertQuery (node_modules/sequelize/lib/dialects/abstract/query-generator.js:187:28)
    at QueryInterface.insert (node_modules/sequelize/lib/query-interface.js:519:37)
    at Promise.try.then.then.then (node_modules/sequelize/lib/model.js:3591:56)
    at tryCatcher (node_modules/sequelize/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules/sequelize/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (node_modules/sequelize/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (node_modules/sequelize/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (node_modules/sequelize/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (node_modules/sequelize/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (node_modules/sequelize/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (node_modules/sequelize/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5) name: 'SequelizeValidationError', errors: [] }
```

__Dialect:__ postgres
__Dialect version:__ Stable???
__Database version:__ 9.6 (Current)
__Sequelize version:__ 4.8.4
__Tested with master branch:__ Yes

### PR DESCRIPTION
**Pull request by mkaufmaner**
### Pull Request check-list
- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in CONTRIBUTING.md?

### Description of change 
Closes #8336

See #8356 (Partial fix still requires further work)
See #8339

### CODE REVIEW

**Comment by mkaufmaner** [comment]
Please review!  Increase coverage by 0.05%!  Woot!

Please note, this **WON'T** affect user defined setters.  I think a major refactor of data types should go into v5.

File: lib/data-types.js [hunk 1]
```diff
@@ -315,6 +336,22 @@ DATE.prototype.validate = function validate(value) {
...
+DATE.prototype._sanitize = function _sanitize(value, options) {
+  if ((!options || options && !options.raw) && !(value instanceof Date) && !!value) {
+    value = new Date(value);
+  }
+
+  return value;
+};
+
+DATE.prototype._isChanged = function _isChanged(value, originalValue) {
+  if (originalValue && !!value && value instanceof Date && originalValue instanceof Date && value.getTime() === originalValue.getTime()) {
```
Comment (sushantdhiman) [inline lib/data-types.js]: Multi line this condition check

File: lib/dialects/postgres/data-types.js [hunk 2]
```diff
@@ -34,9 +34,44 @@ module.exports = BaseTypes => {
...
+      value = BaseTypes.DATEONLY.prototype._sanitize.call(this, value);
+    }
+
     return value;
   };
 
+  DATEONLY.prototype._isChanged = function _isChanged(value, originalValue) {
+    if (
+      originalValue && !!value &&
+      (value === originalValue || value instanceof Date && originalValue instanceof Date && value.getTime() === originalValue.getTime())
```
Comment (sushantdhiman) [inline lib/dialects/postgres/data-types.js]: move this to base type? this logic should be honored by all dialects for DATEONLY

File: lib/dialects/postgres/data-types.js [hunk 3]
```diff
@@ -138,6 +194,43 @@ module.exports = BaseTypes => {
...
+      value = new Date(value);
+    }
+
+    return value;
+  };
+
+  DATE.prototype._isChanged = function _isChanged(value, originalValue) {
+    if (
+      originalValue && !!value &&
+      (value === originalValue || value instanceof Date && originalValue instanceof Date && value.getTime() === originalValue.getTime())
```
Comment (sushantdhiman) [inline lib/dialects/postgres/data-types.js]: This logic is again same `Postgres.DATEONLY._isChanged` (which I have suggested to move to `BaseTypes.DATEONLY`)

May be `BaseType.DATE` should have this logic, `BaseType.DATEONLY` should call that and dialect would never need to override it

**Comment by mkaufmaner** [comment]
@sushantdhiman I will address these in the morning.  Thanks for the quick response!

File: lib/dialects/postgres/data-types.js (hunk 3 above)
Comment (mkaufmaner) [reply lib/dialects/postgres/data-types.js]: The only reason I extended this into postgres was because it was the only dialect where the `originalValue` and `value` could be equal (`Infinity === Infinity`).  All others would be `Date.getTime() === Date.getTime()`.

However, after some thought I think you are right in moving it into the `BaseType`.

**Comment by mkaufmaner** [comment]
This is ready to go.  Please finalize reviews :)

File: lib/dialects/postgres/data-types.js [hunk 4]
```diff
@@ -123,6 +155,27 @@ module.exports = BaseTypes => {
     return 'BOOLEAN';
   };
 
+  BOOLEAN.prototype._sanitize = function _sanitize(value) {
```
Comment (sushantdhiman) [inline lib/dialects/postgres/data-types.js]: Why boolean is needed here, its logic looks exactly same as base type

File: lib/dialects/postgres/data-types.js [hunk 5]
```diff
@@ -34,6 +34,38 @@ module.exports = BaseTypes => {
   inherits(DATEONLY, BaseTypes.DATEONLY);
 
   DATEONLY.parse = function parse(value) {
```
Comment (sushantdhiman) [inline lib/dialects/postgres/data-types.js]: DATEONLY shares exact methods with DATE (from same dialect). I would say just call `DATE.*` methods inside DATEONLY as they both are same date types

File: lib/dialects/postgres/data-types.js (hunk 4 above)
Comment (mkaufmaner) [reply lib/dialects/postgres/data-types.js]: Where value === 'f' or 't'.

File: lib/dialects/postgres/data-types.js (hunk 5 above)
Comment (mkaufmaner) [reply lib/dialects/postgres/data-types.js]: hrm. ok

File: lib/dialects/postgres/data-types.js (hunk 4 above)
Comment (sushantdhiman) [reply lib/dialects/postgres/data-types.js]: 👍

**Comment by mkaufmaner** [comment]
@sushantdhiman Changed "Close #8356" to "See #8356".  Also removed DATEONLY.parse entirely.

**Comment by mkaufmaner** [comment]
@sushantdhiman Im not at my normal development environment at the moment but will fix the dateonly in about 7 hours when I wake up.

**Comment by mkaufmaner** [comment]
@sushantdhiman @janmeier  I have put back the DATEONLY.parse method;

```js
DATEONLY.parse = function parse(value) {
	if (value === 'infinity') {
		value = Infinity;
	} else if (value === '-infinity') {
	value = -Infinity;
	}

	return value;
};
```

because the parser types differ from the DATE data type.

DATEONLY:
```js
BaseTypes.DATEONLY.types.postgres = {
	oids: [1082],
	array_oids: [1182]
};
```

DATE:
```js
BaseTypes.DATE.types.postgres = {
	oids: [1184],
	array_oids: [1185]
};
```

If I change the DATEONLY oids then it will break existing functionality supporting varchar columns.

File: test/integration/model/geography.test.js [hunk 6]
```diff
@@ -175,6 +175,52 @@ describe(Support.getTestDialectTeaser('Model'), () => {
       });
     });
 
+    if (current.dialect.name === 'postgres') {
+      describe('GEOGRAPHY(POLYGON, SRID)', () => {
```
Comment (janmeier) [inline test/integration/model/geography.test.js]: I don't see any code changes related to this - tests for something else?

Comment (mkaufmaner) [reply test/integration/model/geography.test.js]: @janmeier Yes, I decided to add some tests to cover GEOGRAPHY types while I was at it because I wanted to increase coverage of the postgres dialect.  Hope this doesn't prevent anything.

Comment (janmeier) [reply test/integration/model/geography.test.js]: Not at all, just wanted to make sure I wasn't missing anything

File: lib/data-types.js [hunk 7]
```diff
@@ -350,6 +393,22 @@ DATEONLY.prototype._stringify = function _stringify(date) {
   return moment(date).format('YYYY-MM-DD');
 };
 
+DATEONLY.prototype._sanitize = function _sanitize(value, options) {
+  if (!options || options && !options.raw) {
+    return moment(value).format('YYYY-MM-DD');
```
Comment (eseliger) [inline lib/data-types.js]: I think this is missing a `!!value` check. Now, we are getting `"Invalid date"` value for `NULL`, resulting in an error.
