### PR TITLE
Fix setting isolation level in MySQL and MariaDB

### LINKED ISSUE #10975: Sequelize does not properly use mysql sessions
## What are you doing?

When I start transaction with `isolationLevel: Sequelize.Transaction.ISOLATION_LEVELS.READ_UNCOMMITTED` :

1. It runs `SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;` after `START TRANSACTION;` so it does not affect the current ongoing transaction as is stated in mysql manual https://dev.mysql.com/doc/refman/8.0/en/set-transaction.html#set-transaction-isolation-level

2. But it affects another transactions that runs on same (reused) connection from pool.

When I start new transaction it always appears in logs with new "session" identifier like `9101e35d-e571-491b-8fc3-c03c6fed1811`. But this is different from mysql session which is defined by sequelize connection and sequelize reuses connections in pool. So when I (or sequelize) change session isolation level for some transaction with sequelize session like `9101e35d-e571-491b-8fc3-c03c6fed1811` it can affect future transactions in different sequelize sessions like `494a41f6-4fe9-4710-9c52-ab016d4d6378` which unhappily used same connection from sequelize connection pool. Once is set session transaction isolation level it will be here permanently for particular sequelize connection not only for current sequelize "session" (or transaction) because sequelize uses connection pool and reuses connections for its "sessions".

```node.js
await sequelize.transaction(async function(transaction)
{
	// Executing (9101e35d-e571-491b-8fc3-c03c6fed1811): START TRANSACTION;
	console.log((await sequelize.query("SELECT @@TX_ISOLATION;", { type: sequelize.QueryTypes.SELECT, transaction }))[0]["@@TX_ISOLATION"]);
	// Executing (9101e35d-e571-491b-8fc3-c03c6fed1811): SELECT @@TX_ISOLATION;
	// REPEATABLE-READ
	await sequelize.query("SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;", { transaction });
	// Executing (9101e35d-e571-491b-8fc3-c03c6fed1811): SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	console.log((await sequelize.query("SELECT @@TX_ISOLATION;", { type: sequelize.QueryTypes.SELECT, transaction }))[0]["@@TX_ISOLATION"]);
	// Executing (9101e35d-e571-491b-8fc3-c03c6fed1811): SELECT @@TX_ISOLATION;
	// READ-UNCOMMITTED
	await sequelize.transaction(async function(transaction)
	{
		// Executing (a8acc202-5d4e-4d7d-ba28-f5ac0378333e): START TRANSACTION;
		console.log((await sequelize.query("SELECT @@TX_ISOLATION;", { type: sequelize.QueryTypes.SELECT, transaction }))[0]["@@TX_ISOLATION"]);
		// Executing (a8acc202-5d4e-4d7d-ba28-f5ac0378333e): SELECT @@TX_ISOLATION;
		// REPEATABLE-READ
		// good as we started new transaction before was first finished we forced sequelize to use new connection so we still have repeatable read
		await sequelize.query("SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;", { transaction });
		// Executing (a8acc202-5d4e-4d7d-ba28-f5ac0378333e): SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
		console.log((await sequelize.query("SELECT @@TX_ISOLATION;", { type: sequelize.QueryTypes.SELECT, transaction }))[0]["@@TX_ISOLATION"]);
		// Executing (a8acc202-5d4e-4d7d-ba28-f5ac0378333e): SELECT @@TX_ISOLATION;
		// READ-UNCOMMITTED
	});
	// Executing (a8acc202-5d4e-4d7d-ba28-f5ac0378333e): COMMIT;
	// Executing (9101e35d-e571-491b-8fc3-c03c6fed1811): COMMIT;
});
await sequelize.transaction(async function(transaction)
{
	// Executing (494a41f6-4fe9-4710-9c52-ab016d4d6378): START TRANSACTION;
	console.log((await sequelize.query("SELECT @@TX_ISOLATION;", { type: sequelize.QueryTypes.SELECT, transaction }))[0]["@@TX_ISOLATION"]);
	// Executing (494a41f6-4fe9-4710-9c52-ab016d4d6378): SELECT @@TX_ISOLATION;
	// READ-UNCOMMITTED
	// so why we have read uncommitted in new session 494a41f6-4fe9-4710-9c52-ab016d4d6378? probably was reused one of above connections
	// Executing (494a41f6-4fe9-4710-9c52-ab016d4d6378): COMMIT;
});
```

Just to clarify this:

``` node.js
await sequelize.transaction({ isolationLevel: Sequelize.Transaction.ISOLATION_LEVELS.READ_UNCOMMITTED }, async function(transaction)...
```

Executes:

```
Executing (95ca9deb-53c4-4327-a6d9-fd07e41539fb): START TRANSACTION;
Executing (95ca9deb-53c4-4327-a6d9-fd07e41539fb): SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
```

So I used `SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;` manually to see what is TX_ISOLATION in between.

**To Reproduce**

1. Create sequelize instance with mysql dialect.
2. Run sample code (in async function)
3. See output and logs

## What do you expect to happen?
Last TX_ISOLATION should be REPEATABLE-READ. Sequelize should start new mysql session for each transaction and change session isolation level before starting transaction. **Or change isolation level using `SET TRANSACTION ISOLATION LEVEL;` immediately before `START TRANSACTION` and then should not be needed to start new mysql session for each transaction**.

## What is actually happening?
Last TX_ISOLATION is READ-UNCOMMITTED. Cannot use isolation levels per transaction.

## Environment
Dialect:
- [x] mysql
- [x] mariadb
Dialect **library** version: any
Database version: any
Sequelize version: 5.8.6
Node Version: any
OS: any
Tested with latest release:
- [x] No
- [ ] Yes, specify that version:

### PR DESCRIPTION
**Pull request by poldridge**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [X] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [X] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [X] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [X] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

Fixes #10975

Setting isolation level does not work in MySQL or MariaDB. For both those dialects the setIsolationLevel query must be executed before the startTransaction query. For postgres the reverse is required, but it must be set before the first query in the transaction. For other dialects, it can be set at any time before or during a transaction.

This drops `SESSION` from the `SET TRANSACTION` queries, in order to set the isolation for a just a single transaction when future transactions in the session don't specify one, and updates MySQL and MariaDB to issue the `SET TRANSACTION` statement before the `START TRANSACTION`.

Three integration tests are added to confirm that changing isolation level works in all dialects. All added tests fail in mysql and mariadb without this fix.

### CODE REVIEW

**Comment by papb** [comment]
Hello! I see you are a first-time contributor, thank you for taking the time to help Sequelize! I hope to see more PRs from you in the future!

Unfortunately I am very time constrained right now so I won't be able to take a closer look at your PR anytime soon... Thanks for the patience :)

**Comment by poldridge** [comment]
No problem. The linked issue is still "status: awaiting investigation" so I figured that might be the case.

File: lib/transaction.js [hunk 1]
```diff
@@ -158,11 +150,18 @@ class Transaction {
...
+  startTransactionWithIsolationLevel() {
+    const queryInterface = this.sequelize.getQueryInterface();
+
+    if ( this.sequelize.dialect.supports.settingIsolationLevelDuringTransaction ) {
+      return queryInterface.startTransaction(this, this.options).then(() => {
+        return queryInterface.setIsolationLevel(this, this.options.isolationLevel);
+      });
+    }
+
+    return queryInterface.setIsolationLevel(this, this.options.isolationLevel).then(() => {
```
Comment (sushantdhiman) [inline lib/transaction.js]: `this.options` as third argument to `setIsolationLevel`

File: lib/transaction.js [hunk 2]
```diff
@@ -158,11 +150,18 @@ class Transaction {
...
-    return this
-      .sequelize
-      .getQueryInterface()
-      .setIsolationLevel(this, this.options.isolationLevel, this.options);
+  startTransactionWithIsolationLevel() {
+    const queryInterface = this.sequelize.getQueryInterface();
+
+    if ( this.sequelize.dialect.supports.settingIsolationLevelDuringTransaction ) {
+      return queryInterface.startTransaction(this, this.options).then(() => {
+        return queryInterface.setIsolationLevel(this, this.options.isolationLevel);
```
Comment (sushantdhiman) [inline lib/transaction.js]: `this.options` as third argument to `setIsolationLevel`

File: lib/transaction.js [hunk 3]
```diff
@@ -127,9 +127,8 @@ class Transaction {
         this.connection.uuid = this.id;
       })
       .then(() => {
-        return this.begin()
+        return this.startTransactionWithIsolationLevel()
```
Comment (sushantdhiman) [inline lib/transaction.js]: Let's keep the method name `begin`

File: test/integration/transaction.test.js [hunk 4]
```diff
@@ -527,6 +527,93 @@ if (current.dialect.supports.transactions) {
...
+                  });
+                });
+              });
+            });
+          })
+        ).to.eventually.be.fulfilled;
+      });
+
+      // mssql is excluded because it implements REPREATABLE READ using locks rather than a snapshot, and will see the new row
+      if (['mariadb', 'mysql', 'postgres', 'postgres-native'].includes(dialect)) {
```
Comment (sushantdhiman) [inline test/integration/transaction.test.js]: Use blacklist like `!['mssql'].includes(dialect)`, this will allow future dialects to accommodate for this test

File: test/integration/transaction.test.js [hunk 5]
```diff
@@ -527,6 +527,93 @@ if (current.dialect.supports.transactions) {
...
+                  });
+                });
+              });
+            })
+          ).to.eventually.be.fulfilled;
+        });
+      }
+
+      // PostgreSQL is excluded because it detects Serialization Failure on commit instead of acquiring locks on the read rows
+      if (['mariadb', 'mysql', 'mssql'].includes(dialect)) {
```
Comment (sushantdhiman) [inline test/integration/transaction.test.js]: Same here, use blacklist

File: test/integration/transaction.test.js [hunk 6]
```diff
@@ -527,6 +527,93 @@ if (current.dialect.supports.transactions) {
```
Comment (sushantdhiman) [inline test/integration/transaction.test.js]: New tests are creating [nested promises](https://medium.com/@pyrolistical/how-to-get-out-of-promise-hell-8c20e0ab0513), please improve that code where you can

**Comment by poldridge** [comment]
Great! Thanks for the review. I'll go over it next week if I can

File: test/integration/transaction.test.js (hunk 6 above)
Comment (poldridge) [reply test/integration/transaction.test.js]: Thanks, this looked like the style other tests in the file were using to me, but I'm happy to adjust it

**Comment by poldridge** [comment]
First time I merged in master the tests failed. Seems like a lot of PRs have had similar issues with random failures, so I force pushed to trigger tests again and it looks good now.

**Comment by papb** [comment]
Thank you @poldridge !
