### PR TITLE
fix(model destroy): Return 0 when options is truncate. 

### LINKED ISSUE #12164: Model.destroy returns NaN as destroyed count
### What are you doing?

Calling `destroy()` on `Model` in order to truncate table. Based on documentation this call should return `Promise<number>` with count of destroyed entries.

**Here is the link to the SSCCE for this issue:** https://github.com/papb/sequelize-sscce/pull/72 

### What do you expect to happen?

Count of destroyed entries

### What is actually happening?

`NaN is returned instead`

### Environment

- Sequelize version: 5.21.7
- Node.js version: v12 
- Operating System: macos
- If TypeScript related: TypeScript version: 3.8

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): postgres, MySQL, mariadb
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

### PR DESCRIPTION
**Pull request by JuarezLustosa**
### Pull Request check-list

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

This close #12164.
 
I was debugging and realize, the [SSCE](https://github.com/papb/sequelize-sscce/pull/72) examples is passing truncate as an option. Therefore truncate on the database does not show affected rows so we can't return the value, thus I found the Postgres NaN in these cases.
 
- I changed the doc adding info about it when use truncate will no show rows affected only on Sqlite do this.
- Fixed Postgres rowCount when queryResult.rowCount isn't returning 
- Fixed MSsql  when data is empty return 0 on isBulkDeleteQuery

### CODE REVIEW

File: lib/dialects/mssql/query.js [hunk 1]
```diff
@@ -214,7 +214,7 @@ class Query extends AbstractQuery {
       return data.length;
     }
     if (this.isBulkDeleteQuery()) {
-      return data[0] && data[0].AFFECTEDROWS;
+      return data[0] && data[0].AFFECTEDROWS || 0;
```
Comment (sobrinho) [inline lib/dialects/mssql/query.js:217]: Probably:

```suggestion
      return data[0] ? data[0].AFFECTEDROWS : 0;
```

Comment (JuarezLustosa) [reply lib/dialects/mssql/query.js:217]: Nice one!
