### PR TITLE
.update include attributes changed by setter methods

### LINKED ISSUE #3221: set() for Virtual datatype does not work when doing updateAttributes()
password_hash: DataTypes.STRING,
    password: { type: DataTypes.VIRTUAL,
        validate: {
            len: {args: [10, 20], msg:"password must be 10-20 characters" }
        },

        set: function(password) {
            var password_hash = bcrypt.hash(password, ...);
            this.setDataValue('password', password);
            this.setDataValue('password_hash', password_hash);
        }
    }

I try to update password:

    user.updateAttributes({ name: 'test', password: "password1" }).then(function(user)) {
        console.log(user);
    });

Which prints out:

```
{ id: 1,
  name: 'test',
  password_hash: '$2a$10$rdNZ4WqG8kLeH.cT2c2N8ONkXAMy5qAPV7cPrsqOgVg.uMncl53CW',
  password: 'password1' }
```

It looks like everything was updated. But actually, the new password hash is never set. It still holds the old password hash when `create()` was called to create the user for the first time. However, the name updates fine.

The SQL output is:

    Executing (default): UPDATE "Users" SET "name"='test', WHERE "id"=1

----
using postgres, sequelize 2.0.0-rc8.

### PR DESCRIPTION
**Pull request by robertfalken**
The update method of an instance keeps track of possible side effect of setter methods and includes affected attributes in the save. Should fix #3221

### CODE REVIEW

File: lib/instance.js [hunk 1]
```diff
@@ -754,13 +754,23 @@ module.exports = (function() {
...
+
     options = options || {};
     if (Array.isArray(options)) options = {fields: options};
 
     this.set(values, {attributes: options.fields});
 
+    // Now we need to figure out which fields were actually affected by the setter.
+    // We build a somewhat weird argument list array that we can apply to _.without
+    changeMemory.unshift(this.changed());
+    affectedBySetter = _.without.apply(this, changeMemory);
```
Comment (mickhansen) [inline lib/instance.js]: Can be expressed more cleanly with `[this.changed()].concat(changeMemory)` i think.

File: lib/instance.js [hunk 2]
```diff
@@ -754,13 +754,23 @@ module.exports = (function() {
    * @alias updateAttributes
    */
   Instance.prototype.update = function(values, options) {
+    var changeMemory = this.changed() || []
+      , affectedBySetter
+      , valuesShouldUpdate;
```
Comment (mickhansen) [inline lib/instance.js]: 'changeMemory' => 'changedBefore'
'afftedBySetter' => 'sideEffects'
'valuesShouldUpdate' => 'fields'

Would be my suggestion to names

File: lib/instance.js (hunk 1 above)
Comment (robertfalken) [inline lib/instance.js]: @mickhansen  do you mean something like this?

    sideEffects = _.without.apply(this, [(this.changed() || [])].concat(changedBefore));
    fields = _.union(Object.keys(values), sideEffects);

Also, do you want me to rewrite history and provide one single commit?

File: lib/instance.js [hunk 3]
```diff
@@ -754,13 +754,23 @@ module.exports = (function() {
...
+
     options = options || {};
     if (Array.isArray(options)) options = {fields: options};
 
     this.set(values, {attributes: options.fields});
 
+    // Now we need to figure out which fields were actually affected by the setter.
+    // We build a somewhat weird argument list array that we can apply to _.without
+    changedBefore.unshift(this.changed());
+    sideEffects = _.without.apply(this, changedBefore);
```
Comment (mickhansen) [inline lib/instance.js]: `.without.apply(this, [this.changed() || []].concat(changedBefore))` would be great yeah. I think it's a bit more easy to understand but i'm not certain that's true :)

**Comment by mickhansen** [comment]
Yes a squash to a single good descriptive commit would be great :)

**Comment by robertfalken** [comment]
It is changed and squashed. Let me know if there's something else I need to or should do.

**Comment by Ghirro** [comment]
This is a good feature implementation but shouldn't the same occur for `Model.update()`? I.e. any virtual setters are run prior to updating?
