### PR TITLE
Fix sequelize.transaction() breaks when used with Promise.mapSeries (…

### LINKED ISSUE #5943: sequelize.transaction() breaks when used with Promise.mapSeries
I use the promise library is bluebird.
When I used transaction before Promise.mapSeries, the transaction will be breaks after some sql, but when I write it in Promise.mapSeries it is correct.
**Before Promise.mapSeries**
```
models = require './models'
Promise = require 'bluebird'
models.sequelize.transaction (t) ->
  models.Order.findAll {
    where:
      pass: false
  }
  .then (orders) ->
    orders = orders[0..2]
    Promise.mapSeries orders, (order) ->
      Promise.all [
        order.getProd()
        order.getFactory()
      ]
      .then (results) ->
        [prod, factory] = results
        models.Bill.findOne {
          where:
            prodId: prod.id
            factoryId: factory.id
        }
      .then (bill) ->
        console.log bill.id
.then ->
  console.log 'ok'
```
**Output**
```
Executing (4829ee34-9be5-4b37-ac8b-e1e6f7235afe): START TRANSACTION;
Executing (4829ee34-9be5-4b37-ac8b-e1e6f7235afe): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (4829ee34-9be5-4b37-ac8b-e1e6f7235afe): SET autocommit = 1;
Executing (4829ee34-9be5-4b37-ac8b-e1e6f7235afe): SELECT `id`, `quantity`, `delivery_time`, `pass`, `createdAt`, `updatedAt`, `prodId`,
`factoryId` FROM `order` AS `order` WHERE `order`.`pass` = false;
Executing (default): SELECT `id`, `code`, `unit`, `price`, `per`, `createdAt`, `updatedAt`, `customerId`, `shapeId` FROM `prod` AS `prod
` WHERE `prod`.`id` = 473;
Executing (default): SELECT `id`, `name`, `createdAt`, `updatedAt` FROM `factory` AS `factory` WHERE `factory`.`id` = 2;
Executing (default): SELECT `id`, `total_order`, `total_ship`, `last_order`, `createdAt`, `updatedAt`, `factoryId`, `prodId` FROM `bill`
 AS `bill` WHERE `bill`.`prodId` = 473 AND `bill`.`factoryId` = 2 LIMIT 1;
1
Executing (default): SELECT `id`, `code`, `unit`, `price`, `per`, `createdAt`, `updatedAt`, `customerId`, `shapeId` FROM `prod` AS `prod
` WHERE `prod`.`id` = 415;
Executing (default): SELECT `id`, `name`, `createdAt`, `updatedAt` FROM `factory` AS `factory` WHERE `factory`.`id` = 1;
Executing (default): SELECT `id`, `total_order`, `total_ship`, `last_order`, `createdAt`, `updatedAt`, `factoryId`, `prodId` FROM `bill`
 AS `bill` WHERE `bill`.`prodId` = 415 AND `bill`.`factoryId` = 1 LIMIT 1;
2
Executing (default): SELECT `id`, `code`, `unit`, `price`, `per`, `createdAt`, `updatedAt`, `customerId`, `shapeId` FROM `prod` AS `prod
` WHERE `prod`.`id` = 520;
Executing (default): SELECT `id`, `name`, `createdAt`, `updatedAt` FROM `factory` AS `factory` WHERE `factory`.`id` = 2;
Executing (default): SELECT `id`, `total_order`, `total_ship`, `last_order`, `createdAt`, `updatedAt`, `factoryId`, `prodId` FROM `bill`
 AS `bill` WHERE `bill`.`prodId` = 520 AND `bill`.`factoryId` = 2 LIMIT 1;
3
Executing (4829ee34-9be5-4b37-ac8b-e1e6f7235afe): COMMIT;
ok
```
**In Promise.mapSeries**
```
models = require './models'
Promise = require 'bluebird'
models.Order.findAll {
  where:
    pass: false
}
.then (orders) ->
  orders = orders[0..2]
  Promise.mapSeries orders, (order) ->
    models.sequelize.transaction (t) ->
      Promise.all [
        order.getProd()
        order.getFactory()
      ]
      .then (results) ->
        [prod, factory] = results
        models.Bill.findOne {
          where:
            prodId: prod.id
            factoryId: factory.id
        }
      .then (bill) ->
        console.log bill.id
    .then ->
      console.log order.id
.then ->
  console.log 'ok'
```
**Output**
```
Executing (default): SELECT `id`, `quantity`, `delivery_time`, `pass`, `createdAt`, `updatedAt`, `prodId`, `factoryId` FROM `order` AS `
order` WHERE `order`.`pass` = false;
Executing (18a7a582-97ef-4e30-a483-a0894d2d84e6): START TRANSACTION;
Executing (18a7a582-97ef-4e30-a483-a0894d2d84e6): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (18a7a582-97ef-4e30-a483-a0894d2d84e6): SET autocommit = 1;
Executing (18a7a582-97ef-4e30-a483-a0894d2d84e6): SELECT `id`, `code`, `unit`, `price`, `per`, `createdAt`, `updatedAt`, `customerId`, `
shapeId` FROM `prod` AS `prod` WHERE `prod`.`id` = 473;
Executing (18a7a582-97ef-4e30-a483-a0894d2d84e6): SELECT `id`, `name`, `createdAt`, `updatedAt` FROM `factory` AS `factory` WHERE `facto
ry`.`id` = 2;
Executing (18a7a582-97ef-4e30-a483-a0894d2d84e6): SELECT `id`, `total_order`, `total_ship`, `last_order`, `createdAt`, `updatedAt`, `fac
toryId`, `prodId` FROM `bill` AS `bill` WHERE `bill`.`prodId` = 473 AND `bill`.`factoryId` = 2 LIMIT 1;
1
Executing (18a7a582-97ef-4e30-a483-a0894d2d84e6): COMMIT;
1
Executing (0f5c5c84-5b20-4a0e-aeaa-ee86b8e57c1b): START TRANSACTION;
Executing (0f5c5c84-5b20-4a0e-aeaa-ee86b8e57c1b): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (0f5c5c84-5b20-4a0e-aeaa-ee86b8e57c1b): SET autocommit = 1;
Executing (0f5c5c84-5b20-4a0e-aeaa-ee86b8e57c1b): SELECT `id`, `code`, `unit`, `price`, `per`, `createdAt`, `updatedAt`, `customerId`, `
shapeId` FROM `prod` AS `prod` WHERE `prod`.`id` = 415;
Executing (0f5c5c84-5b20-4a0e-aeaa-ee86b8e57c1b): SELECT `id`, `name`, `createdAt`, `updatedAt` FROM `factory` AS `factory` WHERE `facto
ry`.`id` = 1;
Executing (0f5c5c84-5b20-4a0e-aeaa-ee86b8e57c1b): SELECT `id`, `total_order`, `total_ship`, `last_order`, `createdAt`, `updatedAt`, `fac
toryId`, `prodId` FROM `bill` AS `bill` WHERE `bill`.`prodId` = 415 AND `bill`.`factoryId` = 1 LIMIT 1;
2
Executing (0f5c5c84-5b20-4a0e-aeaa-ee86b8e57c1b): COMMIT;
2
Executing (d45a612d-2b75-49a7-8a8e-f63904119cab): START TRANSACTION;
Executing (d45a612d-2b75-49a7-8a8e-f63904119cab): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (d45a612d-2b75-49a7-8a8e-f63904119cab): SET autocommit = 1;
Executing (d45a612d-2b75-49a7-8a8e-f63904119cab): SELECT `id`, `code`, `unit`, `price`, `per`, `createdAt`, `updatedAt`, `customerId`, `
shapeId` FROM `prod` AS `prod` WHERE `prod`.`id` = 520;
Executing (d45a612d-2b75-49a7-8a8e-f63904119cab): SELECT `id`, `name`, `createdAt`, `updatedAt` FROM `factory` AS `factory` WHERE `facto
ry`.`id` = 2;
Executing (d45a612d-2b75-49a7-8a8e-f63904119cab): SELECT `id`, `total_order`, `total_ship`, `last_order`, `createdAt`, `updatedAt`, `fac
toryId`, `prodId` FROM `bill` AS `bill` WHERE `bill`.`prodId` = 520 AND `bill`.`factoryId` = 2 LIMIT 1;
3
Executing (d45a612d-2b75-49a7-8a8e-f63904119cab): COMMIT;
4
ok
```

### PR DESCRIPTION
**Pull request by hendrul**
Fix #5943

### CODE REVIEW

File: lib/promise.js [hunk 1]
```diff
@@ -25,21 +25,23 @@ function shimCLS(object, functionName, fnArgs){
...
-shimCLS(Promise, 'map', [1]);
-shimCLS(Promise, 'reduce', [1]);
-shimCLS(Promise, 'filter', [1]);
-shimCLS(Promise, 'each', [1]);
-shimCLS(Promise.prototype, 'map', [0]);
-shimCLS(Promise.prototype, 'reduce', [0]);
-shimCLS(Promise.prototype, 'filter', [0]);
-shimCLS(Promise.prototype, 'each', [0]);
+shimCLS(Promise, 'map',       [1]);
+shimCLS(Promise, 'mapSeries', [1]);
```
Comment (sushantdhiman) [inline lib/promise.js]: Only add the `mapSeries` changes, remove all the spaces you have added in other methods and shims.

**Comment by sushantdhiman** [comment]
You also need to add the some tests [here](https://github.com/sequelize/sequelize/blob/master/test/integration/cls.test.js)

**Comment by broofa** [comment]
Can we get this backported to `latest` (v3.30.2)?

This is one of those bugs that not a lot of people are going to encounter, but when they do it burns a shit-ton of time.  (I lost over a day trying to figure out what was going on because of the complexity of the code I was wrapping the transaction around).
