### PR TITLE
fix: use lodash _baseIsNative directly instead of _.isNative (#12358)

### LINKED ISSUE #12358: Unable to use 6.0.0-beta.6 with core-js
## Issue Description

I'm using Webpack with core-js polyfill in my Node.js project relying on Sequelize library. I decided to make an earlier migration from Sequelize 5 to Sequelize 6 but was unable to make it working to due this error:

```
/home/ezze/Development/geobase/node_modules/lodash/lodash.js:11927
        throw new Error(CORE_ERROR_TEXT);
        ^

Error: Unsupported core-js use. Try https://npms.io/search?q=ponyfill.
    at Function.isNative (/home/ezze/Development/geobase/node_modules/lodash/lodash.js:11927:15)
    at _.mergeWith (/home/ezze/Development/geobase/node_modules/sequelize/lib/utils.js:54:42)
    at baseMergeDeep (/home/ezze/Development/geobase/node_modules/lodash/lodash.js:3643:11)
    at /home/ezze/Development/geobase/node_modules/lodash/lodash.js:3603:11
    at /home/ezze/Development/geobase/node_modules/lodash/lodash.js:4905:15
    at baseMerge (/home/ezze/Development/geobase/node_modules/lodash/lodash.js:3600:7)
    at baseMergeDeep (/home/ezze/Development/geobase/node_modules/lodash/lodash.js:3689:9)
    at /home/ezze/Development/geobase/node_modules/lodash/lodash.js:3603:11
    at /home/ezze/Development/geobase/node_modules/lodash/lodash.js:4905:15
    at baseMerge (/home/ezze/Development/geobase/node_modules/lodash/lodash.js:3600:7)
    at baseMergeDeep (/home/ezze/Development/geobase/node_modules/lodash/lodash.js:3689:9)
    at /home/ezze/Development/geobase/node_modules/lodash/lodash.js:3603:11
    at /home/ezze/Development/geobase/node_modules/lodash/lodash.js:4905:15
    at baseMerge (/home/ezze/Development/geobase/node_modules/lodash/lodash.js:3600:7)
    at baseMergeDeep (/home/ezze/Development/geobase/node_modules/lodash/lodash.js:3689:9)
    at /home/ezze/Development/geobase/node_modules/lodash/lodash.js:3603:11
```

### What are you doing?

Upgrading Sequelize 5 => 6. I narrowed down the problem and [created a repo](https://github.com/ezze/sequelize-core-js-issue) to reproduce it. The issue is caused by `_.isNative()` function that is incompatible with `core-js` and is used by `mergeDefaults` utility function of Sequelize.

> This method can't reliably detect native functions in the presence of the core-js package because core-js circumvents this kind of detection. Despite multiple requests, the core-js maintainer has made it clear: any attempt to fix the detection will be obstructed. As a result, we're left with little choice but to throw an error. Unfortunately, this also affects packages, like babel-polyfill, which rely on core-js.

### What do you expect to happen?

The code working in Sequelize 5 to work in Sequelize 6.

### What is actually happening?

An error

> Error: Unsupported core-js use. Try https://npms.io/search?q=ponyfill.

is thrown.

### Environment

- Sequelize version: 6.0.0-beta.6
- Node.js version: 10.21.0
- Operating System: Ubuntu 18.04 LTS

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

### PR DESCRIPTION
**Pull request by tpodom**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Closes #12358

Lodash throws an error when calling _.isNative if core-js has been loaded because some of its shims can interfere with lodash's ability to accurate determine if a particular function is a native function or not.  Using the _baseIsNative module directly bypasses the core-js check in lodash without requiring a custom implementation if the native function detection.

I didn't add any new unit test to validate that an error isn't thrown when core-js shims are loaded because I wasn't sure if you wanted an extra dev dependency for that.  I also wasn't sure since Mocha doesn't isolate each test file to a separate process if you wanted the core-js loaded for all tests since that could in theory mask some other problem when core-js is not present.

### CODE REVIEW

File: src/utils.js [hunk 1]
```diff
@@ -1,6 +1,9 @@
 const DataTypes = require('./data-types');
 const SqlString = require('./sql-string');
 const _ = require('lodash');
+// _.isNative includes a check for core-js and throws an error if present.
```
Comment (sushantdhiman) [inline src/utils.js:4]: Move this comment to where baseIsNative is used

**Comment by tpodom** [comment]
I moved the comment down. I just noticed in the readme it says to target bug fixes to master first, do you want me to re-point this PR?

**Comment by sushantdhiman** [comment]
> I moved the comment down. I just noticed in the readme it says to target bug fixes to master first, do you want me to re-point this PR?

Thanks, this PR is already pointed to `master` it seems. Please open a new PR for v6 so it can be released
