### PR TITLE
Fix issue where upsert fails for database function values

### LINKED ISSUE #3406: Upsert incorrectly replacing sequelize.fn
Upsert combined with Sequelize.fn('NOW'); does not seem to be correctly transformed to PostgreSQL.

The actual Command:
```
Model.upsert({
            key1: 'foo',
            key2: 'bar',
            value1: 'baz'
            receivedAt: sequelize.fn('NOW')
          })
```

Insert is as expected - note the receivedAt = NOW()
```
INSERT INTO "Model"
("key1","key2","value1","receivedAt","createdAt","updatedAt") 
VALUES
('foo','bar','baz',NOW(),'2015-03-25 13:31:53.138 +00:00','2015-03-25 13:31:53.138 +00:00');
```

Upsert is as expected - note the receivedAt is broken and createdAt is missing/deformed.
```
UPDATE "Model" 
SET 
"key1"='foo',
"key2"='bar',
"value1"='baz',
"receivedAt"=`fn` = 'NOW', `args` = ,
"updatedAt"='2015-03-25 13:31:53.138 +00:00' 
WHERE (("key1" = 'foo' AND "key2" = 'bar'));
```

### PR DESCRIPTION
**Pull request by FredKSchott**
Fixes #3406 + adds tests
/cc @janmeier

### CODE REVIEW

**Comment by janmeier** [comment]
Looks good, but you'll have to limit the tests to PG only, since other dialects don't support functions as default values

**Comment by FredKSchott** [comment]
Ah good catch, should be all fixed now / looks like tests are passing

File: lib/utils.js [hunk 1]
```diff
@@ -97,6 +97,8 @@ var Utils = module.exports = {
     return lodash.cloneDeep(obj, function (elem) {
       // Unfortunately, lodash.cloneDeep doesn't preserve Buffer.isBuffer, which we have to rely on for binary data
       if (Buffer.isBuffer(elem)) { return elem; }
+      // Preserve data-types like `fn` across clones
+      if (elem instanceof Utils.fn) { return new Utils.fn(elem.fn, elem.args); }
```
Comment (mickhansen) [inline lib/utils.js]: You should be able to simply `return elem`

Comment (mickhansen) [inline lib/utils.js]: Or nevermind, i suppose that might still need to be cloned?

Comment (janmeier) [inline lib/utils.js]: Don't think we need to clone no

Comment (FredKSchott) [inline lib/utils.js]: Since this is a general-purpose deepClone method I would probably expect all properties to be cloned &  that any changes made to one object wouldn't be reflected on its clone.

**Comment by FredKSchott** [comment]
Since this is happening whenever a database function is used, and not just on default values, I moved the test out of the postgres-specific dialect folder and back into the general `upsert.test.js` file

File: lib/utils.js (hunk 1 above)
Comment (mickhansen) [inline lib/utils.js]: We only need to clone if the internal state can somehow be mutated later on. I don't believe this is the case for `fn`.
In any case, if we do go this route, it would be better to add a clone method() to the `fn` prototype and call that from here.

Comment (FredKSchott) [inline lib/utils.js]: Which way do you guys want me to take this? Happy to do either, just want to get it out so that we can start using upsert.

Comment (mickhansen) [inline lib/utils.js]: A `clone` method would be super, deep clone can then look for the presence of that on elem (generally) and call it if need be.

Comment (FredKSchott) [inline lib/utils.js]: :+1: I really like that solution, much more flexible

**Comment by FredKSchott** [comment]
@mickhansen @janmeier comments addressed

File: lib/utils.js [hunk 2]
```diff
@@ -421,4 +423,8 @@ Utils.fn.prototype._isSequelizeMethod =
 Utils.col.prototype._isSequelizeMethod =
 Utils.json.prototype._isSequelizeMethod = true;
 
+Utils.fn.prototype.clone = function() {
+  return new Utils.fn(this.fn, this.args);
+}
```
Comment (janmeier) [inline lib/utils.js]: missing semicolon

Comment (FredKSchott) [inline lib/utils.js]: doh, good catch. fixed!
