### PR TITLE
Fix tedious connect deprecation

### LINKED ISSUE #12181: tedious 8.3.0 deprecation
## Issue Description

`tedious` will require calling `.connect()` on the connection in v9 it currently reports a deprecation in v8.3.0

### What are you doing?

using `tedious` v8.3.0 to connect to MS SQL Server

### What do you expect to happen?

No deprecation notice

### What is actually happening?

tedious is showing deprecation notice:

```
In the next major version of `tedious`, creating a new `Connection`
instance will no longer establish a connection to the server automatically. Please use
the new `connect` helper function or call the `.connect` method on the newly created
`Connection` object to silence this message.
```

### Additional context

The `tedious` PR with this deprecation: https://github.com/tediousjs/tedious/pull/1069

### Environment

- Sequelize version: 5.21.7
- Node.js version: 12.6.1
- Operating System: Windows 10

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): MSSQL
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

### PR DESCRIPTION
**Pull request by UziTech**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Call `connect` after creating `tedious` connection if required.

Fixes #12181

### CODE REVIEW

**Comment by UziTech** [comment]
I'm not sure how to test this since it would require installing different versions of tedious.

**Comment by RodrigoHamuy** [comment]
Thanks for this fix. When can we expect it to be on v5? Thanks.

**Comment by sushantdhiman** [comment]
If someone opens a PR for v5, it will get auto released on merge

**Comment by UziTech** [comment]
this fix is available in v5.21.10

**Comment by RodrigoHamuy** [comment]
Thanks!

File: lib/dialects/mssql/connection-manager.js [hunk 1]
```diff
@@ -61,6 +61,9 @@ class ConnectionManager extends AbstractConnectionManager {
     try {
       return await new Promise((resolve, reject) => {
         const connection = new this.lib.Connection(connectionConfig);
+        if (connection.state === connection.STATE.INITIALIZED) {
+          connection.connect();
+        }
```
Comment (arthurschreiber) [inline lib/dialects/mssql/connection-manager.js:66]: @UziTech I don't think you should be checking against `state` here. Just calling `.connect` should be just fine. 🤔

Comment (UziTech) [reply lib/dialects/mssql/connection-manager.js:66]: Unless the user is using an old version of tedious where calling connect would throw an error.

Comment (killerfurbel) [reply lib/dialects/mssql/connection-manager.js:66]: But this Code leads to an unhandled exception if used with msnodesqlv8 instead of tedious.

connection.state is undefined as well as connection.STATE, so it will throw a `cannot read property INITIALIZED of undefined` Error.

Could you please check if connection.STATE is defined before accessing INITIALIZED? Checking if `.connect` exists would not be suitable because msnodesqlv8 does not require the `.connect()` call at all, this is done in the Constructor already.

Comment (arthurschreiber) [reply lib/dialects/mssql/connection-manager.js:66]: @killerfurbel This code is not supposed to work with `msnodesqlv8` in the first place. It has a completely different API than `tedious`.

Comment (killerfurbel) [reply lib/dialects/mssql/connection-manager.js:66]: Really? See https://github.com/TimelordUK/node-sqlserver-v8#use-with-sequelize ... and why does sequelize support the `dialectModule` property in the constructor, if tedious is the only choice?
I agree, tedious is built in, therefore it is possibly the first choice for most users. But it is possible to use others and this code breaks it... I don't think it has a completely different API - it has a specific sequelize connector (https://github.com/TimelordUK/node-sqlserver-v8/blob/master/lib/sequelize/connection.js).

Comment (arthurschreiber) [reply lib/dialects/mssql/connection-manager.js:66]: So, the `msnodesqlv8` integration for `sequelize` works by re-implementing the `tedious` API, which to me as the `tedious` maintainer, seems extremely questionable.

Comment (arthurschreiber) [reply lib/dialects/mssql/connection-manager.js:66]: I think the main idea behind `dialectModule` is so you can e.g. use e.g. a forked version of `tedious` or any other connector used by `sequelize`.

The way that `msnodesqlv8` build compatibility for `sequelize` "works", but I'm not sure that is a robust approach. Shouldn't there be a separate dialect for `msnodesqlv8` if that is supposed to be a fully supported option?

Comment (sushantdhiman) [reply lib/dialects/mssql/connection-manager.js:66]: Sequelize is not designed to work with `msnodesqlv8`

Comment (UziTech) [reply lib/dialects/mssql/connection-manager.js:66]: > and this code breaks it... I don't think it has a completely different API

If it wants to keep working with sequelize it could add a `STATE` property.

Comment (killerfurbel) [reply lib/dialects/mssql/connection-manager.js:66]: I created an issue in the msnodesqlv8 repo: https://github.com/TimelordUK/node-sqlserver-v8/issues/159

However, since you also backported this behavior also to v5, I would strongly vote for a check within sequelize or revert the commit in the v5 branch. I think "removing" a depreciation warning by implementing a breaking change is not reasonable and should only happen in a major release (--> 6.x).

Comment (UziTech) [reply lib/dialects/mssql/connection-manager.js:66]: You could create a PR to check for `STATE`. That would probably be the best chance of getting it changed.
