### PR TITLE
fix: remove undefined options in sequelize.define

### LINKED ISSUE #15816: Model definition not respecting default schema in the presence of undefined schema passed in
## Issue Creation Checklist

- [x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

Model definition seems to discard default schema name as passed into the sequelize constructor. Maybe the api has changed for this, but the [annotations](https://github.com/sequelize/sequelize/blob/4294cea0fe28543364fc2796b05285b3fa301a8e/packages/core/src/sequelize.js#L169) seem to indicate the current behavior is incorrect.

### Reproducible Example

```js
// const { Sequelize } = require("sequelize");
const { Sequelize } = require("@sequelize/core");

const sequelize = new Sequelize({
  dialect: "postgres",
  database: "main",
  username: "postgres",
  password: "postgres",
  port: 5433,
  define: {
    schema: "myFavSchema",
  },
});

const Thing = sequelize.define("Thing", {}, { schema: undefined });

// console.log(Thing._schema); // myFavSchema
console.log(Thing.modelDefinition?.options.schema); // undefined

```

Here is the link to the SSCCE for this issue:

https://github.com/jfo/sequelize-repro/blob/main/default-schema.js

### What do you expect to happen?

For the default schema to be respected on model definition if undefined has been passed in.

### What is actually happening?

The schema is `undefined` when `undefined` has been passed in.

### Environment

- Sequelize version: 7.0.0-alpha.23
- Node.js version: v18.13.0
- Database & Version: Postgres 14.1
- Connector library & Version: pg 8.10.0

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

### PR DESCRIPTION
**Pull request by WikiRik**
## Pull Request Checklist

- [X] Have you added new tests to prevent regressions?
- [X] If a documentation update is necessary, have you opened a PR to [the documentation repository](https://github.com/sequelize/website/)? 
- [X] Did you update the typescript typings accordingly (if applicable)?
- [X] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [X] Does the name of your PR follow [our conventions](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#6-commit-your-modifications)?

## Description Of Change

This fixes #15816 but I'm open for suggestions if this is the proper approach. It also migrates `test/unit/model/define` to TS

### CODE REVIEW

File: packages/core/src/model-definition.ts [hunk 1]
```diff
@@ -226,13 +228,13 @@ If you need regular getters & setters, define your model as a class and add gett
 See https://sequelize.org/docs/v6/core-concepts/getters-setters-virtuals/#deprecated-in-sequelize-v7-gettermethods-and-settermethods for more information.`);
     }
 
-    this.options.name.plural ??= pluralize(modelOptions.modelName);
+    this.options.name.plural ??= pluralize(definedModelOptions.modelName!);
```
Comment (ephys) [inline packages/core/src/model-definition.ts:231]: I propose to use this.options instead of definedModelOptions

File: packages/core/src/model-definition.ts [hunk 2]
```diff
@@ -213,7 +215,7 @@ export class ModelDefinition {
         },
         globalOptions.define as ModelOptions,
       ),
-      modelOptions,
+      definedModelOptions,
```
Comment (ephys) [inline packages/core/src/model-definition.ts:218]: And with the previous change, you could eliminate the extra variable by removing undefined here

**Review by ephys — CHANGES_REQUESTED** [review]

**Review by ephys — APPROVED** [review]
