### PR TITLE
fix: do not replace `:replacements` inside of strings

### LINKED ISSUE #13817: Replacements break with unrelated user provided data
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)
https://github.com/HandleCollections/sequelize-sscce
## Bug Description

When using replacements with user provided data we get errors when users input the colon symbol.

This happens because the user string is injected into the sql which later is parsed by sql-string.js file's `formatNamedParameters` function.

The `formatNamedParameters` does not have a way to know where the colon symbols comes from.

### SSCCE

**Here is the link to the SSCCE for this issue:** 
https://github.com/HandleCollections/sequelize-sscce

```js
  // lib/sql-string.js formatNamedParameters gets the sql with `WHERE name = "some:foo"`
  // it will try to replace the ":foo", even tho it is not supposed to get replaced
  const query = {
    where: {
      name: 'some:foo', // this is a user provided string I expect to be sanitized
    },
    replacements: {
      test: 'this is used somewhere', // not used in example for the sake of simplicity
    },
  };
```

### What do you expect to happen?

I want to be able to search for strings containing a colon symbol and use replacements at the same time.

I also expect user provided data to be sanitized and never be treated as anything other than text. 

### What is actually happening?

sequelize tries to parse user provided data and throws an error.

I think it might be an avenue for sql injection since sequelize is treating an user provided string as parseable text.

```
Error: Named parameter ":foo" has no value in the given object.
    at /Users/pedro/projects/sequelize-sscce/node_modules/sequelize/dist/lib/sql-string.js:103:11
```

### Environment

- Sequelize version: 6.12.2 and 4.4.4 
- Node.js version: v14.16.0 

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.

### Would you be willing to resolve this issue by submitting a Pull Request?

It seems to be a very difficult problem to solve correctly, meaning only replacing actual replacements, not just as string with a colon.

I also thought about an ignore replacement error, where it would not replace a string that doesn't match a replacement, but this would still allow for a soft "injection" if the user matched a existing replacement.

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

### PR DESCRIPTION
**Pull request by ephys**
### Pull Request Checklist

- [x] Have you added new tests to prevent regressions?
- [x] Does `yarn test` or `yarn test-DIALECT` pass with this change (including linting)?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)?

### Description Of Change

This PR backports the non-breaking changes from https://github.com/sequelize/sequelize/pull/14447 in v6

Only replacements have been backported, as unfortunately an escape hack was put in place to handle the bind parameter scenario, and reverting it would be a breaking change.

Closes #13817

### CODE REVIEW

**Review by fzn0x — APPROVED** [review]
We are good to go

**Review by WikiRik — APPROVED** [review]
Looks like nothing weird got backported

**Comment by ephys** [comment]
I just hope this doesn't introduce a breaking change, but in theory it will only be a breaking change if the feature was used 'incorrectly' (used a replacement in a place where a replacement should not be treated as one, like inside of a string).

**Comment by ephys** [comment]
I will skip the mysql 8 tests: It would seem we are experiencing the same issue as we did with mariadb https://github.com/sequelize/sequelize/issues/14174

**Comment by WikiRik** [comment]
This is the cause of #14509 
Not sure why `Generate docs` check passes while there is clearly a SyntaxError for it. @ephys would you be able to check it out?

File: src/utils.js [hunk 1]
```diff
@@ -114,13 +114,26 @@ function pluralize(str) {
 }
 exports.pluralize = pluralize;
 
+/**
+ * @deprecated use {@link injectReplacements} instead. This method has been removed in v7.
+ *
+ * @param {[string, ...unknown[]]} arr - first item is the SQL, following items are the positional replacements.
```
Comment (WikiRik) [inline src/utils.js:120]: @ephys I assume the issue is with this line
```
SyntaxError: Invalid regular expression: /[~][string, ..$/: Unterminated character class
```

Comment (ephys) [reply src/utils.js:120]: That's most likely it, and the docs check did not catch it

Comment (ephys) [reply src/utils.js:120]: PR ready https://github.com/sequelize/sequelize/pull/14513

**Comment by evangow** [comment]
This just broke my deployment, so it's a breaking change for me at the very least.

"in theory it will only be a breaking change if the feature was used 'incorrectly' (used a replacement in a place where a replacement should not be treated as one, like inside of a string)"

Not sure what you mean by replacements being used incorrectly inside a string.

The docs do this:

```
await sequelize.query(
  'SELECT * FROM projects WHERE status = :status',
  {
    replacements: { status: 'active' },
    type: QueryTypes.SELECT
  }
);
```
https://sequelize.org/docs/v6/core-concepts/raw-queries/

**Comment by peterbaricic** [comment]
Please, if you break things in a minor release update then please provide an example how to use replacements with raw queries. Why is it incorrect usage?

**Comment by ephys** [comment]
By 'using a replacement inside a string' i meant a sql string, something like this;

```js
await sequelize.query(
  `SELECT * FROM projects WHERE status = ':status'`,
  {
    replacements: { status: 'active' },
    type: QueryTypes.SELECT
  }
);
```

Note the quotes around `:status`. Injecting a replacement there would have resulted in sql injection. That's the thing we changed.

Your usage is correct and should not have broken. We'll look into what happened there.

**Comment by peterbaricic** [comment]
this is my usage, I use it to call sql functions, I don't have any strings there

```ts
const res: bulkItem[] = await database.query(`SELECT "portfolioInvestmentId", value FROM ${metric}(:fundId, array[:pciIds]::uuid[], :untilDate, :excludeEventId)`, {
      type: QueryTypes.SELECT,
      replacements: {
        fundId,
        pciIds,
        untilDate: dateToStr(untilDate),
        excludeEventId,
      },
```

**Comment by ephys** [comment]
This results in 

```sql
SELECT "portfolioInvestmentId", value FROM table('abc', array[:pciIds]::uuid[], 'ijk', 'lmn')
```

Looks like the culprit is `array[:pciIds]::uuid[]`. Technically it's not a valid spot for a SQL value, but v6 doesn't have a way to specify the type of a replacement and this is breaking a legitimate workaround to that so we'll fix the parser in v6 to allow it.

**Comment by ephys** [comment]
PR: https://github.com/sequelize/sequelize/pull/14518

**Comment by evangow** [comment]
I had 2 cases where using replacements broke. The first was with using it with LIMIT doing something like the below

```javascript
await sequelize.query(
  'SELECT * FROM projects WHERE status = :status LIMIT :first',
  {
    replacements: { status: 'active', first: 20 },
    type: QueryTypes.SELECT
  }
);
```

The 2nd case was with using it with an array as well, such as `WHERE "tags" @> ARRAY[:tags]::TEXT[]`. Seems like the PR you submitted should fix this 2nd case but not the first

**Comment by ephys** [comment]
I just ran it against our latest v6 and it resulted in `SELECT * FROM projects WHERE status = 'active' LIMIT 20`

There may be something more going on. If you'd rather avoid posting the real query in public, you can send it to me privately on our [slack](http://sequelize-slack.herokuapp.com/) (if you're comfortable with that), and I'll look into it.

**Comment by nabilzhafri** [comment]
@ephys i see, if thats the concern that make sense to patch such thing. In my case, it's all constructed internally, so it wasn't really a problem.

And thanks for the solution! That'll work.
In my case I have to go with second solution because my queries are all in .sql files

**Comment by Caerbannog** [comment]
Here are two more cases where the replacement is not detected, with PostgreSQL.

1. JSONB indexing
```sql
select ('{"abc": 1}'::jsonb)->>:key;
```

2. Inside a `do` block. I assume that `$$` triggers the "inside of strings" limitation.
```sql
do $$
  begin
    if :value then
     refresh materialized view abc;
   end if;
  end
$$;
select 1;
```

We worked around these cases by concatenating strings, and taking care of sanitization ourselves.

**Comment by WikiRik** [comment]
@ephys I'm clearing up my notifications and trying to ping you in some of those so they're back on your radar

File: src/sql-string.d.ts [hunk 2]
```diff
@@ -1,5 +1,5 @@
 export type Escapable = undefined | null | boolean | number | string | Date;
 export function escapeId(val: string, forbidQualified?: boolean): string;
-export function escape(val: Escapable | Escapable[], timeZone?: string, dialect?: string, format?: string): string;
+export function escape(val: Escapable | Escapable[], timeZone?: string, dialect?: string, format?: boolean): string;
 export function format(sql: string, values: unknown[], timeZone?: string, dialect?: string): string;
 export function formatNamedParameters(sql: string, values: unknown[], timeZone?: string, dialect?: string): string;
```
Comment (benasher44) [inline src/sql-string.d.ts:5]: It looks like this wasn't updated, so existing TS users won't see the new injectReplacements function, nor will they see the deprecation.

**Comment by ephys** [comment]
I haven't been able to resolve the `DO` and `EXECUTE` use cases.

The problem is that I cannot guarantee that the code injected inside of the string is safe. It requires a much more complex escape function.

In your example, if I set `value` to `'$$'`, the result will be

```sql
do $$
  begin
    if '$$' then
      refresh materialized view abc;
    end if;
  end
$$;
```

Which is a syntax error because postgres considers `$$` to be the end of the string passed to the do block

This limitation wasn't introduced by this PR, so that code was vulnerable before this PR, but I can't enable it until we've figured out a way to safely escape the value that needs to be injected inside of the string.

**Comment by vivekkairi** [comment]
Hi @ephys 

Screenshot 2022-09-26 at 6 34 18 PM

With earlier sequelize versions, passing `undefined` as positional parameter was consider as `null` but now an error is been thrown resulting in a breaking change.

File: src/utils/sql.ts [hunk 3]
```diff
@@ -0,0 +1,221 @@
...
+      const previousChar = sqlString[i - 1];
+      // we want to be conservative with what we consider to be a replacement to avoid risk of conflict with potential operators
+      // users need to add a space before the bind parameter (except after '(', ',', and '=')
+      if (previousChar !== undefined && !/[\s(,=]/.test(previousChar)) {
+        continue;
+      }
+
+      const remainingString = sqlString.slice(i, sqlString.length);
+
+      const match = remainingString.match(/^:(?<name>[a-z_][0-9a-z_]*)(?:\)|,|$|\s|::)/i);
```
Comment (hbrysiewicz) [inline src/utils/sql.ts:144]: This regex does not take into account an ending `;` on the statement, so I corrected locally to `remainingString.match(/^:(?<name>[a-z_][0-9a-z_]*)(?:\)|,|\;|$|\s|::)/i);` and then also discovered it does not like when the sql statement has JSON in it such as: `UPDATE table SET value = value || '{"column::form": :formTemplateId}' where key = 'formTemplates.defaultForms'` (with replacements for `:formTemplateId` passed in)

Comment (ephys) [reply src/utils/sql.ts:144]: That's not a bug, your `:formTemplateId` is inside of a SQL string so we won't replace it because that will lead to sql injection as well as the risk of mangling data

The `;` thing may be a bug, I'd need an example of a failing query to make sure

**Comment by denodaeus** [comment]
> Hi @ephys
> 
> Screenshot 2022-09-26 at 6 34 18 PM
> 
> With earlier sequelize versions, passing `undefined` as positional parameter was consider as `null` but now an error is been thrown resulting in a breaking change.

This is also how it broke us.  It is often not uncommon in javascript to pass undefined in as positional arguments.  It's worse that this slipped in as not a major breaking change - this is a pretty major, breaking API change.
