### PR TITLE
fix(increment): broken queries

### LINKED ISSUE #9572: increment function generates strange sql
I am trying to increment a field:
`
user.increment({ lastCheckingEmailSendingNumber: 1 });
`
The increment operation does not work. And I get this error:
error.message: "column "0" of relation "User" does not exist"
error.sql: "UPDATE "User" SET "lastCheckingEmailSendingNumber"="lastCheckingEmailSendingNumber"+ 1,"0"='id',"1"='email',"2"='firstName',"3"='lastName',"4"='phoneNumber',"5"='birthdate',"6"='nationalId' WHERE "id" = 1 RETURNING *"

I don't understand where this part `"0"='id',"1"='email',"2"='firstName',"3"='lastName',"4"='phoneNumber',"5"='birthdate',"6"='nationalId'`
comes from, even though emai, firstName, ... are columns in User Table !?

I am using sequelize-typescript version 0.6.5

__Dialect:__ postgres
__Dialect version:__ pg 6.4.2
__Database version:__ 9.6
__Sequelize version:__ 5.0.0-beta.8
__Tested with latest release:__ yes, 5.0.0-beta.8

### LINKED ISSUE #10411: Trying to increment value with Model Class generates wrong SQL
[Looking at the increment method example in the documentations](http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-increment) it doesn't look like the increment have to run on an instance (because you can add where props on option).

 Currently I am trying to run increment on the model class itself (see example). 

## What are you doing?

Trying to increment a field using Model.

```js

hooks: {
      beforeCreate: hit => {
        sequelize.models.Link.increment({
          hitCount: 1
        }, {
          silent: true,
          where: {
            id: hit.linkId
          }
        })
      },
    }

```

## What do you expect to happen?
Increase the field by one

## What is actually happening?
SQL Error: Unknown column '0' in 'field list'.

The query is almost correct but sequelize adds model fields into the query.

```
UPDATE `links` SET `hitCount`=`hitCount`+ 1,`0`='id',`1`='name',`2`='originalUrl',`3`='code',`4`='type',`5`='userId',`6`='opengraph',`7`='shortUrl',`8`='createdAt',`9`='updatedAt' WHERE `id` = 40
```

__Dialect:__ mysql
__Dialect version:__ 1.6.4
__Database version:__ MySQL 5.7.25-0ubuntu0.18.04.2 - (Ubuntu) 
__Sequelize version:__ 4.42.0
__Tested with latest release:__ YES (4.42.0)

**Similar:** #9572

### LINKED ISSUE #10719: increment shows sql error after use scope query
## What are you doing?
I just want increment field of  a model instance after scope query.
see codes below:

```js
Movie.scope('bh').findOne({where:{id:1}}).then(movie=>{
movie.increment('fav_nums',{by:1})
})
```

bh is name of a scope，defined by code below：
```js
  scopes: {
            bh: {
                attributes: { exclude: ['created_at', 'updated_at','deleted_at'] }
            }
        }
```

## What do you expect to happen?
when query ，i need this scope to exclude some attributes，after query，i just want increment a field of model instance 。but see the sql below，wrong sql generated。

## What is actually happening?
very simple code ,but will cause sql errors。because the code above will be translated into sqls like this:

```sql
UPDATE movie SET fav_nums=fav_nums+ 1,exclude='created_at', 'updated_at', 'deleted_at',updated_at='2019-01-21 15:59:18' WHERE id = 1
```

Obviously，the sql is wrong。

__Dialect:__ mysql
__Dialect version: 
__Database version:5.6
__Sequelize version: 5.2.12
__Tested with latest release:yes，5.2.12

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

### PR DESCRIPTION
**Pull request by papb**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [X] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [X] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [X] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [ ] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Fixes #10719
Fixes #10411
Fixes #9572

[Inspired](https://github.com/sequelize/sequelize/pull/11676#issuecomment-576415470) by #11676, thanks @mhio and @ALiangLiang.

### CODE REVIEW

File: lib/dialects/abstract/query-generator.js [hunk 1]
```diff
@@ -407,20 +407,21 @@ class QueryGenerator {
...
-   * @param {Object} where         A hash with conditions (e.g. {name: 'foo'}) OR an ID as integer
+   * @param {string} operator                    String with the arithmetic operator (e.g. '+' or '-')
+   * @param {string} tableName                   Name of the table
+   * @param {Object} where                       A plain-object with conditions (e.g. {name: 'foo'}) OR an ID as integer
+   * @param {Object} incrementAmountsByField     A plain-object with attribute-value-pairs
+   * @param {Object} extraAttributesToBeUpdated  A plain-object with attribute-value-pairs
    * @param {Object} options
-   * @param {Object} attributes
+   * 
+   * @private
```
Comment (papb) [inline lib/dialects/abstract/query-generator.js]: Note: here I am simply making explicit the fact that this method is private (since the whole namespace is already `@private`)

**Comment by sushantdhiman** [comment]
:100:
