### PR TITLE
Fix empty not null validation message

### LINKED ISSUE #7890: empty validation message for notNull Violation
## What you are doing?
I migrated to sequelize v4 from v3. I have some model, part of definition with property and validation:

**v3**:
```js
    const application = sequelize.define('Application', {
// ......
        sso_url: {
            type: DataTypes.STRING(2083),
            allowNull: false, // cant be null
            validate: { // other validation, it doesn't matter
                isUrl: {
                    msg: 'SSO URL must be a valid url.'
                }
            }
        },
    }
// ......
    );
```
**v4**:
```js
    class Application extends sequelize.Model { /* ... */ }

    Application.init({
// ......
        sso_url: {
            type: DataTypes.STRING(2083),
            allowNull: false,
            validate: {
                isUrl: {
                    msg: 'SSO URL must be a valid url.'
                },
            }
        },
// ......
    }, {
        sequelize,
// ......
    });
```

And I have some API endpoint for application creation.
I covered this part by tests before updating to v4. The test check validation message when I don't pass *sso_url* field for creation.

I dumped validation error object to console.

## What do you expect to happen?
_To see validation error object with old fields (messages) and values, because there is no changes in [upgrade to v4 guide](http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html)._ And it is **breaking changes**.

## What is actually happening?
_Error object has incorrect message field._

_Output_

v3:
```js
{ SequelizeValidationError: notNull Violation: sso_url cannot be null // <- this explain the error
    at /home/stripped/node_modules/sequelize/lib/instance-validator.js:74:14
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/home/stripped/node_modules/bluebird/js/release/util.js:16:23)
// ....
    at Immediate.Async.drainQueues (/home/stripped/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
  name: 'SequelizeValidationError',
  message: 'notNull Violation: sso_url cannot be null',
  errors: 
   [ { message: 'sso_url cannot be null', // <- this field is not empty!
       type: 'notNull Violation',
       path: 'sso_url',
       value: null } ] }
```

v4:
```js
{ SequelizeValidationError: Validation Error // <- not the same
    at Promise.all.then (/home/stripped/node_modules/sequelize/lib/instance-validator.js:77:15)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/home/stripped/node_modules/bluebird/js/release/util.js:16:23)
// .......
    at Immediate.Async.drainQueues (/home/stripped/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
  name: 'SequelizeValidationError',
  errors: 
   [ ValidationErrorItem {
       message: '', // <- not the same **EMPTY**
       type: 'notNull Violation',
       path: 'sso_url',
       value: null } ] }
```

__Dialect:__ mysql
__Database version:__ 5.6.33-0ubuntu0.14.04.1
__Sequelize version:__ 3.30.4 -> **4.2.1**

### PR DESCRIPTION
**Pull request by tomfun**
close #7890 

### Pull Request check-list

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you follow the commit message conventions explained in CONTRIBUTING.md?

### Description of change

In previous versions was default validation message, and was way to customize this message. Now it can't be used:
 - [customization message][https://github.com/sequelize/sequelize/blob/master/lib/utils/validator-extras.js#L81]
 - default message is empty, when there is no *notNull* with *msg* (see this PR)

I remove dead code, it gives a only default not null validation message. There is alternative way: do revert [customization message deprecation](https://github.com/sequelize/sequelize/blob/master/lib/utils/validator-extras.js#L81)

### CODE REVIEW

File: lib/instance-validator.js [hunk 1]
```diff
@@ -321,10 +321,7 @@ class InstanceValidator {
     let error;
 
     if (rawAttribute.allowNull === false && (value === null || value === undefined)) {
-      const validators = this.modelInstance.validators[field];
-      const errMsg = validators
-                      ? (validators.notNull || {}).msg
-                      : `${field} cannot be null`;
+      const errMsg = `${field} cannot be null`;
```
Comment (felixfbecker) [inline lib/instance-validator.js]: This now doesn't use `validators.notNull.msg` anymore, whereas it did before. I would suggest
```js
const errMsg = validators && validators.notNull && validators.notNull.msg || `${field} cannot be null`
```

Comment (tomfun) [inline lib/instance-validator.js]: I can fix it, but when you use 'notNull' validation, it fails. because of this (customization message)[https://github.com/sequelize/sequelize/blob/master/lib/utils/validator-extras.js#L81]

So end user can't use it anymore.

Comment (felixfbecker) [inline lib/instance-validator.js]: oh, that makes sense. In that case the way you did it is better. I also cannot think of a way where `${field} cannot be null` doesn't describe the exact problem.

Comment (tomfun) [inline lib/instance-validator.js]: @felixfbecker in my project all entites haven't custom not null validation message.
So what the next, do you approve it?

File: test/integration/instance.validations.test.js [hunk 2]
```diff
@@ -344,6 +344,45 @@ describe(Support.getTestDialectTeaser('InstanceValidator'), () => {
...
+            throw new Error('Validation must be failed');
+          }, () => {
+            // fail is ok
+          });
+      });
+
+      it('correctly throws an error using create method with default generated messages', function() {
+        return this.Project.create({}).catch(err => {
+          expect(err).to.have.ownProperty('name')
+            .and.have.ownProperty('errors');
```
Comment (felixfbecker) [inline test/integration/instance.validations.test.js]: you don't use `and` in the next line, please stay consistent.

File: test/integration/instance.validations.test.js [hunk 3]
```diff
@@ -344,6 +344,45 @@ describe(Support.getTestDialectTeaser('InstanceValidator'), () => {
         });
       });
     });
+    describe('Not null schema validation', () => {
+      beforeEach(function() {
+        const self = this;
```
Comment (felixfbecker) [inline test/integration/instance.validations.test.js]: you don't need self

Comment (tomfun) [inline test/integration/instance.validations.test.js]: done

**Comment by tomfun** [comment]
@mbroadst @sushantdhiman @eseliger would you merge it?

**Comment by tomfun** [comment]
@felixfbecker could you re-run CI.  
Maybe it will be merged soon :pray: ?

**Comment by felixfbecker** [comment]
Pending review

**Comment by tomfun** [comment]
@mbroadst @sushantdhiman so what the next?

**Comment by tomfun** [comment]
Any updates?

**Comment by tomfun** [comment]
Please merge it. Or say what need to be fixed.

**Comment by tomfun** [comment]
Guys, are you enjoying my monologue? :face_with_thermometer:
