### PR TITLE
fix(query-interface): add ability to pass options from createFunction() call

### LINKED ISSUE #8741: queryInterface.createFunction() does not support sequelize.query options
## What are you doing?
```js
queryInterface.createFunction('test', [], 'integer', 'plpgsql', 'RETURN 1;', {logging: console.log})
```

## What do you expect to happen?
Logged SQL:
```
Executing (default): CREATE FUNCTION test()
RETURNS integer AS $func$
BEGIN
        RETURN 1;
END;
$func$ language 'plpgsql';
```

## What is actually happening?
```
sequelize\lib\dialects\postgres\query-generator.js:687
      '' : '\n\t' + options.join('\n\t');
                            ^
TypeError: options.join is not a function
```

__Dialect:__ postgres
__Dialect version:__ pg@6
__Database version:__ 10.0
__Sequelize version:__ 4.24.0
__Tested with latest release:__ Yes

### PR DESCRIPTION
**Pull request by markablov**
Closes #8741

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](../CONTRIBUTING.md)?

### Description of change

queryInterface.createFunction() does not support ability to pass options to sequelize.query().
I extended signature of this function similar to createTrigger() approach - separate extended SQL function description options with options that passed to sequelize.query().

### CODE REVIEW

File: lib/query-interface.js [hunk 1]
```diff
@@ -1122,8 +1122,8 @@ class QueryInterface {
     }
   }
 
-  createFunction(functionName, params, returnType, language, body, options) {
```
Comment (sushantdhiman) [inline lib/query-interface.js]: Since you are using functions, can you add proper comments for this method options and usage, something like https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L157

Comment (markablov) [reply lib/query-interface.js]: done

Comment (sushantdhiman) [reply lib/query-interface.js]: Great :+1:
