### PR TITLE
Fixes #2038, Added missing UNSIGNED / ZEROFILL support for DECIMAL

### LINKED ISSUE #2038: Is unsigned decimal type supported?
I got "Unrecognized data type for field price" exception with this schema definition:

```
var Order = db.define('order', {
    price: Sequelize.DECIMAL.UNSIGNED
});
```

INTEGER.UNSIGNED works as expected.

### PR DESCRIPTION
**Pull request by sushantdhiman**
### Pull Request check-list

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does your issue contain a link to existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Have you added an entry under `Future` in the changelog?

### Description of change

Closes #2038 , `DECIMAL` was missing implementation for `UNSIGNED` and `ZEROFILL`, Added for `MySQL`

### CODE REVIEW

File: lib/data-types.js [hunk 1]
```diff
@@ -345,11 +345,13 @@ inherits(DECIMAL, NUMBER);
 
 DECIMAL.prototype.key = DECIMAL.key = 'DECIMAL';
 DECIMAL.prototype.toSql = function toSql() {
+  let colDefinition = 'DECIMAL';
```
Comment (mickhansen) [inline lib/data-types.js]: This is slightly ugly, how is it handled elsewhere?

Comment (sushantdhiman) [inline lib/data-types.js]: Like this https://github.com/sequelize/sequelize/blob/master/lib/data-types.js#L187

Comment (mickhansen) [inline lib/data-types.js]: Alright, if you rename the varaible to `definition` which is a tad shorter i'm good with this.
Or to result to keep it in line.

Comment (sushantdhiman) [inline lib/data-types.js]: I can remove the variable all together, just return `DECIMAL (12, 2)` from first statement other wise  return `DECIMAL`

Comment (mickhansen) [inline lib/data-types.js]: good with me aswell.

File: lib/dialects/mysql/data-types.js [hunk 2]
```diff
@@ -25,6 +25,26 @@ module.exports = BaseTypes => {
...
+
+    if (this._unsigned) {
+     colDefinition += ' UNSIGNED';
+    }
+
+    if (this._zerofill) {
+     colDefinition += ' ZEROFILL';
+    }
+
+    return colDefinition;
```
Comment (mickhansen) [inline lib/dialects/mysql/data-types.js]: same here, appreciate a variable rename (bikeshedding2000)

Comment (sushantdhiman) [inline lib/dialects/mysql/data-types.js]: no problem, I will rename the variable to `definition` here

**Comment by sushantdhiman** [comment]
Ready for merge @mickhansen
