### PR TITLE
(fix) DATEONLY parsed as Date

### LINKED ISSUE #4858: DATEONLY field is being parsed as a javascript Date with time/zone
I am using postgres.

My dateonly field is being stored as YYYY-MM-DD but when I pull that data down to the client, it is being sent as a full timestamp with time and timezone parts.

### PR DESCRIPTION
**Pull request by sushantdhiman**
### Pull Request check-list
- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does your issue contain a link to existing issue or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Have you added an entry under `Future` in the changelog?
### Description of change

Close #4858

### CODE REVIEW

File: lib/dialects/mysql/data-types.js [hunk 1]
```diff
@@ -62,7 +63,7 @@ module.exports = BaseTypes => {
   };
 
   function DATE(length) {
-    if (!(this instanceof DATE)) return new Date(length);
+    if (!(this instanceof DATE)) return new DATE(length);
```
Comment (janmeier) [inline lib/dialects/mysql/data-types.js]: Good catch ;)

File: lib/model.js [hunk 2]
```diff
@@ -3085,14 +3086,23 @@ class Model {
...
-                originalValue = new Date(originalValue);
-              }
-              if (originalValue && value.getTime() === originalValue.getTime()) {
-                return this;
+              // Dont parse DATEONLY to new Date, keep them as string
+              if (this.rawAttributes[key].type instanceof DataTypes.DATEONLY) {
+                if (originalValue && originalValue === value) {
+                  return this;
+                } else {
+                  value = moment(value).format('YYYY-MM-DD');
```
Comment (mickhansen) [inline lib/model.js]: Should perhaps happen in stringify instead?

Comment (sushantdhiman) [inline lib/model.js]: When we build instance, we need to keep `YYYY-MM-DD` there as well, it prevent build instance to have `Date`. Its a safe guard against case when user are passing `new Date` / `moment` to `DATEONLY`. This is also done in stringify, but stringify is only called when we are putting data from instance to query

File: .eslintrc.json [hunk 3]
```diff
@@ -10,7 +10,7 @@
     "no-var": "error",
     "prefer-const": "error",
     "semi": ["error", "always"],
-    "space-before-function-paren": ["warn", "never"],
+    "space-before-function-paren": "off",
```
Comment (felixfbecker) [inline .eslintrc.json]: Why this? I tried to align this rule with how most of the codebase is written. I know it is inconsistent in the codebase which is why I made it a warning

File: lib/dialects/postgres/data-types.js [hunk 4]
```diff
@@ -24,16 +24,26 @@ module.exports = BaseTypes => {
     array_oids: [3807]
   };
 
-  BaseTypes.DATEONLY.types.postgres = {
-    oids: [1082],
-    array_oids: [1182]
-  };
-
```
Comment (felixfbecker) [inline lib/dialects/postgres/data-types.js]: Why move this around?

File: lib/model.js (hunk 2 above)
Comment (felixfbecker) [inline lib/model.js]: Hm... I don't know, do we have other cases where values passed to `build`/`set` are converted to another data type? Might be unexpected behavior, I would think that these two are equivalent:
```js
const user = new User({birthday: new Date()})
const user = Object.assign(new User(), {birthday: new Date()});

File: test/integration/data-types.test.js [hunk 5]
```diff
@@ -438,4 +438,22 @@ describe(Support.getTestDialectTeaser('DataTypes'), function() {
...
 
+  it('should return YYYY-MM-DD format string for DATEONLY', function () {
+    const Model = this.sequelize.define('user', {
+      stamp: Sequelize.DATEONLY
+    });
+    const testDate = moment().format('YYYY-MM-DD');
+
+    return Model.sync({ force: true})
+      .then(() => Model.create({ stamp: testDate }))
+      .then((record) => {
```
Comment (felixfbecker) [inline test/integration/data-types.test.js]: Unneeded parens

File: lib/dialects/postgres/data-types.js (hunk 4 above)
Comment (sushantdhiman) [inline lib/dialects/postgres/data-types.js]: To keep it with DATEONLY declaration

Comment (felixfbecker) [inline lib/dialects/postgres/data-types.js]: But all other oids are grouped at the top?

Comment (sushantdhiman) [inline lib/dialects/postgres/data-types.js]: No all of them

Comment (felixfbecker) [inline lib/dialects/postgres/data-types.js]: Okay then. Btw imo in the future we shouldn't patch on `BaseTypes`

**Comment by sushantdhiman** [comment]
Can be merged @sequelize/core ?

**Comment by felixfbecker** [comment]
@sushantdhiman 
https://github.com/sequelize/sequelize/pull/6709#discussion_r83595347
https://github.com/sequelize/sequelize/pull/6709#discussion_r83595511

File: lib/model.js (hunk 2 above)
Comment (sushantdhiman) [inline lib/model.js]: ` Object.assign(new User(), {birthday: new Date()});` Syntax wont work actually as we hide data in `dataValues`

Beside we are already converting incoming user data to `Date` instance as well. So I dont think there should be any problem converting it to `YYYY-MM-DD`, because thats what `DATEONLY` field is storing

Comment (felixfbecker) [inline lib/model.js]: If we do it in other places as well it's okay though

**Comment by sushantdhiman** [comment]
Flag is green and I think all comments are properly answers. Please merge if looks good to go @sequelize/core

**Comment by janmeier** [comment]
:+1:
