### PR TITLE
fix(increment): support scopes

### LINKED ISSUE #8537: Model.increment throws `Missing where attribute in the options parameter` error even if used with scope
## What are you doing?

Model.increment requires a `where` option be present, even if it's empty. But it ignores `where` options populated via scopes.

```js
it('should work with scopes', function () {
  const User = this.sequelize.define('User', {
    aNumber: DataTypes.INTEGER,
    name: DataTypes.STRING
  }, {
    scopes: {
      jeff: {
        where: {
          name: 'Jeff'
        }
      }
    }
  });

  return User.sync({force: true}).then(() => {
    return User.bulkCreate([
      {
        aNumber: 1,
        name: 'Jeff'
      },
      {
        aNumber: 3,
        name: 'Not Jeff'
      }
    ]);
  }).then(() => {
    return User.scope('jeff').increment('aNumber');
  }).then(() => {
    return User.scope('jeff').findOne();
  }).then(jeff => {
    expect(jeff.aNumber).to.equal(2);
  }).then(() => {
    return User.findOne({
      where: {
        name: 'Not Jeff'
      }
    });
  }).then(notJeff => {
    expect(notJeff.aNumber).to.equal(3);
  });
});
```

## What do you expect to happen?
`where` from scope should be applied to `increment` operation.

## What is actually happening?
`.increment` throws an Error: `Missing where attribute in the options parameter`.

__Dialect:__ any
__Dialect version:__ any
__Database version:__ any
__Sequelize version:__ master
__Tested with master branch:__ Yes

### LINKED ISSUE #8539: Model.increment ignores scopes
## What are you doing?

Given that [you have to pass `where: {}`](https://github.com/sequelize/sequelize/issues/8537), I'd still expect scopes to work with `Model.increment`:
```js
it('should work with scopes', function () {
  const User = this.sequelize.define('User', {
    aNumber: DataTypes.INTEGER,
    name: DataTypes.STRING
  }, {
    scopes: {
      jeff: {
        where: {
          name: 'Jeff'
        }
      }
    }
  });

  return User.sync({force: true}).then(() => {
    return User.bulkCreate([
      {
        aNumber: 1,
        name: 'Jeff'
      },
      {
        aNumber: 3,
        name: 'Not Jeff'
      }
    ]);
  }).then(() => {
    return User.scope('jeff').increment('aNumber', {
      where: {}
    });
  }).then(() => {
    return User.scope('jeff').findOne();
  }).then(jeff => {
    expect(jeff.aNumber).to.equal(2);
  }).then(() => {
    return User.findOne({
      where: {
        name: 'Not Jeff'
      }
    });
  }).then(notJeff => {
   // this fails since notJeff was incremented too
    expect(notJeff.aNumber).to.equal(3);
  });
});
```

## What do you expect to happen?
Only `Jeff` is incremented.

## What is actually happening?
All users are incremented since scope is ignored.

__Dialect:__ any
__Dialect version:__ any
__Database version:__ any
__Sequelize version:__ master
__Tested with master branch:__ Yes

### PR DESCRIPTION
**Pull request by gabegorelick**
Closes #8539
Closes #8537 

### Pull Request check-list

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in CONTRIBUTING.md?

### Description of change

Make `Model.increment` respect scopes.

### CODE REVIEW

File: lib/model.js [hunk 1]
```diff
@@ -2892,6 +2892,7 @@ class Model {
   * @return {Promise<this>}
   */
   static increment(fields, options) {
+    this._injectScope(options);
```
Comment (gabegorelick) [inline lib/model.js]: Having this before `_optionsMustContainWhere` makes sense to me, but if there's a reason to inject scopes after that assertion, we can move it down.

**Comment by sushantdhiman** [comment]
Tests failing

File: lib/model.js (hunk 1 above)
Comment (janmeier) [reply lib/model.js]: I think it fits fine here
