### PR TITLE
fix(typings): Add getDatabaseName type

### LINKED ISSUE #11431: Property 'getDatabaseName' does not exist on type 'Sequelize'.
## Issue Description

Trying to call `getDatabaseName` using Sequelize with Typescript however the method is not declared in `sequelize.d.ts`

### What are you doing?

```js
import { Sequelize, Model, DataTypes } from 'sequelize';

const sequelize: Sequelize = new Sequelize(
    ...
);
sequelize
  .authenticate()
  .then(() => {
    log.info(`Successfully connected to database '${sequelize.getDatabaseName()}'
  })

```

### What do you expect to happen?

Function already declared

### What is actually happening?

TS Compile error
(other methods like getDialect are declared and work fine)

### Environment

- Sequelize version: `sequelize@5.18.4`
- Node.js version: `v10.15.1`
- Operating System: MacOS 
- TypeScript version: `typescript@3.6.3`
- dialect: postgres
### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- I think I could find the time and means to do this

### PR DESCRIPTION
**Pull request by ibarrae**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Add `getDatabaseName` function type in `Sequelize` class type. Closes #11431

### CODE REVIEW

File: types/lib/sequelize.d.ts [hunk 1]
```diff
@@ -1066,6 +1066,12 @@ export class Sequelize extends Hooks {
    */
   public getDialect(): string;
 
+  /**
+   * Returns the database name.
+   */
+
```
Comment (SimonSchick) [inline types/lib/sequelize.d.ts]: Can you rm the newline here pls?

**Comment by papb** [comment]
Hello! I see you are a first-time contributor, thank you for taking the time to help Sequelize! I hope to see more PRs from you in the future!
