### PR TITLE
fix(tinyint): ignore params for TINYINT on postgres

### LINKED ISSUE #9738: Postgres Migration: ERROR: syntax error at or near "UNSIGNED"
## What are you doing?

Trying to run a  migration against Postgres

```js
'use strict';
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.createTable('Events', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER.UNSIGNED
      },
      type: {
        allowNull: false,
        type: Sequelize.TINYINT.UNSIGNED
      }
    });
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.dropTable('Events');
  }
};

```

## What do you expect to happen?

~Migration to successfully run~ An error about `TINYINT` not being supported.

## What is actually happening?

```
== 20180417181241-create-events: migrating =======
(sequelize) Warning: PostgreSQL does not support INTEGER with options. Plain `INTEGER` will be used instead., '
>> Check:', http://www.postgresql.org/docs/9.4/static/datatype.html

ERROR: syntax error at or near "UNSIGNED"
```
If I remove unsigned I get an error about `TINYINT` not being supported by Postgres (which is expected). 

## Versions

Postgres 10.4
Sequelize CLI [Node: 9.5.0, CLI: 4.0.0, ORM: 4.37.6]

### PR DESCRIPTION
**Pull request by t-bonatti**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Proposal to fix #9738.
Postgres don't have type TINYINT.
With this PR the mesage error is more clear when use `TINYINT.UNSIGNED`. It's same when use `TINYINT`

From:
`ERROR: syntax error at or near "UNSIGNED"`

To:
`type "tinyint" does not exist`

@sushantdhiman what do you think?

### CODE REVIEW

File: lib/dialects/postgres/data-types.js [hunk 1]
```diff
@@ -254,6 +254,27 @@ module.exports = BaseTypes => {
     array_oids: [1185]
   };
 
+  function TINYINT(length) {
+    if (!(this instanceof TINYINT)) return new TINYINT(length);
+    BaseTypes.TINYINT.apply(this, arguments);
+
+    // POSTGRES does not support any parameters for bigint
```
Comment (sushantdhiman) [inline lib/dialects/postgres/data-types.js]: // POSTGRES does not support any parameters for tinyint

**Comment by t-bonatti** [comment]
@sunshinewyin Done!

**Comment by sushantdhiman** [comment]
Thanks @t-bonatti
