### PR TITLE
Fix bulk create not inserting NULL for undefined values. Fixes #3670

### LINKED ISSUE #3670: Model.bulkCreate() inserts NULL for undefined values
on 2.1.3; postgres

```
var Beer = sequelize.define('Beer', {
    style: Sequelize.STRING,
    size: Sequelize.INTEGER,
});

Beer.bulkCreate([{
    style: 'ipa'
}])
.then(function(){
})
```

> ```
Executing (default): INSERT INTO "Beers" ("id","style","size","createdAt","updatedAt") VALUES (DEFAULT,'ipa',NULL,'2015-05-07 20:32:46.454 +00:00','2015-05-07 20:32:46.454 +00:00');
```

### PR DESCRIPTION
**Pull request by BridgeAR**

### CODE REVIEW

**Comment by mickhansen** [comment]
The description is misleading, does it fix it so it will no longer insert null values or will do it again.

File: lib/model.js [hunk 1]
```diff
@@ -1337,7 +1337,9 @@ module.exports = (function() {
         // Filter dataValues by options.fields
         var values = {};
         options.fields.forEach(function(field) {
-          values[field] = instance.dataValues[field];
```
Comment (mickhansen) [inline lib/model.js]: This should probably just use the method from utils instead for mapping fields.

File: test/integration/model/create.test.js [hunk 2]
```diff
@@ -1351,6 +1351,29 @@ describe(Support.getTestDialectTeaser('Model'), function() {
...
+          style: Sequelize.STRING,
+          size: Sequelize.INTEGER,
+      });
+
+      return Beer.sync({force: true}).then(function () {
+        return Beer.bulkCreate([{
+            style: 'ipa'
+        }], {
+          logging: function(sql) {
+            if (dialect === 'postgres') {
```
Comment (mickhansen) [inline test/integration/model/create.test.js]: Really don't want to add more sql testing in the integration tests, we're trying to remove it as much as possible.

Comment (BridgeAR) [inline test/integration/model/create.test.js]: I thought so, but for me it was to late in the night and fast to write :blush: 
I'll change it later

File: lib/model.js (hunk 1 above)
Comment (BridgeAR) [inline lib/model.js]: I'll check that. I played around with this quite a bit, since I was not really happy with that solution (I came up with this after around three minutes and tried other stuff for at least an hour...).
I tried not to use fields all the time (that's not necessary at all) but couldn't find a good working solution.

File: test/integration/model/create.test.js (hunk 2 above)
Comment (BridgeAR) [inline test/integration/model/create.test.js]: Hm while thinking about it: A unit test would not help here. It's not really about the SQL generation but what happens earlier on. I could refactor the bulkInsertQuery, but I doubt that this would be the wanted solution.

**Comment by BridgeAR** [comment]
Ready for merge. This should actually speed up very big bulkCreates :smiley:

File: test/integration/model/create.test.js (hunk 2 above)
Comment (mickhansen) [inline test/integration/model/create.test.js]: If it's not about the sql don't test the sql ;)

Comment (mickhansen) [inline test/integration/model/create.test.js]: Perhaps do a test against a table with NOT NULL fields but with default values on the db side (not in sequelize since we then provide it).
