### PR TITLE
fix(decrement/negativeValue): Instance.decrement doesn't work with negative value (#8253)

### LINKED ISSUE #8253: Instance.decrement doesn't work with negative value
## What you are doing?

I'm calling ```Instance.decrement``` with the negative value.
```js
const assert = require('assert');
const Sequelize = require('sequelize');
const sequelize = new Sequelize('database', 'username', 'password', {
  // dialect: 'postgres',
  dialect: 'sqlite',
  storage: ':memory:'
});

const User = sequelize.define('user', {
  id: {
    type: Sequelize.UUID,
    primaryKey: true,
    defaultValue: Sequelize.UUIDV4
  },
  username: {
    type: Sequelize.STRING,
    allowNull: false
  },
  balance: {
    type: Sequelize.INTEGER,
    defaultValue: 0
  }
});

sequelize.sync()
  .then(() => User.create({ username: 'alice' }))
  .then(user => user.decrement({ balance: -5 }))
  // UPDATE `users` SET `balance`=`balance`--5,`updatedAt`='2017-09-05 07:44:49.742 +00:00' WHERE `id` = 'db0fb06a-c4ea-465a-8974-744c521f684d'
  //                                       --^ sql comment
  .then(user => user.reload())
  .then(user => assert(user.balance === +5))
;
```

## What do you expect to happen?
I wanted the user balance to be +5

## What is actually happening?
But the balance of the user has not changed

~~__Dialect:__ any~~
~~__Database version:__ any~~
~~__Sequelize version:__ 4.8.0~~

__Dialect:__ postgres
__Database version:__ 9.6.3
__Sequelize version:__ 4.8.0

__Dialect:__ sqlite
__Database version:__ 3.16.0
__Sequelize version:__ 4.8.0

### PR DESCRIPTION
**Pull request by dotpack**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in CONTRIBUTING.md?

### Description of change

Closes #8253

### CODE REVIEW

File: lib/dialects/abstract/query-generator.js [hunk 1]
```diff
@@ -403,7 +403,8 @@ const QueryGenerator = {
 
     for (const key in attrValueHash) {
       const value = attrValueHash[key];
-      values.push(this.quoteIdentifier(key) + '=' + this.quoteIdentifier(key) + operator + this.escape(value));
+      const negativeValueIsNotSqlComment = (typeof value === 'number' && value < 0) ? ' ' : '';
+      values.push(this.quoteIdentifier(key) + '=' + this.quoteIdentifier(key) + operator + negativeValueIsNotSqlComment + this.escape(value));
```
Comment (sushantdhiman) [inline lib/dialects/abstract/query-generator.js]: `negativeValueIsNotSqlComment` is tooooo verbose., just add a space after operator permanently
