### PR TITLE
fix(model): ordering by renamed sub-query attribute

### LINKED ISSUE #8739: Model.findAll with a hasMany relationship, order, and limit fails with custom field name
## What are you doing?

```js
const User = this.sequelize.define('user', {
  name: {
    type: Sequelize.STRING,
    field: 'some_other_name'
  }
});
const Project = this.sequelize.define('project', { title: Sequelize.STRING });
User.hasMany(Project);

return User.sync({ force: true })
  .then(() => Project.sync({ force: true }))
  .then(() => {
    return User.findAll({
      order: ['name'],
      limit: 1,
      include: [Project]
    });
  });
```

## What do you expect to happen?
No error

## What is actually happening?

Query generated is
```sql
SELECT "user".*, "projects"."id" AS "projects.id", "projects"."title" AS "projects.title", "projects"."createdAt" AS "projects.createdAt", "projects"."updatedAt" AS "projects.updatedAt", "projects"."userId" AS "projects.userId" 
FROM (SELECT "user"."id", "user"."some_other_name" AS "name", "user"."createdAt", "user"."updatedAt" FROM "users" AS "user" ORDER BY "user"."some_other_name" LIMIT 1) AS "user"
LEFT OUTER JOIN "projects" AS "projects" ON "user"."id" = "projects"."userId"
ORDER BY "user"."some_other_name";
```

which causes the following error since the subquery renames `user.some_other_name`, which is used by the `ORDER BY` clause, into `user.name`:

> SequelizeDatabaseError: column user.some_other_name does not exist

To work around this, you can manually project the columns Sequelize needs with `attributes: [['some_other_name', 'name'], ['some_other_name', 'some_other_name']],`. 

__Dialect:__ any
__Dialect version:__ any
__Database version:__ any
__Sequelize version:__ master
__Tested with latest release:__ Yes

### PR DESCRIPTION
**Pull request by gabegorelick**
Closes #8739

### Pull Request check-list

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)? **N/A**
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](../CONTRIBUTING.md)?

### Description of change

Use correct column name when ordering by an attribute projected from a sub-query. See #8739.

### CODE REVIEW

File: lib/dialects/abstract/query-generator.js [hunk 1]
```diff
@@ -1688,6 +1688,16 @@ const QueryGenerator = {
         ) {
           subQueryOrder.push(this.quote(order, model, '->'));
         }
+
+        if (subQuery) {
+          // Handle case where sub-query renames attribute we want to order by,
+          // see https://github.com/sequelize/sequelize/issues/8739
+          const subQueryAttribute = options.attributes.find(a => Array.isArray(a) && a[0] === order[0] && a[1]);
+          if (subQueryAttribute) {
+            order[0] = new Utils.Col(subQueryAttribute[1]);
```
Comment (sushantdhiman) [inline lib/dialects/abstract/query-generator.js]: These wont work when order contain multiple attributes being renamed by subQuery. Please add a test for two or more attributes

Comment (gabegorelick) [reply lib/dialects/abstract/query-generator.js]: @sushantdhiman I believe it actually will work since we loop over each `order` clause above. I added some tests which should confirm that. Let me know if I'm mistaken.
