### PR TITLE
fix(abstract/connection-manager): acquire call never finishes

### LINKED ISSUE #7616: Unhandled rejection SequelizeConnectionError: read ECONNRESET
when call functions to insert or get data from mysql at the first time, i got this error, please help

"sequelize": "~3.21.0", "mysql": 

> pool:{
        maxConnections:10,
        minConnections:1,
        maxIdleTime:12000
    },

> Unhandled rejection SequelizeConnectionError: read ECONNRESET
    at Quit._callback (/Users/tsy/devspace/builder/server/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:133:30)
    at Quit.Sequence.end (/Users/tsy/devspace/builder/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Protocol.handleNetworkError (/Users/tsy/devspace/builder/server/node_modules/mysql/lib/protocol/Protocol.js:364:14)
    at Connection._handleNetworkError (/Users/tsy/devspace/builder/server/node_modules/mysql/lib/Connection.js:421:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at ConnectionManager.disconnect (/Users/tsy/devspace/builder/server/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:130:10)
    at ConnectionManager.$disconnect (/Users/tsy/devspace/builder/server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:253:41)
    at Object.destroy (/Users/tsy/devspace/builder/server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:99:14)
    at Pool.destroy (/Users/tsy/devspace/builder/server/node_modules/generic-pool/lib/generic-pool.js:193:17)
    at Pool.removeIdle [as _removeIdle] (/Users/tsy/devspace/builder/server/node_modules/generic-pool/lib/generic-pool.js:224:10)
    at Timeout._onTimeout (/Users/tsy/devspace/builder/server/node_modules/generic-pool/lib/generic-pool.js:248:12)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

### LINKED ISSUE #7884: TimeoutError: ResourceRequest timed out
## What you are doing?

Testing the connection to a postgres amazon rds instance
```js
const sequelize = new Sequelize('dbname', 'username', 'password', {
  host: 'example.rds.amazonaws.com',
  dialect: 'postgres'
});


sequelize
  .authenticate()
  .then(() => {
    console.log('Connection has been established successfully.');
  })
  .catch(err => {
    console.error('Unable to connect to the database:', err);
  });
```

## What do you expect to happen?
App should connect and should output in console: "Connection has been established successfully"

## What is actually happening?
```
Unable to connect to the database: { TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (\myapp\node_modules\generic-pool\lib\ResourceRequest.js:58:17)
    at Timeout.bound (\myapp\node_modules\generic-pool\lib\ResourceRequest.js:8:15)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5) name: 'TimeoutError' }
```

__Dialect:__ postgres
__Database version:__ 9.6
__Sequelize version:__ 4.2.1

### LINKED ISSUE #8014: ResourceRequest timed out - connection not reestablished after db restarted
## What you are doing?
We're running into an issue where Sequelize will not reconnect to the database after the database is stopped and started again.  If you want, you can try hosting a local mssql database using this tutorial and running the following code, and following the steps I provide below:  

https://medium.com/@reverentgeek/sql-server-running-on-a-mac-3efafda48861

```js
const options = {
  host: 'localhost',
  dialect: 'mssql',
  pool: {
    max: 1,
    min: 0,
    idle: 5000,
    acquire: 5000
  },
  dialectOptions: {
    requestTimeout: 5000
  },
  isolationLevel: 'READ UNCOMMITTED'
};

const Sequelize = require('sequelize')

const sequelize = new Sequelize('testing', 'sa', 'P@55w0rd', options);

setInterval(() => {
  sequelize
    .query("SELECT 'connection is successful'", {
      type: Sequelize.QueryTypes.SELECT
    })
    .then((results) => {
      console.log(results);
    })
    .catch((err) => {
      console.log(err);
    })
}, 5000);
```

Steps after code is running and mssql container is running:

1. stop the container
2. wait until an interval fires and throws an error
3. start the container
4. notice that all future queries result in timeout errors

I'm pretty sure this should reject, but I'm not too sure: https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/connection-manager.js#L98

## What do you expect to happen?
Sequelize to reconnect and have queries work as normal.

## What is actually happening?
Sequelize fails to reconnect the created pool resource.

__Dialect:__ mssql, but probably all
__Database version:__ XXX
__Sequelize version:__ 4.4.2

### LINKED ISSUE #8076: Pooled connection exceeded the 'max_user_connections' resource
## What you are doing?
Connecting to a database on Heroku, and syncing the database. It looks like connections aren't pooling, though I've configured a maximum number of 5 connections in the pool. I posted on the Slack channel about 5 hours ago, and nothing there indicated my configuration was wrong, so I'm guessing it's a bug.
```
pool: {
    max: 5,
    min: 0,
    idle: 10000,
  }
```

## What do you expect to happen?
I wanted a successful connection to the database.

## What is actually happening?
```Data Sync failed User '{USERNAME}' has exceeded the 'max_user_connections' resource (current value: 10)```
From the database dashboard, I can see the Sequelize is making 10 connections, clearly more than the max config.

__Dialect:__ mysql
__Sequelize version:__ v3, v4 and also @swordfish444's fork, which updates the eviction config.

### LINKED ISSUE #8098: generic-pool "Resource not currently part of this pool" exceptions for mssql
## What you are doing?
I'm creating my Sequelize instance with the following options:

```js
const db_options =  {
     name: Config.DB_NAME, 
     username: Config.DB_USERNAME, 
     password, 
     host: Config.DB_HOST,
     dialect: "mssql",
     dialectOptions: {
         encrypt: true
     },
     pool: {
         min: 10,
         max: 300,
         idle: 30000,
     },
     benchmark: true
     logging: true
};
```

## What do you expect to happen?
No issues at all

## What is actually happening?
It seems like connections are dying before they are returned to the pool. The following exception is thrown quite often:

```
Error: Resource not currently part of this pool 
    at Pool.destroy (/data/node_modules/generic-pool/lib/Pool.js:450:35) 
    at Connection.connection.on.err (/data/node_modules/sequelize/lib/dialects/mssql/connection-manager.js:124:25) 
    at emitOne (events.js:96:13) at Connection.emit (events.js:188:7) 
    at Connection.socketError (/data/node_modules/tedious/lib/connection.js:703:14) 
    at emitOne (events.js:101:20) at Socket.emit (events.js:188:7) 
    at emitErrorNT (net.js:1278:8) at _combinedTickCallback (internal/process/next_tick.js:74:11) 
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

__Dialect:__ mssql
__Database version:__ V12
__Sequelize version:__ 4.4.2

### LINKED ISSUE #8133: Resource Request Timed out
## What you are doing?

I have a script which parses XML and loads them into a database. This script previously worked with Postgres SQL. I must switch to MSSQL. I have the following db connection settings:
```js
// code here
    { "username":username,
      "password":"password,
      "database":database,
      "host":host,
      "port": "post,
      "dialect":"mssql",
     "connectionTimeout": 0,
      "pool":{
         "max": 1,
         "min": 1,
         "idle": 200000,
        "acquire": 200000
      },
    "retry":{"max": 3},
    "logging": false,
    "dialectOptions": {
                "requestTimeout": 0,
     },
     "options":{
                "port": port
     }
}

```

## What do you expect to happen?
I wanted the data to load into the database.

## What is actually happening?
The records load for approximately 4 minutes. Then i get the following error:
```js
{ TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (/home/jcook/riqi_provider_directory/node_modules/sequelize/node_modules/generic-pool/lib/ResourceRequest.js:59:17)
    at Timeout.bound [as _onTimeout] (/home/jcook/riqi_provider_directory/node_modules/sequelize/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5) name: 'TimeoutError' }
```

Some data continues to load, but it looks like not all of my records are inserted into the database.

__Dialect:__ mssql 
__Database version:__ 2008
__Sequelize version:__ 4.1.0

### LINKED ISSUE #8185: Pool destroy error
I am using sequelize orm v4.4.2. I use pm2 to run my express app. After sometime the app started, I am getting below error regularly:

 You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
	Error: Resource not currently part of this pool
	at Pool.destroy (\node_modules\sequelize\node_modules\generic-pool\lib\Pool.js:450:35)
	at Connection.connection.on.err (\node_modules\sequelize\lib\dialects\mssql\connection-manager.js:124:25)
	at emitOne (events.js:115:13)
	at Connection.emit (events.js:210:7)
	at Connection.socketError (\node_modules\tedious\lib\connection.js:535:14)
	at emitOne (events.js:115:13)
	at Socket.emit (events.js:210:7)
	at emitErrorNT (internal/streams/destroy.js:64:8)
	at _combinedTickCallback (internal/process/next_tick.js:138:11)
	at process._tickDomainCallback (internal/process/next_tick.js:218:9)
	Unhandled rejection Error: Resource not currently part of this pool
	at Pool.destroy (\node_modules\sequelize\node_modules\generic-pool\lib\Pool.js:450:35)
	at Connection.connection.on.err (\node_modules\sequelize\lib\dialects\mssql\connection-manager.js:124:25)
	at emitOne (events.js:115:13)
	at Connection.emit (events.js:210:7)
	at Connection.socketError (\node_modules\tedious\lib\connection.js:535:14)
	at emitOne (events.js:115:13)
	at Socket.emit (events.js:210:7)
	at emitErrorNT (internal/streams/destroy.js:64:8)
	at _combinedTickCallback (internal/process/next_tick.js:138:11)
	at process._tickDomainCallback (internal/process/next_tick.js:218:9)

This is my sequelize configuration:

var sequelize = new Sequelize(
    process.env.DB_CATALOG,
    process.env.DB_USER,
    process.env.DB_PASSWORD,
    {
        logging: true,
        host: process.env.DB_HOST,
        dialect: 'mssql',
        port: process.env.DB_PORT,
        dialectOptions: {
            connectTimeout: 10000,
            instanceName: process.env.DB_SERVER_INSTANCE,
            multipleStatements: true
        },
        define:
        {
            timestamps: false // disabled timestamp to ignore createdAt, updatedAt fields 
        },
        pool: {
            min: 1,
            max: 10,
            acquire:  10000,
          },
    });

Can anyone please let me know what is the cause of error

### LINKED ISSUE #8322: Error: Resource not currently part of this pool
## What are you doing?
Running against Google Cloud SQL and today I think they did some rolling restarts and sequelize continued to throw these errors (417 of them over an hour) and did not recover. Application had to be shutdown and restarted.

## What do you expect to happen?
Errors to go away when database comes back.

## What is actually happening?
Errors continually get thrown until restart, unable to recover on its own.

```
Unhandled rejection Error: Resource not currently part of this pool
    at Pool.release (/app/node_modules/generic-pool/lib/Pool.js:422:35)
    at ConnectionManager.releaseConnection (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:292:22)
    at Transaction.cleanup (/app/node_modules/sequelize/lib/transaction.js:165:50)
    at sequelize.getQueryInterface.rollbackTransaction.finally (/app/node_modules/sequelize/lib/transaction.js:95:23)
    at PassThroughHandlerContext.finallyHandler (/app/node_modules/bluebird/js/release/finally.js:56:23)
    at bound (domain.js:280:14)
    at PassThroughHandlerContext.runBound (domain.js:293:12)
    at PassThroughHandlerContext.tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

__Dialect:__ mysql
__Dialect version:__ 
__Database version:__ 5.7
__Sequelize version:__ 4.8.3
__Tested with master branch:__ No

**Note :** _Your issue may be ignored by maintainers if its not tested against `master` branch OR does not follow issue template._

### PR DESCRIPTION
**Pull request by sushantdhiman**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in CONTRIBUTING.md?

### Description of change

This is basically a hack but pooling library has given us no options. Pool acquire call
now resolves even if there is an error. We simply check if its an error instance or not
and reject accordingly.

Read more here https://github.com/sequelize/sequelize/issues/7884#issuecomment-330136439

`_determineConnection` method can be used to check if thing returned by pooling library is
actaully a connection or error

Closes #7884
Closes #7616
Closes #8014
Closes #8133
Closes #8322
Closes #8185
Closes #8098
Closes #8076
Closes #8014

### CODE REVIEW

**Comment by sushantdhiman** [comment]
This is sort of work in progress, I will ask for final review from @sequelize/core when I am happy with this PR and may be add a few tests

File: lib/dialects/abstract/connection-manager.js [hunk 1]
```diff
@@ -248,56 +217,65 @@ class ConnectionManager {
...
+      if (mayBeConnection instanceof Error) {
+        return this.pool.destroy(mayBeConnection)
+          .then(() => { reject(mayBeConnection); })
+          .catch(/Resource not currently part of this pool/, () => {
+            reject(mayBeConnection);
+          });
+      }
+
+      return resolve(mayBeConnection);
     });
```
Comment (caseyduquettesc) [inline lib/dialects/abstract/connection-manager.js]: How do you feel about this? Since you're using bluebird, it reduces a little boilerplate and I think this is equivalent.

```javascript
_determineConnection(mayBeConnection) {
  if (mayBeConnection instanceof Error) {
    return Promise.resolve(this.pool.destroy(mayBeConnection))
      .catch(/Resource not currently part of this pool/, () => {}) // suppress this error
      .then(() => { throw mayBeConnection; });
  }

  return Promise.resolve(mayBeConnection);
}
```

**Comment by caseyduquettesc** [comment]
For a "hack" this certainly looks cleaner to me :)

File: lib/dialects/abstract/connection-manager.js [hunk 2]
```diff
@@ -248,59 +217,73 @@ class ConnectionManager {
...
   _connect(config) {
-    return this.sequelize.runHooks('beforeConnect', config)
-      .then(() => this.dialect.connectionManager.connect(config))
-      .then(connection => this.sequelize.runHooks('afterConnect', connection, config).return(connection));
+    return new Promise(resolve => {
+      this.sequelize.runHooks('beforeConnect', config)
+        .then(() => this.dialect.connectionManager.connect(config))
+        .then(connection => this.sequelize.runHooks('afterConnect', connection, config).return(connection))
+        .then(connection => resolve(connection))
+        .catch(e => { resolve(e); });
```
Comment (mickhansen) [inline lib/dialects/abstract/connection-manager.js]: No need to wrap in new Promise i reckon? Can just `return err` from catch i think?

Comment (sushantdhiman) [reply lib/dialects/abstract/connection-manager.js]: :+1:

File: lib/dialects/abstract/connection-manager.js [hunk 3]
```diff
@@ -85,20 +90,7 @@ class ConnectionManager {
...
-            .then(resolve)
-            .catch(e => {
-              // dont throw otherwise pool will release _dispense call
-              // which will call _connect even if error is fatal
-              // https://github.com/coopernurse/node-pool/issues/161
-              this.poolError = e;
-            });
-        }),
+        create: () => this._connect(config),
         destroy: connection => {
```
Comment (amachang) [inline lib/dialects/abstract/connection-manager.js]: suggest changing name <code>connection</code> to <code>mayBeConnection</code>

And, I think "connection destroy" shouldn't be logged if error.

```javascript
if (mayBeConnection instanceof Error) {
  return Promise.resolve(); // avoid "connection destroy" debug log
}
return this._disconnect(mayBeConnection).tap(() => {
  debug('connection destroy');
});
```

File: lib/dialects/abstract/connection-manager.js [hunk 4]
```diff
@@ -85,20 +90,7 @@ class ConnectionManager {
...
-            })
-            .then(resolve)
-            .catch(e => {
-              // dont throw otherwise pool will release _dispense call
-              // which will call _connect even if error is fatal
-              // https://github.com/coopernurse/node-pool/issues/161
-              this.poolError = e;
-            });
-        }),
+        create: () => this._connect(config),
```
Comment (amachang) [inline lib/dialects/abstract/connection-manager.js]: I think converting <code>reject(err)</code> to <code>resolve(err)</code> should be **here**. This hack is only for pool. <code>_connect</code> shouldn't be hacky.

```javascript
this._connect(config).catch(err => err);

File: lib/dialects/abstract/connection-manager.js [hunk 5]
```diff
@@ -175,69 +166,47 @@ class ConnectionManager {
...
-              });
-          });
-        },
-        destroy: connection => {
-          return this._disconnect(connection);
+          return this
+            ._connect(config.replication.read[nextRead])
+            .tap(connection => {
+              connection.queryType = 'read';
+            });
```
Comment (amachang) [inline lib/dialects/abstract/connection-manager.js]: As I mentioned before,  I think the hack should be here.

```javascript
return this
  ._connect(config.replication.read[nextRead])
  .then(connection => { // not to apply to error object, use "then", not "tap"
    connection.queryType = 'read';
  })
  .catch(err => err);
```

File: lib/dialects/abstract/connection-manager.js [hunk 6]
```diff
@@ -175,69 +166,47 @@ class ConnectionManager {
...
         },
+        destroy: connection => this._disconnect(connection),
```
Comment (amachang) [inline lib/dialects/abstract/connection-manager.js]:
```javascript
connection => {
  if (mayBeConnection instanceof Error) {
    return Promise.resolve();
  }
  return this._disconnect(connection);
}
```

File: lib/dialects/abstract/connection-manager.js [hunk 7]
```diff
@@ -175,69 +166,47 @@ class ConnectionManager {
...
             ._connect(config.replication.write)
-            .then(connection => {
+            .tap(connection => {
               connection.queryType = 'write';
-              this.poolError = null;
-              return resolve(connection);
-            })
-            .catch(e => {
-              this.poolError = e;
             });
```
Comment (amachang) [inline lib/dialects/abstract/connection-manager.js]: Same as above:
```javascript
return this
  ._connect(config.replication.write)
  .then(connection => { // not to apply to error object, use "then", not "tap"
    connection.queryType = 'write';
  })
  .catch(err => err);
```

File: lib/dialects/abstract/connection-manager.js [hunk 8]
```diff
@@ -248,64 +217,80 @@ class ConnectionManager {
...
+
+    return Promise.resolve(mayBeConnection);
   }
 
   _connect(config) {
     return this.sequelize.runHooks('beforeConnect', config)
       .then(() => this.dialect.connectionManager.connect(config))
-      .then(connection => this.sequelize.runHooks('afterConnect', connection, config).return(connection));
+      .then(connection => this.sequelize.runHooks('afterConnect', connection, config).return(connection))
+      .catch(error => { return error; });
```
Comment (amachang) [inline lib/dialects/abstract/connection-manager.js]: As I mentioned above, I think the hack shouldn't be here.

Delete call of <code>catch</code>.

File: lib/dialects/abstract/connection-manager.js [hunk 9]
```diff
@@ -248,64 +217,80 @@ class ConnectionManager {
...
   }
 
   _disconnect(connection) {
+    // hacky, _determineConnection could send Error instance for disconnection
+    if (connection instanceof Error) {
+      return Promise.resolve();
+    }
```
Comment (amachang) [inline lib/dialects/abstract/connection-manager.js]: As I mentioned above, I think the hack shouldn't be here.

Delete if statement of <code>connection instanceof Error</code>.

File: lib/dialects/abstract/connection-manager.js (hunk 4 above)
Comment (amachang) [inline lib/dialects/abstract/connection-manager.js]: I think converting <code>reject(err)</code> to <code>resolve(err)</code> should be **here**. This hack is only for pool. <code>_connect</code> shouldn't be hacky.

```javascript
this._connect(config).catch(err => err);
```

File: lib/dialects/abstract/connection-manager.js (hunk 3 above)
Comment (amachang) [inline lib/dialects/abstract/connection-manager.js]: suggest changing name <code>connection</code> to <code>mayBeConnection</code>

And, I think "connection destroy" shouldn't be logged if error.

```javascript
if (mayBeConnection instanceof Error) {
  return Promise.resolve(); // avoid "connection destroy" debug log
}
return this._disconnect(mayBeConnection).tap(() => {
  debug('connection destroy');
});
```

File: lib/dialects/abstract/connection-manager.js (hunk 5 above)
Comment (amachang) [inline lib/dialects/abstract/connection-manager.js]: As I mentioned above,  I think the hack should be here.

```javascript
return this
  ._connect(config.replication.read[nextRead])
  .then(connection => { // not to apply to error object, use "then", not "tap"
    connection.queryType = 'read';
  })
  .catch(err => err);
```

File: lib/dialects/abstract/connection-manager.js (hunk 6 above)
Comment (amachang) [inline lib/dialects/abstract/connection-manager.js]: Same as above:
```javascript
connection => {
  if (mayBeConnection instanceof Error) {
    return Promise.resolve();
  }
  return this._disconnect(connection);
}
```

File: lib/dialects/abstract/connection-manager.js (hunk 7 above)
Comment (amachang) [inline lib/dialects/abstract/connection-manager.js]: Same as above:
```javascript
return this
  ._connect(config.replication.write)
  .then(connection => { // not to apply to error object, use "then", not "tap"
    connection.queryType = 'write';
  })
  .catch(err => err);
```

File: lib/dialects/abstract/connection-manager.js (hunk 8 above)
Comment (amachang) [inline lib/dialects/abstract/connection-manager.js]: As I mentioned above, I think the hack shouldn't be here.

Delete call of <code>catch</code>.

File: lib/dialects/abstract/connection-manager.js (hunk 9 above)
Comment (amachang) [inline lib/dialects/abstract/connection-manager.js]: As I mentioned above, I think the hack shouldn't be here.

Delete call of <code>catch</code>.

**Comment by amachang** [comment]
I suggest a little bit changes, but it works nice!

File: lib/dialects/abstract/connection-manager.js [hunk 10]
```diff
@@ -6,17 +6,24 @@ const _ = require('lodash');
...
 const semver = require('semver');
-const timers = require('timers');
 
 const defaultPoolingConfig = {
   max: 5,
   min: 0,
   idle: 10000,
   acquire: 10000,
-  evict: 60000,
+  evict: 10000,
```
Comment (sushantdhiman) [inline lib/dialects/abstract/connection-manager.js]: We need to set `evict ~= idle` , reason being even if idle time is crossed its the evictor that will remove those idle connections.

More details https://github.com/coopernurse/node-pool/issues/178

File: lib/dialects/abstract/connection-manager.js [hunk 11]
```diff
@@ -25,21 +32,19 @@ class ConnectionManager {
...
     this.versionPromise = null;
-    this.poolError = null;
     this.dialectName = this.sequelize.options.dialect;
 
     if (config.pool === false) {
       throw new Error('Support for pool:false was removed in v4.0');
     }
 
-    config.pool =_.defaults(config.pool || {}, defaultPoolingConfig, {
+    this.config.pool =_.defaults(config.pool || {}, defaultPoolingConfig, {
```
Comment (sushantdhiman) [inline lib/dialects/abstract/connection-manager.js]: Woosh, user supplied `pooling.config` was never used

Comment (caseyduquettesc) [reply lib/dialects/abstract/connection-manager.js]: nit: space after equals

Comment (caseyduquettesc) [reply lib/dialects/abstract/connection-manager.js]: While I agree with the change because it's clearer, doesn't `this.config === config`? And wouldn't that mean that changing `config` also changes `this.config`?

Comment (sushantdhiman) [reply lib/dialects/abstract/connection-manager.js]: `const config` is deep cloned version of `this.config`, so any changes made to it will not reflect into `this.config`

File: lib/dialects/abstract/connection-manager.js (hunk 10 above)
Comment (janmeier) [reply lib/dialects/abstract/connection-manager.js]: Maybe a good idea to mention this in the API docs. (perhaps just a link to that issue)

File: test/integration/dialects/mysql/connector-manager.test.js [hunk 12]
```diff
@@ -34,18 +34,20 @@ if (dialect === 'mysql') {
...
       const User = sequelize.define('User', { username: DataTypes.STRING });
 
       return User
         .sync({force: true})
-        .then(() => User.create({username: 'user1'}))
+        .then(() => User.create({ username: 'user1' }))
         .then(() => sequelize.Promise.delay(100))
         .then(() => {
-        // This query will be queued just after the `client.end` is executed and before its callback is called
+          expect(sequelize.connectionManager.pool.size).to.equal(0);
```
Comment (janmeier) [inline test/integration/dialects/mysql/connector-manager.test.js]: Good catch - Otherwise we're not really sure what this test is testing! :D

File: lib/dialects/abstract/connection-manager.js [hunk 13]
```diff
@@ -68,59 +79,55 @@ class ConnectionManager {
...
-              // which will call _connect even if error is fatal
-              // https://github.com/coopernurse/node-pool/issues/161
-              this.poolError = e;
-            });
-        }),
-        destroy: connection => {
-          return this._disconnect(connection).tap(() => {
-            debug('connection destroy');
-          });
+        create: () => this._connect(config).catch(err => err ),
```
Comment (eseliger) [inline lib/dialects/abstract/connection-manager.js]: space

File: test/config/config.js [hunk 14]
```diff
@@ -26,7 +26,7 @@ module.exports = {
     database: process.env.SEQ_MSSQL_DB   || process.env.SEQ_DB   || 'sequelize_test',
     username: process.env.SEQ_MSSQL_USER || process.env.SEQ_USER || 'sequelize',
     password: process.env.SEQ_MSSQL_PW   || process.env.SEQ_PW   || 'nEGkLma26gXVHFUAHJxcmsrK',
-    host:     process.env.SEQ_MSSQL_HOST || process.env.SEQ_HOST || 'mssql.sequelizejs.com',
```
Comment (eseliger) [inline test/config/config.js]: did we host that? If so, we can shut it down then :)

Comment (janmeier) [reply test/config/config.js]: @sdepold

**Comment by mjy78** [comment]
Thanks for putting the time into this fix. I've deployed the update, however under load I'm still seeing the "ResourceRequest timed out" errors even with a max pool size of 50. I then increased pool.acquire to 20000 and thus far the errors appeared to have stopped.

**Comment by ruanjiayou** [comment]
can we listen this error event?when "ResourceRequest timed out" occured ,we just use "process.exit(0)",  then pm2 will restart application?

File: lib/dialects/abstract/connection-manager.js (hunk 10 above)
Comment (xianxingg) [reply lib/dialects/abstract/connection-manager.js]: @sushantdhiman by saying `evict ~= idle`, do you mean `evict ≈ idle` ? i think it's fine to set evict to some value a little smaller than idle.

Comment (sushantdhiman) [reply lib/dialects/abstract/connection-manager.js]: @xianxingg as mentioned in https://github.com/coopernurse/node-pool/issues/178#issuecomment-327110870

They should be close (or even evict < idle) because only evictor remove idle connection from pool
