### PR TITLE
Fix mysql showAllTables listing all tables for all databases

### LINKED ISSUE #10629: mariadb: showAllTables lists tables from other databases
## What are you doing?
With mariadb, `showAllTables` lists all tables on the server (except system tables), rather than only those tables in the current database (which seems to be the behavior with other dialects, in particular mysql and postgres).

```js
  const sequelize = new Sequelize(config.dbUrl);
  console.log(await sequelize.getQueryInterface().showAllTables());
```

## What do you expect to happen?
`[]`

## What is actually happening?
Tables from other databases on the server.

Notably, this means that `dropAllTables` will attempt to clear out other databases, too.

The query seems to be using `information_schema.tables`, but (unlike Postgres) information_schema is global in MySQL/MariaDB. (Switching dialect to mysql, which uses `SHOW TABLES`, works.)

__Dialect:__ mariadb
__Dialect version:__ `mariadb@2.0.3`
__Database version:__ 10.3
__Sequelize version:__ master
__Tested with latest release:__ Yes

### PR DESCRIPTION
**Pull request by UziTech**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Did you update the typescript typings accordingly (if applicable)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Fixes https://github.com/sequelize/sequelize/pull/11439#pullrequestreview-290558915
Fixes #10629

### CODE REVIEW

File: test/config/mysql/mysql.sql [hunk 1]
```diff
@@ -0,0 +1,3 @@
+GRANT ALL ON *.* TO 'sequelize_test'@'%' with grant option;
```
Comment (UziTech) [inline test/config/mysql/mysql.sql]: MySql is failing because the user `sequalize_test` doesn't have permissions to use the created database.

I noticed that MariaDB has a file like this to grant it privileges but I don't know how to do the same in mysql.

@papb any ideas?

Comment (papb) [reply test/config/mysql/mysql.sql]: Hmm... Note that [this line in .travis.yml](https://github.com/sequelize/sequelize/blob/8b53f721a07e4ea5a42d74199b319f813f2c109c/.travis.yml#L31) tells MariaDB that it should use that file. I am not sure if something similar exists for MySQL, but if it does, you'll have to update the .travis.yml to do something similar.

Another options that comes to my mind is trying the following at the beginning of your test:

```js
sequelize.query(`GRANT ALL ON *.* TO 'sequelize_test'@'%' with grant option;`)
```

Comment (UziTech) [reply test/config/mysql/mysql.sql]: I tried your second option but it just threw an error saying `sequalize_test` didn't have permission lol

Comment (papb) [reply test/config/mysql/mysql.sql]: Hmm... Good luck :P

File: lib/dialects/mariadb/query-generator.js [hunk 2]
```diff
@@ -24,8 +24,12 @@ class MariaDBQueryGenerator extends MySQLQueryGenerator {
     return `SELECT SCHEMA_NAME as schema_name FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME NOT IN ('MYSQL', 'INFORMATION_SCHEMA', 'PERFORMANCE_SCHEMA'${skip ? skip.reduce( (sql, schemaName) => sql +=  `,${this.escape(schemaName)}`, '') : ''});`;
   }
 
-  showTablesQuery() {
-    return 'SELECT TABLE_NAME, TABLE_SCHEMA FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA NOT IN (\'MYSQL\', \'INFORMATION_SCHEMA\', \'PERFORMANCE_SCHEMA\') AND TABLE_TYPE = \'BASE TABLE\'';
+  showTablesQuery(database) {
+    let query = 'SELECT TABLE_NAME, TABLE_SCHEMA FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA NOT IN (\'MYSQL\', \'INFORMATION_SCHEMA\', \'PERFORMANCE_SCHEMA\') AND TABLE_TYPE = \'BASE TABLE\'';
```
Comment (UziTech) [inline lib/dialects/mariadb/query-generator.js]: I would like to get feedback from @rusher since he created the PR for MariaDB (#10192).

I have a couple questions about your initial PR:

1. Was it intentional to return all tables in all databases?
2. If MariaDB has schemas separate from databases why is `TABLE_SCHEMA` the same as the database in `INFORMATION_SCHEMA.TABLES`?

**Comment by UziTech** [comment]
I'm not sure why MariaDB is failing on travis but it seems unrelated to this PR. @papb can you rerun that job on travis?

**Comment by papb** [comment]
@UziTech We have been experiencing these flaky tests in Sequelize for quite a while now, they always have the form of `Error: Expected 0 running queries. 1 queries still running`. Don't worry about them, me and sushantdhiman know that we can ignore those for now, so your PR is green for our eyes :D

Also whenever you want to trigger a rerun you can just:

```
git commit --allow-empty --no-verify -m "rerun CI" && git push
```

(Side note: I don't have permissions in Travis to trigger a rerun...)

File: docker-compose.yml [hunk 3]
```diff
@@ -56,6 +56,8 @@ services:
       MYSQL_DATABASE: sequelize_test
       MYSQL_USER: sequelize_test
       MYSQL_PASSWORD: sequelize_test
+    volumes:
+    - $MYSQLDB_ENTRYPOINT:/docker-entrypoint-initdb.d
```
Comment (papb) [inline docker-compose.yml]: I see you figured it out, excellent!!

**Comment by UziTech** [comment]
> `git commit --allow-empty --no-verify -m "rerun CI" && git push`

Thanks that's a neat hack.

I wonder if the flaky tests are related to https://github.com/sequelize/sequelize-pool/pull/12. I originally found that issue when I noticed tests that relied on sequalize made jest linger after tests were completed.

File: test/integration/query-interface.test.js [hunk 4]
```diff
@@ -63,6 +63,23 @@ describe(Support.getTestDialectTeaser('QueryInterface'), () => {
           expect(tableNames).to.deep.equal(['my_test_table']);
         });
     });
+
+    if (dialect !== 'sqlite' && dialect !== 'postgres') {
```
Comment (joaoe) [inline test/integration/query-interface.test.js]: Postgre supports `CREATE DATABASE`.
The odd one out is SQLite. For that one you can use `ATTACH DATABASE 'blah.db' as my_db` although the test is somewhat unnecessary because the `sqlite_master` view is limited to each database.

File: lib/dialects/mysql/query-generator.js [hunk 5]
```diff
@@ -148,8 +148,12 @@ class MySQLQueryGenerator extends AbstractQueryGenerator {
     return `SHOW FULL COLUMNS FROM ${table};`;
   }
 
-  showTablesQuery() {
-    return "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE';";
+  showTablesQuery(database) {
+    let query = 'SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA NOT IN (\'MYSQL\', \'INFORMATION_SCHEMA\', \'PERFORMANCE_SCHEMA\') AND TABLE_TYPE = \'BASE TABLE\'';
```
Comment (joaoe) [inline lib/dialects/mysql/query-generator.js]: What if I want to query the `MYSQL` schema ?
Perhaps this check would be a bit better
```
if (database) {
  query += ' AND TABLE_SCHEMA = `${database}`'
} else {
  query += ' AND TABLE_SCHEMA NOT IN ...'
}
```

File: lib/dialects/mariadb/query-generator.js (hunk 2 above)
Comment (joaoe) [reply lib/dialects/mariadb/query-generator.js]: https://dev.mysql.com/doc/refman/8.0/en/create-database.html
`CREATE SCHEMA is a synonym for CREATE DATABASE.`

File: test/integration/query-interface.test.js (hunk 4 above)
Comment (UziTech) [reply test/integration/query-interface.test.js]: Postgres doesn't allow creating a table in another database

```sql
CREATE TABLE my_test_db.my_test_table2 (id INT)
```

Comment (joaoe) [reply test/integration/query-interface.test.js]: Googling the issue shows that one needs a new connection to the other DB. Seems a bit overkill so not worthwhile testing for that. But at least you should write a comment why these dialects are being excluded.

File: lib/dialects/mariadb/query-generator.js (hunk 2 above)
Comment (UziTech) [reply lib/dialects/mariadb/query-generator.js]: It seems to be the same for MariaDB

https://mariadb.com/kb/en/library/create-database/

I've never used MariaDB and I'm starting to wonder if it actually supports schemas the same way PostgreSQL and MSSQL do.

**Comment by UziTech** [comment]
This PR seems ready but I would still like to get feedback from @rusher on (#10192).

I have a couple questions about his initial PR:

1. Was it intentional to return all tables in all databases?
2. Does MariaDB actually have support for schemas like PostgreSQL and MSSQL?
   `CREATE SCHEMA` seems to just be a synonym of `CREATE DATABASE`
   https://mariadb.com/kb/en/library/create-database

File: test/config/mysql/mysql.sql [hunk 6]
```diff
@@ -0,0 +1,3 @@
...
+
+FLUSH PRIVILEGES;
```
Comment (UziTech) [inline test/config/mysql/mysql.sql]: I'm not sure if it would be better to add this file or just use the one for MariaDB since they are exactly the same.

Comment (papb) [reply test/config/mysql/mysql.sql]: I think it's better to keep separate files.

**Comment by rusher** [comment]
@UziTech 

See the same discussion here : https://github.com/sequelize/sequelize/issues/10629

>Does MariaDB actually have support for schemas like PostgreSQL and MSSQL?
>CREATE SCHEMA seems to just be a synonym of CREATE DATABASE
Not really. Actually. MariaDB schema is synonym of database.
MariaDB doesn't have databases but schemas. In fact, to try to be clear, MariaDB handle like there is only one database named 'def'.

See extract from information_schema.TABLES: 
image

Having multiple databases might come in a very near future, mostly because of compatibility. 

When creating a table with a schema, it will be rendered like a mariadb user would expect it, in the designated schema.  
Using Mysql implementation will create a table named 'schema_table'.

**Comment by UziTech** [comment]
Ok so if I'm getting this correct in MariaDB a "Database" is the same as a "Schema" like MySQL but MariaDB **might** support "Catalogs" in the future (right now it is always "def") which is like a "Database" in MSSQL and PostgreSQL.

I've never used MariaDB but if I ever did I would assume a "Database" is a "Schema" not a "Catalog". Therefore to make `showAllTables` intuitive `returns the name of all existing tables in the database.` means it returns all tables in the "Schema" not the "Catalog"

**Comment by UziTech** [comment]
@papb I think this PR is ready to be merged.

File: test/integration/query-interface.test.js [hunk 7]
```diff
@@ -63,6 +63,45 @@ describe(Support.getTestDialectTeaser('QueryInterface'), () => {
...
+      // NOTE: sqlite doesn't allow querying between databases and
+      // postgres requires creating a new connection to create a new table.
+      it('should not show tables in other databases', function() {
+        return this.queryInterface
+          .createTable('my_test_table1', { name: DataTypes.STRING })
+          .then(() => this.sequelize.query('CREATE DATABASE my_test_db'))
+          .then(() => this.sequelize.query(`CREATE TABLE my_test_db${dialect === 'mssql' ? '.dbo' : ''}.my_test_table2 (id INT)`))
```
Comment (rusher) [inline test/integration/query-interface.test.js]: having a test `dialect === 'mssql'`  inside a test `if (dialect !== 'sqlite' && dialect !== 'postgres') {` ?

Comment (UziTech) [reply test/integration/query-interface.test.js]: because `mssql` requires listing the schema (`dbo`) when creating the table but `mysql` and `mariadb` don't.

File: test/integration/query-interface.test.js [hunk 8]
```diff
@@ -63,6 +63,45 @@ describe(Support.getTestDialectTeaser('QueryInterface'), () => {
...
+            expect(tableNames).to.deep.equal(['my_test_table1']);
+          });
+      });
+
+      if (dialect === 'mysql' || dialect === 'mariadb') {
+        it('should show all tables in all databases', function() {
+          return this.queryInterface
+            .createTable('my_test_table1', { name: DataTypes.STRING })
+            .then(() => this.sequelize.query('CREATE DATABASE my_test_db'))
+            .then(() => this.sequelize.query(`CREATE TABLE my_test_db${dialect === 'mssql' ? '.dbo' : ''}.my_test_table2 (id INT)`))
```
Comment (rusher) [inline test/integration/query-interface.test.js]: having a test dialect === 'mssql' inside a test if (dialect !== 'sqlite' && dialect !== 'postgres') { ? (sorry for previous comment, place was here :p )

Comment (UziTech) [reply test/integration/query-interface.test.js]: good catch

**Comment by UziTech** [comment]
Looks like all tests are passing but travis hasn't reported back. I rebased as well so the commits actually make sense for semantic-release.

File: lib/dialects/mariadb/query-generator.js [hunk 9]
```diff
@@ -24,8 +24,14 @@ class MariaDBQueryGenerator extends MySQLQueryGenerator {
     return `SELECT SCHEMA_NAME as schema_name FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME NOT IN ('MYSQL', 'INFORMATION_SCHEMA', 'PERFORMANCE_SCHEMA'${skip ? skip.reduce( (sql, schemaName) => sql += `,${this.escape(schemaName)}`, '') : ''});`;
   }
 
-  showTablesQuery() {
-    return 'SELECT TABLE_NAME, TABLE_SCHEMA FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA NOT IN (\'MYSQL\', \'INFORMATION_SCHEMA\', \'PERFORMANCE_SCHEMA\') AND TABLE_TYPE = \'BASE TABLE\'';
+  showTablesQuery(database) {
+    let query = 'SELECT TABLE_NAME, TABLE_SCHEMA FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = \'BASE TABLE\'';
+    if (database) {
+      query += ` AND TABLE_SCHEMA = '${database}'`;
```
Comment (sushantdhiman) [inline lib/dialects/mariadb/query-generator.js]: `TABLE_SCHEMA = ${this.escape(database)}`

File: lib/dialects/mysql/query-generator.js [hunk 10]
```diff
@@ -148,8 +148,14 @@ class MySQLQueryGenerator extends AbstractQueryGenerator {
     return `SHOW FULL COLUMNS FROM ${table};`;
   }
 
-  showTablesQuery() {
-    return "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE';";
+  showTablesQuery(database) {
+    let query = 'SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = \'BASE TABLE\'';
+    if (database) {
+      query += ` AND TABLE_SCHEMA = '${database}'`;
```
Comment (sushantdhiman) [inline lib/dialects/mysql/query-generator.js]: ```TABLE_SCHEMA = ${this.escape(database)}```

**Comment by misos1** [comment]
Seems showAllTables is missing in documentation.

https://sequelize.org/master/class/lib/query-interface.js~QueryInterface.html

**Comment by papb** [comment]
@misos1 Correct, see #11451
