### PR TITLE
fix addIndexQuery when an object is provided as the tableName

### LINKED ISSUE #3204: options.indexes in define() throws error when the model has a schema
(I am using dialect postgres, on sequelize version 2.0.3)

Included the following in my model options definition:

```json
{
    "indexes": [
        {
            "unique": true,
            "fields": ["myField"]
        }
    ]
}
```

Upon `sequelize.sync()`, I received the following error:

```
Possibly unhandled TypeError: Object "MySchema"."MyTable" has no method 'indexOf'
    at Object.module.exports.QueryGenerator.quoteIdentifiers (...MyProject\node_modules\sequelize\lib\dialects\abstract\query-generator.js:749:23)
    at Object.module.exports.QueryGenerator.addIndexQuery (...MyProject\node_modules\sequelize\lib\dialects\abstract\query-generator.js:519:20)
    at module.exports.QueryInterface.addIndex (...MyProject\node_modules\sequelize\lib\query-interface.js:443:35)
    at ...MyProject\node_modules\sequelize\lib\model.js:418:36
    ...
```

In lib/model.js at line 418, I found the following code:

```node
self.QueryInterface.addIndex(self.getTableName(options), index.fields, index, self.tableName);
```

The problem appears to be that the first argument to `addIndex()` is `self.getTableName(options)`, which returns an **object** of table name data (including a `toString()` method), instead of the actual **string** table name that the `addIndex()` method expects.  If I modify this code to pass the first argument as `self.getTableName(options).toString()`, it creates the index and does not produce an error.

Is this truly a bug, or am I somehow doing this wrong?

### PR DESCRIPTION
**Pull request by mikrofusion**
Fixes #3204

### CODE REVIEW

File: lib/dialects/abstract/query-generator.js [hunk 1]
```diff
@@ -478,6 +478,11 @@ module.exports = (function() {
         options.using = options.indexType || options.method;
       }
 
+      // table name can be either a string or an object
+      if (Utils._.isObject(tableName)) {
+        tableName = tableName.schema + '.' + tableName.tableName;
```
Comment (janmeier) [inline lib/dialects/abstract/query-generator.js]: Use `quoteTable` instead - the delimiter might not always be a dot :)

**Comment by janmeier** [comment]
Could you  add a test case as well?

File: lib/dialects/abstract/query-generator.js (hunk 1 above)
Comment (mickhansen) [inline lib/dialects/abstract/query-generator.js]: Actually this code could be removed entirely, just change `quoteIdentifiers` to `quoteTable` in the bottom.

**Comment by mikrofusion** [comment]
@janmeier @mickhansen thanks for the feedback.  Changing ```quoteIdentifiers``` to ```quoteTable``` seemed to do the trick (in a much cleaner way).  I'll try to get specs added soon.

**Comment by janmeier** [comment]
Sweet! :)

**Comment by mikrofusion** [comment]
@janmeier I added specs.  Can you take a look and let me know what you think?

File: test/unit/sql/index.test.js [hunk 2]
```diff
@@ -17,14 +17,14 @@ suite(Support.getTestDialectTeaser('SQL'), function() {
...
-          default: 'CREATE INDEX [schema_table_column1_column2] ON [schema].[table] ([column1], [column2])'
+          default: 'CREATE INDEX [schema_table_column1_column2] ON [schema.table] ([column1], [column2])'
         });
 
         expectsql(sql.addIndexQuery(sql.quoteTable(sql.addSchema({
           schema: 'schema',
           tableName: 'table'
         })), ['column1', 'column2'], {}), {
-          default: 'CREATE INDEX [schema_table_column1_column2] ON [schema].[table] ([column1], [column2])'
+          default: 'CREATE INDEX [schema_table_column1_column2] ON [schema.table] ([column1], [column2])'
```
Comment (janmeier) [inline test/unit/sql/index.test.js]: Hmm, this test looks off to me .. I don't see a reason to call `sql.quoteTable(sql.addSchema` - Add index should take care of that

File: lib/dialects/abstract/query-generator.js [hunk 3]
```diff
@@ -479,7 +479,7 @@ module.exports = (function() {
       }
 
       options.prefix = options.prefix || rawTablename || tableName;
-      if (options.prefix) {
+      if (options.prefix && options.prefix.replace !== void 0) {
```
Comment (janmeier) [inline lib/dialects/abstract/query-generator.js]: I think `_.isString` is more readable here

File: test/integration/dialects/postgres/query-generator.test.js [hunk 4]
```diff
@@ -870,7 +873,7 @@ if (dialect.match(/^postgres/)) {
           expectation: 'CREATE INDEX \"bar\" ON \"User\" (\"username\", \"isAdmin\")'
         }, {
           arguments: ['mySchema.User', ['username', 'isAdmin'], {}, 'User'],
```
Comment (janmeier) [inline test/integration/dialects/postgres/query-generator.test.js]: Hmm, is this a BC break @mickhansen - If the user passes tablename with schema as a string to addIndex it won't work. But we could argue that that was never the intended usage

File: test/unit/sql/index.test.js (hunk 2 above)
Comment (mickhansen) [inline test/unit/sql/index.test.js]: `[schema.table]` will be wrong for PG atleast i think.

Comment (janmeier) [inline test/unit/sql/index.test.js]: I think the problem here is that the argument passed is the string `schema.table` - the function should be passed a table + schema object

Comment (mickhansen) [inline test/unit/sql/index.test.js]: Yeah i added the test for BC with older PG query generator tests.

File: test/integration/dialects/postgres/query-generator.test.js (hunk 4 above)
Comment (mickhansen) [inline test/integration/dialects/postgres/query-generator.test.js]: True but when using migrations it will be much cleaner to type `schema.table` than `{schema: schema, table: table}`

Comment (janmeier) [inline test/integration/dialects/postgres/query-generator.test.js]: True .. (this is actually the same discussion as we are having below, right :D ?)

Then perhaps if tablename = string, use `quoteIdentifiers` else `quoteTable`?

(Sorry for being so indecisive @mikrofusion - but we need to make sure we still support legacy usecases + migrations)

Comment (mickhansen) [inline test/integration/dialects/postgres/query-generator.test.js]: Guess so.
I forgot what `quoteIdentifiers` does, does it split on `.`? If so yes that could probably work.

Comment (janmeier) [inline test/integration/dialects/postgres/query-generator.test.js]: Yes - that's what we had before

File: lib/dialects/abstract/query-generator.js (hunk 3 above)
Comment (mikrofusion) [inline lib/dialects/abstract/query-generator.js]: Good call.  I'll change this.

File: test/unit/sql/index.test.js (hunk 2 above)
Comment (mikrofusion) [inline test/unit/sql/index.test.js]: I'll undo the change to this file in hopes that I can make a change in the query-generator.js that prevents other specs from needing to be changed.

**Comment by mikrofusion** [comment]
@janmeier @mickhansen I went ahead and reverted the original spec changes to ensure the changes didn't break backwards compatibility. I went ahead and made the ``` if tablename = string, use quoteIdentifiers else quoteTable ``` change and it seemed to do the trick. 
Please review and let me know your thoughts.

File: test/integration/dialects/postgres/query-generator.test.js [hunk 5]
```diff
@@ -856,6 +856,9 @@ if (dialect.match(/^postgres/)) {
           arguments: ['User', ['username', 'isAdmin'], {}, 'User'],
           expectation: 'CREATE INDEX \"user_username_is_admin\" ON \"User\" (\"username\", \"isAdmin\")'
         }, {
+          arguments: [{schema: 'mySchema', tableName: 'myTable'}, ['username', 'isAdmin'], {}, 'User'],
+          expectation: 'CREATE INDEX \"user_username_is_admin\" ON \"mySchema\".\"myTable\" (\"username\", \"isAdmin\")'
```
Comment (mickhansen) [inline test/integration/dialects/postgres/query-generator.test.js]: https://github.com/sequelize/sequelize/blob/master/test/unit/sql/index.test.js

Could you add a test here instead? We're working on removing SQL tests from the integration test suite.

**Comment by mickhansen** [comment]
Looks good, just the one comment about test location.
If you could squash to a single descriptive commit and add a changelog entry we're good to go :)

**Comment by mikrofusion** [comment]
@mickhansen @janmeier - I've moved the spec to ``` test/unit/sql/index.test.js ``` as suggested.  Changelog entry added and commits squashed.  
Please let me know if anything else is needed.

**Comment by mickhansen** [comment]
@mikrofusion Merged, thank you :)
