### PR TITLE
Fixes bulkCreate, Now it properly maps fields to attributes

### LINKED ISSUE #3764: Returned instances from bulkCreate contain values with field keys rather than attribute keys

### LINKED ISSUE #3789: Returned instances from update contain values with field keys rather than attribute keys
I think this is very similar to this: #3764
When Model.update is used with { returning: true } option, instance has field keys rather than attribute keys.

### LINKED ISSUE #3908: Missing column "createdAt" when using "field" param with bulkCreate command
I have this error since upgrading to 3.0: (`"sequelize": "^3.2.0"` to be precise)
```
{ [SequelizeDatabaseError: column "createdAt" of relation "store_table" does not exist]
  name: 'SequelizeDatabaseError',
  message: 'column "createdAt" of relation "store_table" does not exist',
  parent:
   { [error: column "createdAt" of relation "store_table" does not exist]
     name: 'error',
     length: 124,
     severity: 'ERROR',
     code: '42703',
     detail: undefined,
     hint: undefined,
     position: '59',
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'parse_target.c',
     line: '923',
     routine: 'checkInsertTargets',
```

And field is defined:
```
module.exports = function(sequelize) {
  'use strict';

  var DataTypes = require('sequelize');

  return sequelize.define(
    'store_table', {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true
      },

      brandId: {
        type: DataTypes.INTEGER,
        field: 'brand_id',
        references: 'brand',
        referencesKey: 'id'
      },

      name: {
        type: DataTypes.STRING,
        allowNull: true,
        validate: {
          len: [1, 64]
        }
      },

      address: {
        type: DataTypes.TEXT,
        allowNull: true,
        validate: {
          len: [1, 256]
        }
      },

      createdAt: {
        type: DataTypes.DATE,
        field: 'created_at'
      },

      updatedAt: {
        type: DataTypes.DATE,
        field: 'updated_at'
      }

    }, {
      freezeTableName: true
    }
  );
};
```
And present in the DB, obviously under the name of `created_at`.
After reading this issue: https://github.com/sequelize/sequelize/issues/2641 I tried by adding `underscored: true` flag and it does work as before.

The issue is only present on the bulkCreate

### LINKED ISSUE #4103: bulkCreate does not understand timestamps renamed fields
Migration from 2.0.x to 3.x I have some issue with `bulkCreate`

> SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'createdAt' in 'field list'

I have this

```javascript
{
        createdAt: {
            type: DataTypes.DATE,
            field: 'created_at'
        },
        updatedAt: {
            type: DataTypes.DATE,
            field: 'updated_at'
        },
        deletedAt: {
            type: DataTypes.DATE,
            field: 'deleted_at'
        }
}
```

and `timestamp` at `true` in my model definition

### LINKED ISSUE #4476: BUG in bulkCreate: Not properly converting column names to snake case in the database
Hey guys,
Found a bug and/or inconsistency between create and bulkCreate.

Model:
```js
    var model = sequelize.define('Group', {
        name: {
            type: DataTypes.STRING,
            field: 'name',
            allowNull: false
        },
        description: {
            type: DataTypes.STRING,
            field: 'description',
            allowNull: true
        },
        createdAt: {
            field: 'created_at',
            type: DataTypes.DATE
        },
        updatedAt: {
            field: 'updated_at',
            type: DataTypes.DATE
        }
    }, {
        tableName: 'groups',
        classMethods: {
            associate: function (models) {
                model.belongsToMany(models.User, {through: 'UserGroup', foreignKey: 'user_id'});
            }
        }
    });
```

When calling:
```js
Group.create({
        id: 1,
        name: 'Administrators',
        description: 'Administrators'
});
```
Everything works as expected.

But when calling:
```js
Group.bulkCreate([{
        id: 1,
        name: 'Administrators',
        description: 'Administrators'
}]);
```
A sequelize error is raised stating that createdAt column doesn't exist - But I specifically defined that createdAt has field 'created_at'. Full error:
```js
{
   "name":"SequelizeDatabaseError",
   "message":"ER_BAD_FIELD_ERROR: Unknown column 'createdAt' in 'field list'",
   "parent":{
      "code":"ER_BAD_FIELD_ERROR",
      "errno":1054,
      "sqlState":"42S22",
      "index":0,
      "sql":"INSERT INTO `groups` (`id`,`name`,`description`,`createdAt`,`updatedAt`) VALUES (1,'Administrators','Administrators','2015-09-12 12:47:24','2015-09-12 12:47:24'),(2,'Users','Users','2015-09-12 12:47:24','2015-09-12 12:47:24'),(3,'Resellers','Resellers','2015-09-12 12:47:24','2015-09-12 12:47:24');"
   },
   "original":{
      "code":"ER_BAD_FIELD_ERROR",
      "errno":1054,
      "sqlState":"42S22",
      "index":0,
      "sql":"INSERT INTO `groups` (`id`,`name`,`description`,`createdAt`,`updatedAt`) VALUES (1,'Administrators','Administrators','2015-09-12 12:47:24','2015-09-12 12:47:24'),(2,'Users','Users','2015-09-12 12:47:24','2015-09-12 12:47:24'),(3,'Resellers','Resellers','2015-09-12 12:47:24','2015-09-12 12:47:24');"
   },
   "sql":"INSERT INTO `groups` (`id`,`name`,`description`,`createdAt`,`updatedAt`) VALUES (1,'Administrators','Administrators','2015-09-12 12:47:24','2015-09-12 12:47:24'),(2,'Users','Users','2015-09-12 12:47:24','2015-09-12 12:47:24'),(3,'Resellers','Resellers','2015-09-12 12:47:24','2015-09-12 12:47:24');"
}
```

Essentially what happens is that the conversion is not happening in bulkCreate like in create (where it is the expected behavior).

I'm using version: 3.8.0

Thanks!
Ilai

### LINKED ISSUE #4600: bulkCreate with updateOnDuplicate broken when field names different than column names.
Dialect: mysql
Sequelize Version: 3.9.0

I've got an Event model:

```
id: {
   ...
   field: "event_id"
},
group: {
   ...
   field: "group_id"
},
start: {
   ...
   field: "start_date"
},
end: {
   ...
   field: "end_date"
},
content: {
   ...
   field: "content"
},
type: {
   ...
   field: "type"
} 
```

Notice that some fields of this object have different corresponding column names in the table they're stored in.

Now when I try to do a bulkUpdate with the following code: 

```
models.Event.bulkCreate(uEvents, {
        fields: ['id', 'start', 'end', 'type', 'group', 'content', 'title', 'updatedAt'],
        updateOnDuplicate: ["start_date", "end_date", "type", "group_id", "content", "title", "updatedAt"]
    })
```

Sequelize generates the following SQL:

```
INSERT INTO `events` (`event_id`,`start_date`,`end_date`,`type`,`group_id`,`content`,`title`,`updatedAt`,`createdAt`) 
	VALUES (4,'2016-04-01 00:00:00','2016-06-30 00:00:00','range',6,'Directory Launch Phase II','Maintenance and Feature Addition','2015-09-18 16:43:25','2015-10-01 20:32:14'),
		   (3,'2016-01-01 00:00:00','2016-04-01 00:00:00','range',6,'Directory Launch Phase I','Initial Launch for Directory and API','2015-09-18 16:42:52','2015-10-01 20:32:14') 

	ON DUPLICATE KEY UPDATE `content`=VALUES(`content`),`title`=VALUES(`title`),`type`=VALUES(`type`),`updatedAt`=VALUES(`updatedAt`);
```

Notice that the only fields included in the UPDATE clause are those who share their name with their table column.

Ok, so what if we try identifying the `updateOnDuplicate` fields to their property names, e.g.:

`updateOnDuplicate: ["id", "start", ...]`

No dice. We get SQL that looks like this:

```
ON DUPLICATE KEY UPDATE `group`=VALUES(`group`),`start`=VALUES(`start`),`end`=VALUES(`end`),`content`=VALUES(`content`),`title`=VALUES(`title`),`type`=VALUES(`type`),`updatedAt`=VALUES(`updatedAt`)
```

which results in an `ER_BAD_FIELD_ERROR` since the *column* names are never aliased as *table* names, and the database knows to insert into `group_id`, but doesn't know what the hell `group` is.

In short: The `options.fields` and `options.updateOnDuplicate` arguments are using different ways of referring to field names, and there's no way to make them line up (that I'm aware of).

### PR DESCRIPTION
**Pull request by sushantdhiman**
### Pull Request check-list

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does your issue contain a link to existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Have you added an entry under `Future` in the changelog?

### Description of change

Closes #4476 
Closes #3908
Closes #4103
Closes #3764
Closes #4600
Closes #4646 (PR Test case)
Closes #3789

Now `fields` will be properly maps to `attributes`

### CODE REVIEW

File: lib/model.js [hunk 1]
```diff
@@ -2102,10 +2102,12 @@ class Model {
 
         // set createdAt/updatedAt attributes
         if (createdAtAttr && !values[createdAtAttr]) {
-          values[createdAtAttr] = now;
+          let createdAtField = instance.rawAttributes[createdAtAttr].field;
+          values[createdAtField ? createdAtField : createdAtAttr] = now;
```
Comment (BridgeAR) [inline lib/model.js]:
```js
createdAtField ? createdAtField : createdAtAttr
```
could also be written as
```js
createdAtField || createdAtAttr
```

File: lib/model.js [hunk 2]
```diff
@@ -2102,10 +2102,12 @@ class Model {
...
         if (createdAtAttr && !values[createdAtAttr]) {
-          values[createdAtAttr] = now;
+          let createdAtField = instance.rawAttributes[createdAtAttr].field;
+          values[createdAtField || createdAtAttr] = now;
         }
         if (updatedAtAttr && !values[updatedAtAttr]) {
-          values[updatedAtAttr] = now;
+          let updatedAtField = instance.rawAttributes[updatedAtAttr].field;
+          values[updatedAtField || updatedAtAttr] = now;
         }
```
Comment (mickhansen) [inline lib/model.js]: could also simply move this section above the mapValueFieldNames call

Comment (sushantdhiman) [inline lib/model.js]: I can move the `let` section but `if` check and `values` assignment should remain below the call. Will that be good ?

Comment (sushantdhiman) [inline lib/model.js]: @mickhansen this code block depend upon `values`, which are generated by `mapValueFieldNames` call. It can't be moved before that.

**Comment by sushantdhiman** [comment]
@mickhansen @janmeier Any changes ?

File: lib/model.js (hunk 2 above)
Comment (mickhansen) [inline lib/model.js]:
```
let values = instance.dataValues
// timestamp changes
values = mapValueFieldNames(values);
```

Comment (sushantdhiman) [inline lib/model.js]: Breaking 4 tests

**Comment by sushantdhiman** [comment]
WARNING: DO NOT MERGE

**Comment by sushantdhiman** [comment]
@mickhansen @janmeier Its ready

File: lib/model.js [hunk 3]
```diff
@@ -2101,9 +2104,10 @@ class Model {
         // Map attributes for serial identification
         const attributes = {};
         for (const attr in this.tableAttributes) {
-          attributes[attr] = this.rawAttributes[attr];
           if (this.rawAttributes[attr].field) {
             attributes[this.rawAttributes[attr].field] = this.rawAttributes[attr];
```
Comment (mickhansen) [inline lib/model.js]: i actually think `field` is always present now and will simply default to `name`

Comment (sushantdhiman) [inline lib/model.js]: Yup `mapFIeldName` is already handling it.

Comment (mickhansen) [inline lib/model.js]: Was referring to `rawAttributes`, not sure mapFieldName helps here.

Comment (sushantdhiman) [inline lib/model.js]: As `field` is always set , we can do `attributes[this.rawAttributes[attr].field]` ?

Comment (mickhansen) [inline lib/model.js]: IIRC, yes

Comment (sushantdhiman) [inline lib/model.js]: Done

**Comment by sushantdhiman** [comment]
Ping @mickhansen

**Comment by mickhansen** [comment]
LGTM, /cc @janmeier

File: test/integration/model/create.test.js [hunk 4]
```diff
@@ -1808,6 +1808,48 @@ describe(Support.getTestDialectTeaser('Model'), function() {
...
+        expect(m.name).to.be.eql(M1.name);
+        expect(m.secret).to.be.eql(M1.secret);
+
+        return Maya.bulkCreate([M2]);
+      }).spread((m) => {
+
+        // fields are preserved
+        expect(m.createdAt).to.be.ok;
+        expect(m.created_at).to.not.exist;
+        expect(m.secret_given).to.not.exist;
```
Comment (janmeier) [inline test/integration/model/create.test.js]: This will never exist, right (does it fail without the changes)? We only provide getters for attribute names - I think this should be `.get('secret_given')`

Comment (sushantdhiman) [inline test/integration/model/create.test.js]: There was an issue where `fields` and `attributes` both were being returned. `secret_given` is field name for `secret`. Without current fix It will have both `secret` and `secret_given`

We are checking if only `attributes` are being returned, there are no `fields` in the mix

Comment (mickhansen) [inline test/integration/model/create.test.js]: Then you should use `.get()` to make sure it's not present in `dataValues`.

File: changelog.md [hunk 5]
```diff
@@ -25,6 +25,7 @@
 - [FIXED] `upsert` does not fail anymore on not null validations [#5711](https://github.com/sequelize/sequelize/issues/5711)
 - [FIXED] Don't remove includes from count queries and unify findAndCount and count queries. [#6123](https://github.com/sequelize/sequelize/issues/6123)
 - [FIXED] `Model.count` with `options.col` and `options.include` works properly now
+- [FIXED] `bulkCreate` don't map fields to attributes properly [#4476](https://github.com/sequelize/sequelize/issues/4476)[#3908](https://github.com/sequelize/sequelize/issues/3908)[#4103](https://github.com/sequelize/sequelize/issues/4103)[#3764](https://github.com/sequelize/sequelize/issues/3764)[#4476](https://github.com/sequelize/sequelize/issues/4476)
```
Comment (BridgeAR) [inline changelog.md]: 4476 is duplicated and using spaces or commata would be nice.

File: test/integration/model/create.test.js (hunk 4 above)
Comment (sushantdhiman) [inline test/integration/model/create.test.js]: Added the `get` check. There are no fields in `dataValues` as well. Test pass on local env.

File: changelog.md (hunk 5 above)
Comment (sushantdhiman) [inline changelog.md]: Noticed that :), I have changed it

**Comment by sushantdhiman** [comment]
Any other change ?

**Comment by remojansen** [comment]
Hi guys, It looks like the return of `bulkCreate` is not transforming the names into camelCase in version 3.30.4. Is that a bug?

**Comment by sushantdhiman** [comment]
@remojansen Its in `v4` i.e. master branch, not fixed for v3 branch

**Comment by remojansen** [comment]
Thanks for answering, do you have an idea bout then will v4 be released? Thanks

**Comment by abZameen** [comment]
Hey guys, I am still facing the issue on Sequelize 4.4.2.

**Comment by Thyoity** [comment]
I am facing the same issue on Sequelize 4.4.25. bulkCreate() is not mapping fields correctly when I use snake-case in the mysql structure and camel-case in model definitions.

**Comment by jho2n** [comment]
exactly same with @Thyoity  +1

**Comment by keech** [comment]
exactly same with @Thyoity +1

**Comment by kukukk** [comment]
Hi,

I have the same problem as @Thyoity on Sequelize 4.32.1. Any info about the fix?

Thanks.

**Comment by sushantdhiman** [comment]
Why you all are commenting here :), This PR does not address `updateOnDuplicate` case. There is already an issue for that https://github.com/sequelize/sequelize/issues/9016

If you guys want to help, have a look at this PR https://github.com/sequelize/sequelize/pull/9019
