### PR TITLE
Fix 9515: sync() with "alter:true" doesn't use field name in model definition

### LINKED ISSUE #9515: sync() with "alter:true" doesn't use field name in model definition
## What are you doing?

I have a model which is defined like
```js
sequelize.define(‘Test’, {
      test_key: {
          field: ‘testKey’,
          type: DataTypes.BIGINT,
          allowNull: false
      },
})
```
Then I tried to generate the schema by calling
```js
sequelize.sync({ alter: true, force: true })
```
I was expecting the column name to be created as "test_key", but it turns out to be "testKey"

And when I tried to call sync() without "alter:true" like
```js
sequelize.sync({ force: true })
```
Everything works fine.
So there might be a issue for the alter functionality, please help to look into this.

## What do you expect to happen?
I expected sync() with "alter:true" use the "field" option to create the column name.

## What is actually happening?
But sync() with "alter:true" ignores the  "field" option

__Dialect:__ postgres
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ 4.37.10
__Tested with latest release:__ 4.37.10

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

### PR DESCRIPTION
**Pull request by mjcmatrix**
Closes #9515

### CODE REVIEW

File: lib/model.js [hunk 1]
```diff
@@ -1247,11 +1248,11 @@ class Model {
 
               _.each(attributes, (columnDesc, columnName) => {
                 if (!columns[columnName]) {
-                  changes.push(() => this.QueryInterface.addColumn(this.getTableName(options), columnName, attributes[columnName]));
+                  changes.push(() => this.QueryInterface.addColumn(this.getTableName(options), attributes[columnName].field || columnName, attributes[columnName]));
                 }
               });
               _.each(columns, (columnDesc, columnName) => {
-                const currentAttributes = attributes[columnName];
+                const currentAttributes = rawAttributes[columnName];
```
Comment (sushantdhiman) [inline lib/model.js]: rename `currentAttributes` to `currentAttribute`

**Comment by lyh2668** [comment]
Why is this problem not fixed in version 4.41.2?

**Comment by lyh2668** [comment]
@sushantdhiman I upgraded the version to the version 5.0.0-beta.14 and still have this problem.
