### PR TITLE
Fix field name mapping issue for bulk create queries with ON DUPLICATE UPDATE

### LINKED ISSUE #9016: BulkCreate: updateOnDuplicate option is not mapping fields correctly
## What are you doing?

Hi guys,
I have found that bulkCreate with updateOnDuplicate option is not mapping fields correctly when I use snake-case in the mysql structure and camel-case in model definitions.

Model:
```js
const Model = sequelize.define('userCallUp', {
        id: {
            type: DataTypes.INTEGER(10).UNSIGNED,
            allowNull: false,
            primaryKey: true,
            autoIncrement: true,
            field: 'id'
        },
        idCallUp: {
            type: DataTypes.INTEGER(10).UNSIGNED,
            allowNull: false,
            references: {
                model: 'callUp',
                key: 'id'
            },
            field: 'id_call_up'
        },
        idUser: {
            type: DataTypes.INTEGER(10).UNSIGNED,
            allowNull: true,
            references: {
                model: 'user',
                key: 'id'
            },
            field: 'id_user'
        },
        number: {
            type: DataTypes.INTEGER(3).UNSIGNED,
            allowNull: true,
            field: 'number'
        },
        nickname: {
            type: DataTypes.CHAR(255),
            allowNull: true,
            field: 'nickname'
        },
        group: {
            type: DataTypes.ENUM('bench','pitch','coachs'),
            allowNull: false,
            defaultValue: 'bench',
            field: 'group'
        },
        createdAt: {
            type: DataTypes.DATE,
            allowNull: true,
            field: 'created_at'
        },
        updatedAt: {
            type: DataTypes.DATE,
            allowNull: true,
            field: 'updated_at'
        },
        deletedAt: {
            type: DataTypes.DATE,
            allowNull: true,
            field: 'deleted_at'
        }
    }, {
        tableName: 'user_call_up'
    });
```

When calling:
```
const usersCallsUp = [{
                        "idCallUp": 21,
                        "idUser": 500,
                        "number": null,
                        "nickname": null,
                        "group": "coachs"
                    },{
                        "idCallUp": 21,
                        "idUser": 501,
                        "number": 1,
                        "nickname": null,
                        "group": "pitch"
                    }];
UserCallUp.bulkCreate(usersCallsUp, {updateOnDuplicate: ['idUser', 'number', 'nickname', 'group']});
```
## What do you expect to happen?
I expect that all fields that are including in the updateOnDuplicate option were mapping propertly on ON DUPLICATE KEY UPDATE clause of SQL query.
Expected SQL query:
```
INSERT INTO `user_call_up` (`id`,`id_call_up`,`id_user`,`group`,`created_at`,`updated_at`,`number`) VALUES (NULL,21,500,'coachs','2018-02-08 17:14:09','2018-02-08 17:14:09',NULL),(NULL,21,501,'pitch','2018-02-08 17:14:09','2018-02-08 17:14:09',1) ON DUPLICATE KEY UPDATE `id_user`=VALUES(`id_user`),`number`=VALUES(`number`),`nickname`=VALUES(`nickname`),`group`=VALUES(`group`);
```

## What is actually happening?
A sequelize error is raised because on ON DUPLICATE KEY UPDATE the field "idUser" is not mapping correctly to "id_user" which is the correct field on database. (camelCase to snake_case)
Sequelize error:
```
{ SequelizeDatabaseError: Unknown column 'idUser' in 'field list' ... }
```
SQL query:
```
INSERT INTO `user_call_up`
(`id`,`id_call_up`,`id_user`,`group`,`created_at`,`updated_at`,`number`) VALUES (NULL,21,500,'coachs','2018-02-08 17:14:09','2018-02-08 17:14:09',NULL),(NULL,21,501,'pitch','2018-02-08 17:14:09','2018-02-08 17:14:09',1) ON DUPLICATE KEY UPDATE `idUser`=VALUES(`idUser`),`number`=VALUES(`number`),`nickname`=VALUES(`nickname`),`group`=VALUES(`group`);
```
Also, if you include the value of database field "id_user" into the array like that, ['id_user', 'number', 'nickname', 'group'], sequelize ignore this field to the clause.

__Dialect:__ mysql
__Dialect version:__ 2.11.1
__Database version:__ 5.7.18
__Sequelize version:__ 4.33.0
__Tested with latest release:__ 4.33.0

Thanks!
Manu Rua

### PR DESCRIPTION
**Pull request by andriis**
Close #9016

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](../CONTRIBUTING.md)?

### CODE REVIEW

File: lib/dialects/abstract/query-generator.js [hunk 1]
```diff
@@ -217,41 +217,48 @@ const QueryGenerator = {
     Parameters: table name + list of hashes of attribute-value-pairs.
    @private
   */
-  bulkInsertQuery(tableName, attrValueHashes, options, rawAttributes) {
+  bulkInsertQuery(tableName, fieldValueHashes, options, fieldMappedAttributes) {
```
Comment (sushantdhiman) [inline lib/dialects/abstract/query-generator.js]: Might seems like API change but internally this was already the case, `attrValueHashes` are actually values mapped by their field names. Same is true for `rawAttributes`. So I have renamed these arguments

File: test/unit/sql/insert.test.js [hunk 2]
```diff
@@ -109,10 +104,11 @@ describe(Support.getTestDialectTeaser('SQL'), () => {
         timestamps: true
       });
 
-      expectsql(sql.bulkInsertQuery(User.tableName, [{ user_name: 'testuser', pass_word: '12345' }], { updateOnDuplicate: ['username', 'password', 'updatedAt'] }, User.rawAttributes),
+      expectsql(sql.bulkInsertQuery(User.tableName, [{ user_name: 'testuser', pass_word: '12345' }], { updateOnDuplicate: ['user_name', 'pass_word', 'updated_at'] }, User.fieldRawAttributesMap),
```
Comment (sushantdhiman) [inline test/unit/sql/insert.test.js]: a breaking change?

What this test assumes seems incorrect to me, if records are mapped by field name so should `updateOnDuplicate` values. `bulkInsertQuery` should just use whatever data given to it to generate query as its a low level API, converting attributes to fields etc stuff should be handled at model level api.

I think it should be ok to merge this change, `records` are expected to be mapped by field name so should `updateOnDuplicate`
