### PR TITLE
Fix `Instance.decrement` precision problems

### LINKED ISSUE #7112: Instance.decrement losing precision in big numbers
## What you are doing?
When calling `Instance.decrement` to decrement a specific column value, _Sequelize_ internally it uses the `Instance.increment` with the negative value. When converting the value to its negative form it loses precision right [here](https://github.com/sequelize/sequelize/blob/6f9a53bfa542f962e5df1892657d607a2c6318ab/lib/model.js#L3840) (**due to Javascript floating point problem**).

## What do you expect to happen?
For a given big number value `'1123.123456789012345678'` in its _string_ form, I was expecting a query like this:
```sql
UPDATE x = x - '1123.123456789012345678';
```

## What is actually happening?
It is using the `Instance.increment` with the Javascript negative form of the input value:
```sql
UPDATE x = x + '-1123.1234567890124';
```

Example of the JS issue:
```bash
❯ node
> const x = '1123.123456789012345678'; -x
-1123.1234567890124
```

The issue is actually in the negative form of the value. 

I'm willing to add a PR to fix this, but we have 2 choices:
- Fix the interpretation of the negative form of the value (keeping the hack)
- Implement the decrement method in the query interface to use the database subtract operator and to prevent the mutation of the input value (**IMHO** I prefer this one).

__Dialect:__  postgres
__Database version:__ 9.5.4
__Sequelize version:__ 3.23.2

### PR DESCRIPTION
**Pull request by pedrobranco**
Closes #7112.

### Pull Request check-list
- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does your issue contain a link to existing issue (Closes #[issue]) or a description of the issue you are solving?

### Description of change

As suggested by the issue #7112:
- Reuse and rename the `query-generator::incrementQuery()` to `query-generator::incrementOrDecrementQuery()`, which now receives a boolean argument to represent the intention of incrementing or decrementing.
- Rename `query-interface::increment()` to `query-interface::incrementOrDecrement()` to pass the option `options.increment`.
- Change the `model::decrement()` implementation to call `model::increment()` with the option `increment = false`.

Doubts: Tests are passing (`npm run test-docker`), but should we add any test for this internal change?

### CODE REVIEW

File: lib/dialects/abstract/query-generator.js [hunk 1]
```diff
@@ -385,12 +386,17 @@ const QueryGenerator = {
                  If you use a string, you have to escape it on your own.
    @private
   */
-  incrementQuery(tableName, attrValueHash, where, options) {
+  incrementOrDecrementQuery(increment, tableName, attrValueHash, where, options) {
```
Comment (sushantdhiman) [inline lib/dialects/abstract/query-generator.js]: rather than `increment`, pass `operator` directly instead

File: lib/query-interface.js [hunk 2]
```diff
@@ -637,8 +637,8 @@ class QueryInterface {
     );
   }
 
-  increment(instance, tableName, values, identifier, options) {
-    const sql = this.QueryGenerator.incrementQuery(tableName, values, identifier, options.attributes);
+  incrementOrDecrement(instance, tableName, values, identifier, options) {
```
Comment (sushantdhiman) [inline lib/query-interface.js]: We will still keep `increment / decrement` in query generator , which will call `incrementOrDecrementQuery` with different operators

**Comment by sushantdhiman** [comment]
@pedrobranco 

PR needs some work

- It will be better to expose `increment`  and `decrement` methods which pass different `operator` to `incrementOrDecrementQuery`
- we need unit test around `increment`, `decrement` and `incrementORDecrementQuery`

File: lib/dialects/abstract/query-generator.js (hunk 1 above)
Comment (pedrobranco) [inline lib/dialects/abstract/query-generator.js]: Sure.

File: lib/query-interface.js (hunk 2 above)
Comment (pedrobranco) [inline lib/query-interface.js]: In `model.js`: 
- we keep the `decrement()` calling `this.increment()` ? or 
- we replicate the same code from `increment()` to `decrement()` ? or
- abstract the `increment()` internals to another method to be able to call `decrement()` in query-generator?

Comment (sushantdhiman) [inline lib/query-interface.js]: `Model.decrement` will call `Model.increment`  with `{increment: false}` as its is doing already, at last step we use `increment` to choose between `incrementQuery` or `decrementQuery`.

We will keep `incrementOrDecrementQuery` private, may be rename it to `arithmeticQuery` as well

**Comment by pedrobranco** [comment]
@sushantdhiman PR addressed. Can you explain why tests are failing?

File: lib/query-interface.js [hunk 3]
```diff
@@ -638,7 +638,17 @@ class QueryInterface {
   }
 
   increment(instance, tableName, values, identifier, options) {
-    const sql = this.QueryGenerator.incrementQuery(tableName, values, identifier, options.attributes);
+    const sql = this.QueryGenerator.arithmeticQuery(' + ', tableName, values, identifier, options.attributes);
```
Comment (sushantdhiman) [inline lib/query-interface.js]: we can run this without adding extra spaces, right.

If yes, we should not add any extra spaces. May be query generator should handle that if absolutely required, otherwise send query without spaces

Comment (pedrobranco) [inline lib/query-interface.js]: Right. I just kept the same format as before.

File: test/unit/dialects/mssql/query-generator.test.js [hunk 4]
```diff
@@ -171,5 +171,34 @@ if (current.dialect.name === 'mssql') {
         mssql: 'ALTER TABLE [myTable] DROP [myColumnKey]'
       });
     });
+
```
Comment (pedrobranco) [inline test/unit/dialects/mssql/query-generator.test.js]: @sushantdhiman Can you review this queries since it does not run in tests?

Comment (sushantdhiman) [inline test/unit/dialects/mssql/query-generator.test.js]: looks good, beside we have integration tests for increment/decrement so its verified

**Comment by sushantdhiman** [comment]
just needs a changelog entry and its good to go 👍

**Comment by pedrobranco** [comment]
>just needs a changelog entry and its good to go 👍

Done.

**Comment by pedrobranco** [comment]
Thanks @sushantdhiman.
