### PR TITLE
fix(query-generator): fix addColumn create comment

### LINKED ISSUE #4386: Comment property
If you open the url http://docs.sequelizejs.com/en/latest/docs/models-definition/ you can see that:

``` javascript
// Comments can be specified for each field for MySQL and PG
hasComment: { type: Sequelize.INTEGER, comment: "I'm a comment!" },
```

But this feature was not implemented in postgres dialect. I tried to add this in this PR https://github.com/sequelize/sequelize/pull/4385 but tests was failed. Somebody can fix it?

### PR DESCRIPTION
**Pull request by mirkojotic**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Resolves #4386 
More specifically https://github.com/sequelize/sequelize/issues/4386#issuecomment-433015711
This adds on the work @theRichu started around adding an ability to add a comment while using `addColumn` API.

Initial PR can be found here
https://github.com/sequelize/sequelize/pull/10076

### CODE REVIEW

File: lib/dialects/postgres/query-generator.js [hunk 1]
```diff
@@ -452,7 +452,7 @@ class PostgresQueryGenerator extends AbstractQueryGenerator {
     return fragment;
   }
 
-  attributeToSQL(attribute) {
+  attributeToSQL(attribute, option) {
```
Comment (sushantdhiman) [inline lib/dialects/postgres/query-generator.js]: `options`

Comment (mirkojotic) [reply lib/dialects/postgres/query-generator.js]: Done.

**Comment by sushantdhiman** [comment]
Thanks @mirkojotic

File: lib/dialects/postgres/query-generator.js [hunk 2]
```diff
@@ -535,7 +535,13 @@ class PostgresQueryGenerator extends AbstractQueryGenerator {
     }
 
     if (attribute.comment && _.isString(attribute.comment)) {
-      sql += ` COMMENT ${attribute.comment}`;
+      if (option && option.context === 'addColumn') {
+        const quotedAttr = this.quoteIdentifier(option.key);
+        const escapedCommentText = this.escape(attribute.comment);
+        sql += `; COMMENT ON COLUMN ${this.quoteTable(option.table)}.${quotedAttr} IS ${escapedCommentText}`;
```
Comment (normancarcamo) [inline lib/dialects/postgres/query-generator.js]: Is this feature working?
I need to put some comments into a column to let know others devs of a team a small description of what's the purpose of the column.

Comment (mirkojotic) [reply lib/dialects/postgres/query-generator.js]: @normancarcamo It was merged into master but you'll have to see which version of sequelize it will land in.

But also this is just the the addition to a PR merged a couple of months back that allowed this to be done on table creation. This PR is just so you could leverage this feature on `addColumn` API of query generator.

File: lib/dialects/mssql/query-generator.js [hunk 3]
```diff
@@ -239,11 +234,28 @@ class MSSQLQueryGenerator extends AbstractQueryGenerator {
     // FIXME: attributeToSQL SHOULD be using attributes in addColumnQuery
     //        but instead we need to pass the key along as the field here
     dataType.field = key;
+    let commentStr = '';
+
+    if (dataType.comment && _.isString(dataType.comment)) {
```
Comment (SimonSchick) [inline lib/dialects/mssql/query-generator.js]: Post merge comment: Should use `typeof`
