### PR TITLE
fix(types): add missing useCLS static

### LINKED ISSUE #10684: Property 'useCLS' does not exist on type 'typeof Sequelize'.

### PR DESCRIPTION
**Pull request by SimonSchick**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Fixes #10684

### CODE REVIEW

File: types/lib/sequelize.d.ts [hunk 1]
```diff
@@ -673,6 +673,15 @@ export class Sequelize extends Hooks {
...
   public static afterSync(fn: (options: SyncOptions) => HookReturn): void;
 
+  /**
+   * Use CLS with Sequelize.
+   * CLS namespace provided is stored as `Sequelize._cls`
+   * and bluebird Promise is patched to use the namespace, using `cls-bluebird` module.
+   *
+   * @param namespace
+   */
+  public static useCLS(namespace: object): typeof Sequelize;
```
Comment (SimonSchick) [inline types/lib/sequelize.d.ts]: Please note that I'm keeping it to `object` unless we want to create an interface with `bind` and `run` defined, I felt like this was too far reaching into cls tho.
