### PR TITLE
fix(model): destroying paranoid models with custom deletedAt

### LINKED ISSUE #11253: Soft-deleting paranoid model with custom deletedAt DB column name sets wrong attribute on instance
## What are you doing?

```js
const ParanoidUser = this.sequelize.define('ParanoidUser', {
  username: Support.Sequelize.STRING,

  // Custom DB column name
  deletedAt: {type: Support.Sequelize.DATE, field: 'deleted_at'}
}, {paranoid: true});

return ParanoidUser.sync({force: true}).then(() => {
  return ParanoidUser.create({
    username: 'username'
  });
}).then(user => {
  return user.destroy();
}).then(user => {
  // Both these assertions fail. Sequelize sets dataValues.deleted_at instead of deletedAt
  expect(user.dataValues.deletedAt).to.be.ok;
  expect(user.dataValues.deleted_at).to.not.be.ok;
});
```

**To Reproduce**
1. Define paranoid model with `deletedAt` that declares custom `field`
2. Soft delete model instance
3. Check resulting model instance

## What do you expect to happen?
`deletedAt` should be set.

## What is actually happening?
`deleted_at` is set.

## Environment
Dialect:
- [ ] mysql
- [ ] postgres
- [ ] sqlite
- [ ] mssql
- [x] any
Dialect **library** version: any
Database version: any
Sequelize version: master
Node Version: XXX
OS: XXX
If TypeScript related: TypeScript version: XXX
Tested with latest release:
- [ ] No
- [x] Yes, specify that version: master

### PR DESCRIPTION
**Pull request by gabegorelick**
Fixes #11253

### Pull Request check-list

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)? **N/A**
- [x] Did you update the typescript typings accordingly (if applicable)? **N/A**
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Fixes #11253

### CODE REVIEW

File: lib/model.js [hunk 1]
```diff
@@ -4052,29 +4052,17 @@ class Model {
...
-          if (this.constructor._versionAttribute && rowsUpdated < 1) {
-            throw new sequelizeErrors.OptimisticLockError({
-              modelName: this.constructor.name,
-              values,
-              where
-            });
-          }
-          return results;
-        });
+        return this.save(_.defaults({ hooks: false }, options));
```
Comment (gabegorelick) [inline lib/model.js]: Using `save` lets us reuse a lot of code.

File: test/integration/instance.test.js [hunk 2]
```diff
@@ -685,5 +685,104 @@ describe(Support.getTestDialectTeaser('Instance'), () => {
         expect(user.username).to.equal('Peter');
       });
     });
+
+    it('supports custom deletedAt field', function() {
```
Comment (gabegorelick) [inline test/integration/instance.test.js]: `restore` tests are still in here. Happy to move them to their own file if you want.

File: test/integration/instance/destroy.test.js [hunk 3]
```diff
@@ -76,24 +102,254 @@ describe(Support.getTestDialectTeaser('Instance'), () => {
...
       });
 
+      const logging = sinon.spy();
+
       return UserDelete.sync({ force: true }).then(() => {
         return UserDelete.create({ name: 'hallo', bio: 'welt' }).then(u => {
           return UserDelete.findAll().then(users => {
             expect(users.length).to.equal(1);
-            return u.destroy({
-              logging(sql) {
```
Comment (gabegorelick) [inline test/integration/instance/destroy.test.js]: This didn't verify that `logging` was actually called.

**Comment by papb** [comment]
Looks great to me! Superb PR.

File: test/integration/instance/destroy.test.js [hunk 4]
```diff
@@ -56,6 +56,32 @@ describe(Support.getTestDialectTeaser('Instance'), () => {
       });
     });
 
+    it('does not update deletedAt with custom default in subsequent destroys', function() {
```
Comment (gabegorelick) [inline test/integration/instance/destroy.test.js]: Pretty sure this is what's intended, although this test fails on `master`.

File: lib/model.js [hunk 5]
```diff
@@ -4052,29 +4052,18 @@ class Model {
...
-
-        values[field] = new Date();
-        where[field] = Object.prototype.hasOwnProperty.call(attribute, 'defaultValue')
+        const attributeName = this.constructor._timestampAttributes.deletedAt;
+        const attribute = this.constructor.rawAttributes[attributeName];
+        const defaultValue = Object.prototype.hasOwnProperty.call(attribute, 'defaultValue')
           ? attribute.defaultValue
           : null;
+        const currentValue = this.getDataValue(attributeName);
+        if (currentValue == defaultValue || _.isEqual(currentValue, defaultValue)) {
```
Comment (gabegorelick) [inline lib/model.js]: Needed to add `==` check for non-Postgres DBs. For some reason they can return `undefined` for `currentValue`, which is not `_.isEqual` to `null`.

**Comment by gabegorelick** [comment]
@papb Thanks. Tests are passing now. Most of the issues were in the tests not accounting for non-PG quirks (not supporting sub-second dates or Infinity).

File: test/integration/instance/destroy.test.js (hunk 3 above)
Comment (papb) [reply test/integration/instance/destroy.test.js]: Great catch! This reminded me of something I saw recently. I like how you fixed this, using sinon. Would you be willing to do something similar to refactor several other tests with a similar problem?

If you search for `expect(test).to.be.true` you will find 9 occurrences in tests, they all could be refactored to use sinon, would you like to do that?

(And perhaps, if the code gets too big, you could even create a support method to be reused around tests)

File: test/integration/instance.test.js [hunk 6]
```diff
@@ -685,5 +685,104 @@ describe(Support.getTestDialectTeaser('Instance'), () => {
...
+      }, { paranoid: true });
+
+      return ParanoidUser.sync({ force: true }).then(() => {
+        return ParanoidUser.create({
+          username: 'username'
+        });
+      }).then(user => {
+        return user.destroy();
+      }).then(user => {
+        return user.restore();
```
Comment (sushantdhiman) [inline test/integration/instance.test.js]:
```js
expect(user.dataValues.deletedAt).to.be.ok;
expect(user.dataValues.deleted_at).to.not.be.ok;
return user.restore();
```

File: test/integration/instance.test.js [hunk 7]
```diff
@@ -685,5 +685,104 @@ describe(Support.getTestDialectTeaser('Instance'), () => {
...
+      }, { paranoid: true, deletedAt: 'destroyTime' });
+
+      return ParanoidUser.sync({ force: true }).then(() => {
+        return ParanoidUser.create({
+          username: 'username'
+        });
+      }).then(user => {
+        return user.destroy();
+      }).then(user => {
+        return user.restore();
```
Comment (sushantdhiman) [inline test/integration/instance.test.js]:
```js
expect(user.dataValues.destroyTime).to.be.ok;
expect(user.dataValues.deletedAt).to.not.be.ok;
expect(user.dataValues.destroy_time).to.not.be.ok;
return user.restore();
```

File: lib/model.js (hunk 5 above)
Comment (gabegorelick) [reply lib/model.js]: Linting didn't like the extra parens around `currentValue == null && defaultValue == null` so I had to move it out into a variable:
```js
const undefinedOrNull = currentValue == null && defaultValue == null;
if (undefinedOrNull || _.isEqual(currentValue, defaultValue))
```

File: test/integration/instance.test.js (hunk 6 above)
Comment (gabegorelick) [reply test/integration/instance.test.js]: Done

File: test/integration/instance.test.js (hunk 7 above)
Comment (gabegorelick) [reply test/integration/instance.test.js]: Done

File: test/integration/instance/destroy.test.js (hunk 3 above)
Comment (papb) [reply test/integration/instance/destroy.test.js]: (of course, this could be in a separate PR, if you're willing to do it - has nothing to do with this PR)
