### PR TITLE
Fix arrow alias syntax fixes #7742

### LINKED ISSUE #7742: New arrow alias syntax breaks some queries in Sequelize 4.0.0 that worked in 4.0.0-2
When upgrading we found some broken queries. The error message looks like this:

> SequelizeDatabaseError: Unknown column 'purchaseOrder->customer.id' in 'on clause'

(The full query and error message are below.)

Looking at the generated SQL, it creates a `JOIN` using a table alias `purchaseOrder->customer` that is defined in a subquery. That table alias is not in scope in the place where it’s used.

In beta 4.0.0-2 it would have used `purchaseOrder.customer.id`, which works because that is an alias for one of the *column* names exposed by the subquery, and is in scope.

I’ve stripped it down to a basic example. This works in 4.0.0-2, but not in 4.0.0:

```javascript
//
// DB setup
//

const Sequelize = require('sequelize');

const sequelize = new Sequelize('bug_report', 'root', 'password', {
  host: 'localhost',
  port: 32769,
  dialect: 'mysql'
});

const Customer = sequelize.define('customer', {
  name: Sequelize.STRING
});

const ShippingAddress = sequelize.define('shippingAddress', {
  address: Sequelize.STRING,
  verified: Sequelize.BOOLEAN
});

const Order = sequelize.define('purchaseOrder', {
  description: Sequelize.TEXT
});

const Shipment = sequelize.define('shipment', {
  trackingNumber: Sequelize.STRING
});

Customer.hasMany(ShippingAddress);
ShippingAddress.belongsTo(Customer);

Customer.hasMany(Order);
Order.belongsTo(Customer);

Shipment.belongsTo(Order);
Order.hasOne(Shipment);

//
// Bug demo
//

async function f() {
  await sequelize.sync();

  const result = await Shipment.findOne({
    include: [
      {
        model: Order,
        required: true,
        include: [
          {
            model: Customer,
            include: [
              {
                model: ShippingAddress,
                where: { verified: true }
              }
            ]
          }
        ]
      }
    ]
  });

  console.log(result);
}

f();
```

And the generated SQL, and error message is:

```
SELECT `shipment`.*, `purchaseOrder->customer->shippingAddresses`.`id` AS `purchaseOrder.customer.shippingAddresses.id`, `purchaseOrder->customer->shippingAddresses`.`address` AS `purchaseOrder.customer.shippingAddresses.address`, `purchaseOrder->customer->shippingAddresses`.`verified` AS `purchaseOrder.customer.shippingAddresses.verified`, `purchaseOrder->customer->shippingAddresses`.`createdAt` AS `purchaseOrder.customer.shippingAddresses.createdAt`, `purchaseOrder->customer->shippingAddresses`.`updatedAt` AS `purchaseOrder.customer.shippingAddresses.updatedAt`, `purchaseOrder->customer->shippingAddresses`.`customerId` AS `purchaseOrder.customer.shippingAddresses.customerId` FROM (SELECT `shipment`.`id`, `shipment`.`trackingNumber`, `shipment`.`createdAt`, `shipment`.`updatedAt`, `shipment`.`purchaseOrderId`, `purchaseOrder`.`id` AS `purchaseOrder.id`, `purchaseOrder`.`description` AS `purchaseOrder.description`, `purchaseOrder`.`createdAt` AS `purchaseOrder.createdAt`, `purchaseOrder`.`updatedAt` AS `purchaseOrder.updatedAt`, `purchaseOrder`.`customerId` AS `purchaseOrder.customerId`, `purchaseOrder->customer`.`id` AS `purchaseOrder.customer.id`, `purchaseOrder->customer`.`name` AS `purchaseOrder.customer.name`, `purchaseOrder->customer`.`createdAt` AS `purchaseOrder.customer.createdAt`, `purchaseOrder->customer`.`updatedAt` AS `purchaseOrder.customer.updatedAt` FROM `shipments` AS `shipment` INNER JOIN `purchaseOrders` AS `purchaseOrder` ON `shipment`.`purchaseOrderId` = `purchaseOrder`.`id` LEFT OUTER JOIN `customers` AS `purchaseOrder->customer` ON `purchaseOrder`.`customerId` = `purchaseOrder->customer`.`id` LIMIT 1) AS `shipment` INNER JOIN `shippingAddresses` AS `purchaseOrder->customer->shippingAddresses` ON `purchaseOrder->customer.id` = `purchaseOrder->customer->shippingAddresses`.`customerId` AND `purchaseOrder->customer->shippingAddresses`.`verified` = true;
(node:64954) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SequelizeDatabaseError: Unknown column 'purchaseOrder->customer.id' in 'on clause'
```

__Dialect:__ mysql
__Database version:__ 5.6, 5.7
__Sequelize version:__ 4.0.0

### PR DESCRIPTION
**Pull request by ggrimbert**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [X] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [X] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [X] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [X] Did you follow the commit message conventions explained in CONTRIBUTING.md?

### Description of change
Fixes (https://github.com/sequelize/sequelize/issues/7742) and (https://github.com/sequelize/sequelize/issues/7710)

There was a problem while generating the join queries with the new syntax. In some cases, the joinOn is generated like this : 
```
joinOn = this.quoteIdentifier(`${asLeft}.${attrLeft}`);
```
So it uses the "->" syntax, but for this part, it needs the dot notation as the field in the subquery has been renamed with dots.

A test has been added in FindAll.js

### CODE REVIEW

File: lib/dialects/abstract/query-generator.js [hunk 1]
```diff
@@ -1456,7 +1456,7 @@ const QueryGenerator = {
         // The main model attributes is not aliased to a prefix
         joinOn = `${this.quoteTable(parent.as || parent.model.name)}.${this.quoteIdentifier(attrLeft)}`;
       } else {
-        joinOn = this.quoteIdentifier(`${asLeft}.${attrLeft}`);
+        joinOn = this.quoteIdentifier(`${asLeft.replace('->', '.')}.${attrLeft}`);
```
Comment (felixfbecker) [inline lib/dialects/abstract/query-generator.js]: could this contain more than one `->`?

File: test/integration/include/findAll.test.js [hunk 2]
```diff
@@ -2054,4 +2054,53 @@ describe(Support.getTestDialectTeaser('Include'), () => {
         });
     });
   });
+
+  it.only('should be able to generate a correct request with inner and outer join', function() {
```
Comment (felixfbecker) [inline test/integration/include/findAll.test.js]: remove .only

File: test/integration/include/findAll.test.js [hunk 3]
```diff
@@ -2054,4 +2054,53 @@ describe(Support.getTestDialectTeaser('Include'), () => {
...
+    ShippingAddress.belongsTo(Customer);
+
+    Customer.hasMany(Order);
+    Order.belongsTo(Customer);
+
+    Shipment.belongsTo(Order);
+    Order.hasOne(Shipment);
+
+    return this.sequelize.sync({ force: true })
+    .then(() => {
```
Comment (felixfbecker) [inline test/integration/include/findAll.test.js]: indent this

File: test/integration/include/findAll.test.js [hunk 4]
```diff
@@ -2054,4 +2054,53 @@ describe(Support.getTestDialectTeaser('Include'), () => {
...
+            include: [{
+              model: ShippingAddress,
+              where: { verified: true }
+            }]
+          }]
+        }]
+      })
+      .then(result => {
+        //We just want to check that the query correctly runs
+        expect(result).to.not.be.ok;
```
Comment (felixfbecker) [inline test/integration/include/findAll.test.js]: this assertion wouldn't fail if the query fails, so it doesn't seem to serve a purpose

File: lib/dialects/abstract/query-generator.js (hunk 1 above)
Comment (ggrimbert) [inline lib/dialects/abstract/query-generator.js]: Not in the tests I've done, but effectively I think it could contains more than only one ->

File: test/integration/include/findAll.test.js (hunk 3 above)
Comment (ggrimbert) [inline test/integration/include/findAll.test.js]: What indentation do you want ? I don't see what's wrong with this one

File: test/integration/include/findAll.test.js (hunk 4 above)
Comment (ggrimbert) [inline test/integration/include/findAll.test.js]: I don't want the assertion to do anything, it's just there to test something at the end to be sure that the query runs and everything's OK. If the query fails, It will not pass in "then".
This assertion as no other purpose than being sure the code goes into "then".

Comment (felixfbecker) [inline test/integration/include/findAll.test.js]: you don't need the whole then at all, the test will fail if the promise fails

File: test/integration/include/findAll.test.js (hunk 3 above)
Comment (felixfbecker) [inline test/integration/include/findAll.test.js]: +2 more

File: lib/dialects/abstract/query-generator.js (hunk 1 above)
Comment (felixfbecker) [inline lib/dialects/abstract/query-generator.js]: then you must use a regexp with `g` set

**Comment by ggrimbert** [comment]
Changes are done, any update ?

**Comment by natesilva** [comment]
We are waiting on this as well (#7742).

**Comment by felixfbecker** [comment]
Please fix ESLint errors

**Comment by ggrimbert** [comment]
Eslint errors fixed. 
Don't know why many tests fail...

**Comment by natesilva** [comment]
What’s the status -- is this just waiting on linting?

**Comment by ggrimbert** [comment]
Linting fixed.

Thanks @sushantdhiman  for merging the branches

**Comment by sushantdhiman** [comment]
Overall it looks good to me, but would like a review from @janmeier as well

**Comment by juanpaucar** [comment]
@sunshinewyin Is there any update on this? I'm really waiting on this

**Comment by sushantdhiman** [comment]
Please review @janmeier

**Comment by Alexsey** [comment]
Great Thank You for this fix!

**Comment by Alexsey** [comment]
It looks like the bug is still alive - to reproduce it you need to add an `order` parameter by the field that has a `field` in it's definition https://github.com/sequelize/sequelize/issues/8224

**Comment by Alexsey** [comment]
No, sorry, it's a different issue. The way to reproduce is just quite similar. And to face it you first need to fight the current one - bug behind the bug :(
