### PR TITLE
instance.changed() in beforeUpdate hook would always be false. Fixes #3631

### LINKED ISSUE #3631: Model.update - instance.changed() always false/empty in hooks
Prior to 2.1.0, when calling model.update() with the individualHooks option, a call to theUpdatedInstance.changed() within a beforeUpdate hook would return the values that have been updated and now it is always false/empty.

This modification to hooks.test.js makes the test fail.

```
diff --git a/test/integration/hooks.test.js b/test/integration/hooks.test.js
index 56a33a8..0c60141 100644
--- a/test/integration/hooks.test.js
+++ b/test/integration/hooks.test.js
@@ -3439,6 +3439,7 @@ describe(Support.getTestDialectTeaser('Hooks'), function() {
         });
 
         this.User.beforeUpdate(function(user, options, fn) {
+          expect(user.changed()).to.not.be.empty;
           user.beforeHookTest = true;
           fn();
         });
```

### PR DESCRIPTION
**Pull request by BridgeAR**
I also removed some old callbacks from some hooks.

### CODE REVIEW

**Comment by BridgeAR** [comment]
Green build

**Comment by janmeier** [comment]
LGTM - needs a rebase

File: lib/model.js [hunk 1]
```diff
@@ -1685,8 +1685,14 @@ module.exports = (function() {
             , different = false;
 
           return Promise.map(daos, function(dao) {
-            // Record updates in dao's dataValues
+            // Record updates in instances dataValues
             Utils._.extend(dao.dataValues, values);
+            // Set the changed fields on the instance
+            Utils._.forIn(valuesUse, function(newValue, attr) {
+              if (newValue !== dao._previousDataValues[attr]) {
+                dao.setDataValue(attr, newValue);
```
Comment (mickhansen) [inline lib/model.js]: Better to call `instance.changed(field)` rather than setting the value again.
